INSERT INTO sort (nom_sort,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Entrave planaire',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 heure',
        '18 mètres',
        'V, S, M (un bijou d''une valeur minimale de 1 000 po, que le sort consume)',
        '24 heures',
        'Grâce à ce sort, vous vous attachez de force les services d''un céleste, d''un élémentaire, d''une fée ou d''un fiélon. La créature doit se trouver à portée pendant toute la durée du sort. (En général, elle est d''abord invoquée au centre d''un cercle magique inversé où elle reste piégée le temps de l''incantation.) La cible doit faire un jet de sauvegarde de Charisme à la fin de l''incantation. Si elle échoue, elle est contrainte de vous servir pendant toute la durée du sort. Si elle a été invoquée ou créée via un autre sort, la durée de ce dernier se prolongejusqu''à égaler celle de l''entrave planaire.' || E'\n' || 'La créature liée doit suivre vos instructions au mieux de ses capacités. Vous pouvez lui demander de vous accompagner lors d''une aventure, de protéger un lieu ou de transmettre un message. La créature obéit à vos instructions à la lettre, mais si elle est hostile envers vous, elle peut tout à fait interpréter vos paroles de manière à satisfaire ses propres objectifs. Si la créature a exécuté vos instructions avant la fin du sort, elle revient vers vous pour vous en informer si elle se trouve sur le même plan d''existence que vous. Si vous êtes sur un autre plan, elle se rend là où vous l''avez liée et y reste jusqu''à la fin du sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau supérieur, la durée augmente: 10 jours au niveau 6, 30 au niveau 7, 180 au niveau 8 et un an et un jour au niveau 9.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/planarbinding-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Eveil',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '8 heures',
        'contact',
        'V, S, M (une agate d''une valeur minimale de 1 000 po, que le sort consomme)',
        'instantanée',
        'Une fois que vous avez passé la durée de l''incantation à tracer des sentiers magiques dans une pierre précieuse, vous touchez un animal ou une plante de taille Très Grande ou inférieure qui doivent être dépourvus de toute valeur d''intelligence ou posséder une Intelligence de 3 ou moins. La cible reçoit alors une Intelligence de 10 et la possibilité de parler un langage de votre connaissance. Si la cible est une plante, elle peut se déplacer à l''aide de ses branches, de ses racines, de ses lianes, de ses vrilles ou autre et gagne des sens similaires à ceux d''un humain. C''est au MD de choisir les statistiques appropriées à la plante éveillée, en lui appliquant par exemple le profil d''un buisson ou d''un arbre éveillé.' || E'\n' || 'La bête ou la plante éveillée est sous votre charme pendant 30 jours ou jusqu''à ce que vous ou l''un de vos compagnons la blessiez. Une fois que l''effet de charme se termine, la créature éveillée décide seule si elle reste amicale envers vous, selon la façon dont vous l''avez traitée lorsqu''elle était charmée.',
        NULL
    ),
    (
        'Légende',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '10 minutes',
        'personnelle',
        'V, S, M (de l''encens d''une valeur minimale de 250 po que le sort consume et quatre bandelettes d''ivoire valant au moins 50 po chaque)',
        'instantanée',
        'Nommez ou décrivez une personne, un lieu ou un objet. Le sort porte à votre connaissance un bref résumé des connaissances essentielles se rapportant à la chose nommée. Ces connaissances peuvent se présenter sous la forme d''histoires actuelles, de contes oubliés ou même d''un savoir secret qui n''a jamais été révélé au grand public. Si la chose que vous nommez n''est pas digne de figurer dans une légende, vous n''obtenez aucune information. Plus vous possédez d''informations sur cette chose, plus celles que vous recevez via le sort sont précises et détaillées.' || E'\n' || 'Les informations obtenues sont exactes, mais susceptibles de se présenter dans un langage figuré. Par exemple, si vous avez une mystérieuse hache en main, le sort peut vous donner les renseignements suivants : « Malheur au malfaisant qui pose la main sur cette hache, car même son manche peut entailler la main des mécréants. Seul un véritable enfant de la pierre, un être qui aime Moradin et en est aimé en retour, pourra éveiller la véritable puissance de cette hache à condition de prononcer le mot sacré _Rudnogg_. »',
        NULL
    ),
    (
        'Modification de mémoire',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '9 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous tentez de remodeler les souvenirs d''autrui. Une créature située dans votre champ de vision doit faire un jet de sauvegarde de Sagesse. Si vous combattez cette créature, elle a l''avantage lors du jet. Si elle échoue, vous la charmez pendant toute la durée du sort. Elle est alors neutralisée et n''a plus conscience de ce qui l''entoure, mais elle vous entend toujours. Le sort se termine si elle subit le moindre dégât ou si elle est la cible d''un autre sort, auquel cas ses souvenirs restent tous intacts.' || E'\n' || 'Tant que le sort persiste, vous pouvez influer sur les souvenirs de la cible liés à un événement qui s''est déroulé dans les 24 heures précédentes et qui n''a pas duré plus de 10 minutes. Vous pouvez éliminer définitivement tout souvenir de cet événement, permettre à la cible de s''en souvenir parfaitement dans les moindres détails, modifier les détails dont elle se souvient ou créer un souvenir décrivant un tout autre événement.' || E'\n' || 'Vous devez parler à votre cible pour décrire comment ses souvenirs sont affectés et, pour que les nouveaux souvenirs s''implantent dans sa mémoire, elle doit être à même de comprendre votre langue. Son esprit se charge de combler les manques dans votre description. Si le sort se termine avant que vous ayez fini de décrire les souvenirs modifiés, la mémoire de la cible ne subit aucune modification. Sinon, elle tient compte des modifications qui lui ont été apportées dès que le sort se termine.' || E'\n' || 'Les souvenirs modifiés ne changent pas forcément l''attitude de la créature, surtout s''ils entrent en contradiction avec ses penchants naturels, son alignement ou ses croyances. Un souvenir modifié illogique sera ignoré: par exemple, si la cible se souvient combien elle a aimé se baigner dans de l''acide, elle prendra cela pour un mauvais rêve. Le MD peut estimer qu''un souvenir est modifié de manière tellement insensée qu''il n''affecte pas la cible de manière significative.' || E'\n' || 'Si la cible bénéficie de _Lever une malédiction_ ou de _Restauration supérieure_, elle retrouve ses véritables souvenirs.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, vous pouvez modifier les souvenirs d''un événement remontant à 7 jours (niveau 6), 30 jours (niveau 7), 1 an (niveau 8) ou issus de n''importe quelle période du passé de la cible (niveau 9).',
        NULL
    ),
    (
        'Restauration supérieure',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        'contact',
        'V, S, M ( poussière de diamant d''une valeur minimale de 100 po, que le sort consume)',
        'instantanée',
        'Vous imprégnez la créature que vous touchez d''énergie positive, afin de la débarrasser d''un effet débilitant. Vous pouvez ainsi réduire le niveau d''épuisement de la cible d''un cran ou mettre un terme à l''un des effets suivants l''affectant.' || E'\n' || '* Un effet qui charme ou pétrifie la cible.' || E'\n' || '* Une malédiction, y compris l''harmonisation entre la cible et un objet magique maudit.' || E'\n' || '* Une réduction sur l''une des valeurs de caractéristique de la cible.' || E'\n' || '* Un effet réduisant le maximum de points de vie de la cible.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/greaterrestoration-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Soin des blessures de groupe',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '18 mètres',
        'V, S',
        'instantanée',
        'Une vague d''énergie curative s''étend depuis un point de votre choix situé à portée. Choisissez un maximum de six créatures présentes dans une sphère de 9 mètres de rayon centrée sur ce point. Chacune d''entre elles récupère un montant de points de vie égal à 3d8 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les morts-vivants ni sur les créatures artificielles.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, les soins augmentent de 1d8 par niveau au-delà du 5e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/masscurewounds-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Tromperie',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        'personnelle',
        'S',
        'concentration, jusqu''à 1 heure',
        'Vous devenez invisible à l''instant même où un double illusoire de votre personne apparaît là où vous vous trouvez. Ce double persiste pendant toute la durée du sort, mais votre invisibilité se termine dès que vous lancez un sort ou attaquez.' || E'\n' || 'Vous pouvez utiliser votre action pour déplacer votre double d''un maximum de deux fois votre vitesse et le faire bouger, parler et se comporter comme bon vous semble.' || E'\n' || 'Vous pouvez voir par les yeux et entendre par les oreilles de votre double comme si vous vous trouviez à son emplacement. À chacun de vos tours, vous pouvez utiliser une action bonus pour passer d''une perception via ses sens à une perception via les vôtres ou inversement. Tant que vous utilisez les sens de votre double, vous êtes sourd et aveugle à ce qui se passe directement autour de vous.',
        NULL
    ),
    (
        'Contagion',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        'contact',
        'V, S',
        '7 jours',
        'Votre simple contact transmet des maladies. Faites une attaque de sort au corps à corps contre une créature à portée. Si vous touchez, vous lui inoculez une maladie de votre choix, à sélectionner parmi celles décrites plus loin.' || E'\n' || 'La cible doit faire un jet de sauvegarde de Constitution à la fin de chacun de ses tours. Une fois qu''elle en a raté trois, la maladie fait effet pendant toute la durée du sort et la créature n''a plus à faire de jet de sauvegarde. Si elle réussit trois jets de sauvegarde, elle guérit de sa maladie et le sort se termine.' || E'\n' || 'Comme le sort déclenche une maladie naturelle chez la cible, tout effet qui guérit une maladie ou améliore ses symptômes s''y applique.' || E'\n' || '**Mal aveuglant**: La créature est en proie à de violentes douleurs cérébrales et ses yeux deviennent d''un blanc laiteux. Elle est désavantagée lors des tests de Sagesse et desjets de sauvegarde de Sagesse et elle est aveugle.' || E'\n' || '**Fièvre répugnante**: Une forte fièvre s''empare de la créature qui est désavantagée lors des tests de Force, des jets de sauvegarde de Force et des jets d''attaque basés sur la Force.' || E'\n' || '**Pourriture**: La chair de la créature se met à pourrir. Elle est désavantagée lors des tests de Charisme et devient vulnérable à tous les dégâts.' || E'\n' || '**Bouille-crâne**: La créature a soudain l''esprit enfiévré. Elle est désavantagée lors des tests d''Intelligence et des jets de sauvegarde d''intelligence. De plus, au combat, elle se comporte comme si elle était sous l''effet d''un sort de _confusion_.' || E'\n' || '**Convulsions** La créature est agitée de tremblements. Elle est désavantagée lors des tests de Dextérité, des jets de sauvegarde de Dextérité et des jets d''attaque basés sur la Dextérité.' || E'\n' || '**Mort poisseuse**: La créature est affligée de saignements incontrôlables. Elle est désavantagée lors des tests de Constitution et des jets de sauvegarde de Constitution. De plus, elle est étourdie jusqu''à la fin de son prochain tour à chaque fois qu''elle subit des dégâts.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/contagion-fleshrot-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Sanctification',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '24 heures',
        'contact',
        'V, S, M ( herbes, huiles et encens d''une valeur minimale de 1 000 po, que le sort consume)',
        'jusqu''à dissipation',
        'Vous touchez un point et imprégnez la zone qui l''entoure de puissance bénie (ou impie). Cette zone possède un rayon maximal de 18 mètres, sachant que le sort échoue si cette zone chevauche une autre zone déjà sous l''effet d''un sort de _sanctification_. La zone affectée est soumise aux effets suivants.' || E'\n' || 'Premièrement, les célestes, les élémentaires, les fées, les fiélons et les morts-vivants ne peuvent entrer dans la zone, ni charmer, terroriser ou posséder les créatures qui s''y trouvent. Une créature charmée, terrorisée ou possédée par l''une de ces créatures ne l''est plus dès qu''elle pénètre dans la zone. Vous pouvez décider qu''un ou plusieurs des types de créatures mentionnés ne seront pas affectés par cet effet.' || E'\n' || 'Deuxièmement, vous pouvez apposer un effet supplémentaire sur la zone. Choisissez l''un des effets de la liste suivante ou optez pour un autre que propose votre MD. Certains effets s''appliquent aux créatures de la zone. Dans ce cas, vous pouvez préciser s''ils affectent toutes les créatures, uniquement celles qui obéissent à une divinité ou à un chef particulier, ou seulement celles d''un type donné, comme les orcs ou les trolls. Quand une créature susceptible d''être affectée pénètre dans la zone d''effet du sort pour la première fois de son tour ou quand elle y commence son tour, elle peut faire un jet de sauvegarde de Charisme. Si elle le réussit, elle ignore l''effet supplémentaire jusqu''à ce qu''elle quitte la zone.' || E'\n' || '**Courage**: Les créatures affectées ne peuvent être terrorisées tant qu''elles se trouvent dans la zone.' || E'\n' || '**Ténèbres**: Les ténèbres s''abattent sur la zone. La lumière normale est incapable d''illuminer les lieux, tout comme les lumières magiques issues d''un sort de niveau inférieur à celui de l''emplacement que vous avez utilisé pour lancer _sanctification_.' || E'\n' || '**Lumière du jour**: Une vive lumière emplit la zone. Les ténèbres magiques issues d''un sort de niveau inférieur à celui de l''emplacement que vous avez utilisé pour lancer sanctification ne peuvent étouffer cette lumière.' || E'\n' || '**Protection contre l''énergie**: Les créatures affectées situées dans la zone gagnent une résistance contre un type de dégâts de votre choix, à l''exception des dégâts contondants, perforants et tranchants.' || E'\n' || '**Vulnérabilité à l''énergie**: Les créatures affectées situées dans la zone sont affligées d''une vulnérabilité à un type de dégâts de votre choix, à l''exception des dégâts contondants, perforants et tranchants.' || E'\n' || '**Repos éternel**: Les cadavres inhumés dans la zone ne peuvent pas se changer en morts-vivants.' || E'\n' || '**Interférence extradimensionnelle**: Les créatures affectées ne peuvent pas se déplacer ni voyager en usant de téléportation, ni de moyens extradimensionnels ou interplanaires.' || E'\n' || '**Terreur**: Les créatures affectées sont terrorisées tant qu''elles se trouvent dans la zone.' || E'\n' || '**Silence**: Aucun son n''émane de l''intérieur de la zone et aucun son ne peut y pénétrer.' || E'\n' || '**Langues**: Les créatures affectées peuvent communiquer avec n''importe quelle créature de la zone, même si elles ne partagent pas le même langage.',
        NULL
    ),
    (
        'Invoquer un élémentaire',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 minute',
        '27 mètres',
        'V, S, M (encens à brûler pour l''air, argile molle pour la terre, soufre et phosphore pour le feu, ou sable et eau pour l''eau)',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez un serviteur élémentaire. Choisissez une zone d''air, de terre, de feu ou d''eau occupant un cube de 3 mètres d''arête situé à portée. Un élémentaire doté d''un indice de dangerosité de 5 ou moins et adapté à la zone que vous avez choisie apparaît dans un espace inoccupé situé dans un rayon de 3 mètres autour d''elle. Par exemple, un élémentaire du feu jaillit d''un brasier tandis qu''un élémentaire de la terre sort du sol. L''élémentaire disparaît dès qu''il tombe à 0 point de vie ou quand le sort se termine.' || E'\n' || 'L''élémentaire se montre amical envers vous et vos compagnons. Lancez l''initiative pour lui, sachant qu''il dispose de ses propres tours de jeu. Il obéit aux ordres verbaux que vous lui donnez (sans que cela vous demande d''utiliser une action). En l''absence d''ordre, il se défend contre les créatures hostiles, mais n''entreprend pas d''autre action.' || E'\n' || 'Si votre concentration se brise, l''élémentaire ne disparaît pas, mais il échappe à votre contrôle et devient hostile envers vous et vos compagnons. Il peut aller jusqu''à vous attaquer. Vous ne pouvez pas renvoyer un élémentaire qui est hors de contrôle, il disparaît simplement 1 heure après que vous l''avez invoqué.' || E'\n' || 'C''est le MD qui dispose des statistiques de l''élémentaire.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, l''indice de dangerosité de l''élémentaire augmente de 1 par niveau au-delà du 5e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/conjureelemental-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Réincarnation',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 heure',
        'contact',
        'V, S, M (huiles et onguents rares d''une valeur minimale de 1 000 po, que le sort consume)',
        'instantanée',
        'Vous touchez un humanoïde mort ou un morceau du cadavre d''une telle créature. Si la créature est morte depuis 10 jours au maximum, le sort lui fabrique un nouveau corps adulte et y appelle son âme. Le sort échoue si l''âme n''est pas libre de gagner ce corps ou si elle ne le désire pas.' || E'\n' || 'La magie façonne un nouveau corps pour accueillir l''âme, ce qui risque de modifier la race de la créature. Le MD lance 1d100 et consulte la table suivante pour déterminer quel sera le corps de la créature ramenée à la vie ou il en choisit un.' || E'\n' || '**d100 -> Race**' || E'\n' || '01-04 -> Sangdragon' || E'\n' || '05-13 -> Nain des collines' || E'\n' || '14-21 -> Nain des montagnes' || E'\n' || '22-25 -> Elfe noir' || E'\n' || '26-34 -> Haut elfe' || E'\n' || '35-42 -> Elfe sylvestre' || E'\n' || '43-46 -> Gnome des forêts' || E'\n' || '47-52 -> Gnome des roches' || E'\n' || '53-56 -> Demi-elfe' || E'\n' || '57-60 -> Demi-orc' || E'\n' || '61-68 -> Halfelin pied-léger' || E'\n' || '69-76 -> Halfelin robuste' || E'\n' || '77-96 -> Humain' || E'\n' || '97-100 -> Tieffelin' || E'\n' || 'La créature réincarnée se souvient de son ancienne vie et de ses expériences passées. Elle garde les capacités dont elle disposait sous sa forme originelle, mais échange sa race précédente contre la nouvelle et modifie ses traits raciaux en fonction.',
        NULL
    ),
    (
        'Coquille antivie',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle (3 mètres de rayon)',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Une barrière scintillante se déploie depuis votre personne jusqu''à englober une zone d''un rayon de 3 mètres. Elle se déplace avec vous, reste centrée sur vous et repousse les créatures autres que les morts-vivants et les créatures artificielles. Cette barrière persiste pendant toute la durée du sort.' || E'\n' || 'La barrière empêche les créatures affectées de la franchir ou de passer un membre au travers. Une créature affectée peut lancer des sorts ou porter des attaques à distance ou via une arme à allonge, tout cela franchissant la barrière.' || E'\n' || 'Si vous vous déplacez de telle manière qu''une créature affectée est contrainte de traverser la barrière, le sort se termine.',
        NULL
    ),
    (
        'Animation des objets',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Les objets prennent vie sur votre ordre. Choisissez jusqu''à dix objets non magiques à portée que personne ne porte ni ne transporte. Les cibles de taille Moyenne comptent comme deux objets, celles de taille Grande comme quatre et celles de taille Très Grande comme huit. Vous ne pouvez pas animer d''objet de taille supérieure. Chaque cible s''anime et devient une créature placée sous votre contrôle jusqu''à la fin du sort ou jusqu''à tomber à O point de vie.' || E'\n' || 'Par une action bonus, vous pouvez donner un ordre mental à toute créature créée via ce sort qui se trouve au maximum à 150 mètres de vous (si vous en contrôlez plusieurs, vous pouvez donner un ordre à l''une d''elles, certaines d''entre elles ou toutes à la fois, à condition de donner le même ordre à toutes). À vous de décider quelle action la créature va entreprendre et à quel endroit elle se déplacera au cours du tour suivant, mais vous pouvez aussi lui donner un ordre plus générique, comme de garder une salle ou un couloir. En l''absence d''ordre, la créature se contente de se défendre contre les créatures hostiles. Une fois qu''elle a reçu un ordre, elle continue à le suivre jusqu''à ce qu''elle ait accompli sa tâche.' || E'\n' || '**STATISTIQUES DES OBJETS ANIMÉS**' || E'\n' || '**Taille : PV - CA - Attaque - For - Dex**'  || E'\n' || 'Très petite : 20 - 18 - +8 pour toucher, 1d4+4 dégâts - 4 - 18' || E'\n' || 'Petite : 25 - 16 - +6 pour toucher, 1d8+2 dégâts - 6 - 14' || E'\n' || 'Moyenne : 40 - 13 - +5 pour toucher, 2d6+1 dégâts - 10 - 12' || E'\n' || 'Grande : 50 - 10 - +5 pour toucher, 2d10+2 dégâts - 14 - 10' || E'\n' || 'Très grande : 80 - 10 - +8 pour toucher, 2d12+4 dégâts - 18 - 6',
        NULL
    ),
    (
        'Apparence trompeuse',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        '9 mètres',
        'V, S',
        '8 heures',
        'Ce sort vous permet de modifier l''apparence d''autant de créatures que vous voulez, à condition qu''elles se trouvent à portée et dans votre champ de vision. Vous donnez à chacune d''entre elles une nouvelle apparence illusoire. Une cible non consentante peut faire un jet de sauvegarde de Charisme. Si elle le réussit, le sort ne l''affecte pas.' || E'\n' || 'Ce sort change l''apparence physique, mais aussi les habits, les armures, les armes et le reste de l''équipement. Vous pouvez faire croire que chaque créature affectée est plus petite ou plus grande de 30 centimètres maximum qu''en réalité, lui donner l''air grosse, maigre ou entre les deux. Vous ne pouvez pas changer le type de son corps, vous devez choisir une forme possédant la même conformation qu''elle au niveau des membres. En dehors de cela, les détails de l''illusion sont laissés à votre imagination. Le sort persiste pendant toute sa durée ou jusqu''à ce que vous utilisiez une action pour le révoquer.' || E'\n' || 'Les changements apportés par le sort ne résistent pas à un examen physique. Par exemple, si vous l''utilisez pour ajouter un chapeau à la tenue de la cible, les objets passent au travers et toute personne qui essaie de le toucher ne sentira que de l''air ou des cheveux et un crâne. Si vous utilisez le sort pour la faire paraître plus mince qu''en réalité, la main de quelqu''un qui tente de la toucher se heurtera à son corps alors que, visuellement, elle semble encore dans le vide.' || E'\n' || 'Une créature peut utiliser son action pour examiner une cible et faire un test d''lntelligence (Investigation) contre le DD du jet de sauvegarde du sort. Si elle réussit, elle comprend que la cible est déguisée.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/seeming-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Cercle de téléportation',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 minute',
        '3 mètres',
        'V, M (des craies et des encres rares contenant des extraits de pierres précieuses pour une valeur de 50 po, que le sort consume)',
        '1 round',
        'Lorsque vous lancez ce sort, vous tracez un cercle de 3 mètres de diamètre au sol et y inscrivez des symboles qui relient l''endroit où vous vous trouvez actuellement à un cercle de téléportation permanent de votre choix dont vous connaissez la séquence de symboles et qui se trouve sur le même plan d''existence que vous. Un portail scintillant s''ouvre dans le cercle que vous avez tracé et reste ouvert jusqu''à la fin de votre prochain tour. Toute créature qui franchit ce portail apparaît instantanément dans un rayon de 1,50 mètre autour du cercle de destination ou dans l''espace inoccupé le plus proche si le reste est occupé.' || E'\n' || 'Nombre de temples majeurs, de guildes et d''autres lieux d''importance possèdent des cercles de téléportation permanents tracés quelque part dans leur enceinte. Chacun de ces cercles utilise une séquence de symboles uniques : une série de runes·magiques disposées selon un motif particulier. Lorsque vous apprenez à lancer ce sort, vous apprenez la séquence associée à deux destinations situées sur le plan matériel et déterminées par le MD. Vous pouvez apprendre d''autres séquences de symboles au cours de vos aventures. Pour en mémoriser une, vous devez l''étudier pendant 1 minute.' || E'\n' || 'Vous pouvez créer un cercle de téléportation permanent en lançant ce sort au même endroit tous les jours pendant un an. Vous n''avez pas besoin d''utiliser le cercle pour vous téléporter quand vous lancez ce sort pour cela.',
        NULL
    ),
    (
        'Cône de froid',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (cône de 18 mètres)',
        'V, S, M (un petit cône de cristal ou de verre)',
        'instantanée',
        'Une bouffée d''air froid jaillit de vos mains. Toutes les créatures présentes dans un cône de 18 mètres doivent faire un jet de sauvegarde de Constitution. Celles qui le ratent subissent 8d8 dégâts de froid, les autres la moitié seulement.' || E'\n' || 'Une créature qui succombe suite à ce sort se transforme en statue de glacejusqu''à ce qu''elle fonde.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 5e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/coneofcold-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Création',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 minute',
        '9 mètres',
        'V, S, M (un petit bout de matière de même type que l''objet que vous voulez créer)',
        'spéciale',
        'Vous tirez des bribes de matière ombreuse de l''Obscur pour créer à portée des objets inertes en matière végétale: du tissu, de la corde, du bois ou des objets similaires. Ce sort permet aussi de créer des objets minéraux comme de la pierre, du cristal ou du métal. L''objet créé ne doit pas être plus grand qu''un cube de 1,50 mètre d''arête et doit impérativement être d''une forme et d''un matériau que vous avez déjà vus.' || E'\n' || 'La durée du sort dépend du matériau choisi pour façonner l''objet. S''il est fait de plusieurs matières, c''est la durée la plus courte qui s''applique.' || E'\n' || '** Matériau - Durée **' || E'\n' || '* Matière végétale -> 1 jour' || E'\n' || '* Pierre ou cristal -> 12 heures' || E'\n' || '* Métaux précieux -> 1 heure' || E'\n' || '* Gemmes -> 10 minutes' || E'\n' || '* Adamantium ou mithral -> 1 minute' || E'\n' || 'Si vous utilisez les matériaux créés via ce sort comme composantes matérielles pour un autre sort, ce dernier échoue.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, l''arête du cube augmente de 1,50 mètre par niveau au-delà du 5e.',
        NULL
    ),
    (
        'Dominer un humanoïde',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous tentez d''envoûter un humanoïde situé à portée et dans votre champ de vision. Il doit réussir un jet de sauvegarde de Sagesse, sans quoi vous le charmez pendant toute la durée du sort. Il est avantagé lors du jet de sauvegarde si vous ou des créatures amicales envers vous êtes en train de le combattre.' || E'\n' || 'Tant que l''humanoïde est charmé, vous entretenez un lien télépathique avec lui qui persiste tant que vous vous trouvez sur le même plan d''existence. Vous pouvez utiliser ce lien télépathique pour donner des ordres à cette créature tant que vous êtes conscient (ce qui ne vous demande pas d''action). Elle fait de son mieux pour vous obéir. Vous pouvez lui donner un ordre simple et générique, comme « attaque cette créature », « cours jusque là-bas » ou « va chercher cet objet ». Si elle ne reçoit pas de nouvelles instructions de votre part une fois l''ordre exécuté, elle se contente de se défendre et de se préserver au mieux.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dominateperson-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Fléau d''insectes',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '90 mètres',
        'V, S, M (un peu de sucre en poudre, quelques graines de céréales et une tache de graisse)',
        'concentration, jusqu''à 10 minutes',
        'Un essaim de sauterelles grouillantes remplit une sphère de 6 mètres de rayon centrée sur un point de votre choix situé à portée. La sphère s''étend en contournant les angles et persiste pendant toute la durée du sort. La visibilité est réduite dans la zone affectée. L''intérieur de la sphère devient un terrain difficile.' || E'\n' || 'Quand la sphère d''insectes apparaît, chaque créature prise à l''intérieur doit faire un jet de sauvegarde de Constitution. Une créature subit 4d10 dégâts perforants si elle rate sonjet, la moitié seulement si elle le réussit. Une créature doit faire le même jet quand elle entre dans la sphère pour la première fois de son tour ou quand elle y termine son tour.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, les dégâts augmentent de 1d1O par niveau au-delà du 5e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/insect_plague_spell_conjuration_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Immobiliser un monstre',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '27 mètres',
        'V, S, M (un petit morceau de fer bien droit)',
        'concentration, jusqu''à 1 minute',
        'Choisissez une créature située à portée dans votre champ de vision. EUe doit réussir un jet de sauvegarde de Sagesse, sans quoi elle est paralysée pour toute la durée du sort. Ce sort est sans effet sur les morts-vivants. À la fin de chacun de ses tours, la cible a droit à un nouveau jet de sauvegarde de Sagesse. Si elle le réussit, le sort se termine.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 5e_ Les créatures visées doivent se trouver à 9 mètres ou moins les unes des autres au moment où vous lancez le sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/holdmonster-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Mur de pierre',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (un petit bloc de granite)',
        'concentration, jusqu''à 10 minutes',
        'Vous créez un mur de pierre non magique qui se matérialise en un point de votre choix à portée. Il fait 15 centimètres d''épaisseur et se compose de dix panneaux de 3 mètres sur 3. Chaque panneau doit être contigu à un autre. Sinon, vous pouvez opter pour des panneaux de 3 mètres sur 6 de seulement 7,50 centimètres d''épaisseur.' || E'\n' || 'Si le mur passe par l''emplacement d''une créature lorsqu''il apparaît, il la repousse d''un côté ou de l''autre (à vous de choisir). Si une créature est placée de telle manière qu''elle devrait se retrouver entourée de toutes parts par le mur (ou par le mur et une autre surface solide), elle doit faire un jet de sauvegarde de Dextérité. Si elle le réussit, elle peut utiliser sa réaction pour se déplacer à sa vitesse au maximum afin de ne plus être encerclée par le mur.' || E'\n' || 'Le mur peut prendre la forme que vous désirez, mais il ne peut pas occuper le même emplacement qu''une créature ou un objet. Il n''est pas forcément vertical et n''a pas besoin de reposer sur des fondations solides. En revanche, il doit impérativement fusionner avec de la pierre existante lui servant de soutien solide. Vous pouvez donc utiliser ce sort pour jeter un pont au-dessus d''un fossé ou créer une rampe.' || E'\n' || 'Si vous créez une longueur de plus de 6 mètres, vous devez réduire de moitié la taille de chaque panneau pour créer des supports. Vous pouvez façonner la silhouette générale du mur pour le doter de créneaux, de remparts et autres.' || E'\n' || 'Le mur est un objet de pierre que l''on peut endommager et on peut donc y ouvrir des brèches. Chaque panneau a une CA de 15 et 30 points de vie par section de 2,5 centimètres d''épaisseur. Si un panneau tombe à O point de vie, il est détruit, ce qui peut entraîner l''effondrement des panneaux adjacents, au choix du MD.' || E'\n' || 'Si vous restez concentré sur le sort pendant toute sa durée, le mur devient une structure permanente et ne peut plus être dissipé, sinon il disparaît à la fin du sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wallofstone-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Nuage mortel',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Vous créez une sphère de 6 mètres de rayon faite d''un brouillard vert jaunâtre empoisonné. Il est centré sur un point de votre choix situé à portée. Le brouillard s''étend en contournant les coins au besoin. Il persiste pendant toute la durée du sort ou jusqu''à ce qu''un vent fort le disperse et mette un terme au sort. La visibilité est lourdement obstruée dans sa zone d''effet.' || E'\n' || 'Quand une créature entre dans la zone du sort pour la première fois de son tour ou qu''elle y démarre son tour, elle doit faire un jet de sauvegarde de Constitution. Elle subit 5d8 dégâts de poison si elle rate son jet et seulement la moitié si elle le réussit. Le brouillard affecte même les créatures qui retiennent leur souffle ou qui n''ont pas besoin de respirer.' || E'\n' || 'Le brouillard s''éloigne de vous sur une distance de 3 mètres au début de chacun de vos tours, rampant à la surface du sol. Comme ses vapeurs sont plus lourdes que l''air, il s''enfonce dans les replis du terrain et s''infiltre même dans les ouvertures.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 5e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/cloudkill_spell_conjuration_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Télékinésie',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Vous devenez capable de déplacer ou de manipuler des créatures ou des objets par la pensée. Lorsque vous lancez ce sort, puis en tant qu''action à chaque round pendant toute la durée du sort, vous pouvez exercer votre force de volonté sur une créature ou un objet situés à portée et dans votre champ de vision, ce qui provoque l''effet approprié indiqué plus bas. Vous pouvez affecter la même cible, round après round, ou en choisir une nouvelle quand vous le désirez. Si vous changez de cible, la précédente n''est plus affectée.' || E'\n' || '**Créatures**: Vous pouvez essayer de déplacer une créature de taille Très Grande ou inférieure. Faites un test de caractéristique avec votre caractéristique d''incantation, opposé au test de Force de la cible. Si vous l''emportez, vous déplacez la créature d''un maximum de 9 mètres dans la direction de votre choix, y compris en hauteur, mais pas hors de portée du sort. Jusqu''à la fin de votre prochain tour, la créature est entravée dans votre étreinte télékinétique. Une créature soulevée dans les airs reste suspendue dans le vide.' || E'\n' || 'Lors des rounds suivants, vous pouvez utiliser votre action pour maintenir votre prise télékinétique sur la cible en répétant les tests opposés.' || E'\n' || '**Objets**: Vous pouvez essayer de déplacer un objet pesant au maximum 500 kilos. Si cet objet n''est ni porté ni transporté, vous le déplacez automatiquement d''un maximum de 9 mètres dans la direction de votre choix, mais pas hors de portée du sort.' || E'\n' || 'Si l''objet est porté ou transporté par une créature, faites un test de caractéristique avec votre caractéristique d''incantation, opposé au test de Force de cette créature. Si vous l''emportez, vous éloignez l''objet de cette créature sur un maximum de 9 mètres dans la direction de votre choix, mais pas hors de portée du sort.' || E'\n' || 'Vous exercez un contrôle précis sur les objets pris dans votre étreinte télékinétique, vous pouvez donc manipuler un outil basique, ouvrir une porte ou un récipient, déposer un objet dans un récipient ou en retirer un, ou encore verser le contenu d''une fiole.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/telekinesis-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Lien télépathique de Rary',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 action',
        '9 mètres',
        'V, S, M (bouts de coquille d''œuf issus de deux espèces de créatures différentes)',
        '1 heure',
        'Vous forgez un lien télépathique entre maximum huit créatures consentantes situées à portée. Elles sont alors psychiquement liées les unes aux autres pendant la durée du sort. Ce sort n''affecte pas les créatures dotées d''une Intelligence de 2 ou moins.' || E'\n' || 'Jusqu''à la fin du sort,les cibles peuvent communiquer entre elles par télépathie via le lien créé, qu''elles partagent un même langage ou non. Cette communication fonctionne quelle que soit la distance séparant les créatures, mais ne s''étend pas aux autres plans d''existence.',
        NULL
    ),
    (
        'Main de Bigby',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (une coquille d''œuf et un gant en peau de serpent)',
        'concentration, jusqu''à 1 minute',
        'Vous créez une main de force luisante et translucide, de taille Grande, dans un espace inoccupé situé à portée et dans votre champ de vision. La main existe pendant toute la durée du sort, se déplace sur votre ordre et imite les mouvements de votre propre main.' || E'\n' || 'La main est un objet doté d''une CA 20 et d''un nombre de points de vie égal à votre maximum de points de vie. Si elJe tombe à 0 point de vie, le sort se dissipe. La main possède une Force de 26 (+8) et une Dextérité de 10 (+0). Elle n''occupe pas la case où elle se trouve.' || E'\n' || 'Lorsque vous lancez le sort, puis via une action bonus lors de vos tours ultérieurs, vous pouvez déplacer la main sur une distance maximale de 18 mètres et lui faire appliquer l''un des effets suivants.' || E'\n' || '**Poing serré**: La main frappe une créature ou un objet situés dans un rayon de 1,50 mètre d''elle. Faites une attaque de sort de contact pour la main en utilisant vos propres statistiques. Si elle touche, la cible subit 4d8 dégâts de force.' || E'\n' || '**Main percutante**: La main tente de repousser une créature située dans un rayon de 1,50 mètre dans la direction de votre choix. Faites un test avec la Force de la main opposé au test de Force (Athlétisme) de la cible. Si cette dernière est de taille Moyenne ou inférieure, vous êtes avantagé lors du test. Si vous l''emportez,la main repousse la cible sur 1,50 mètre plus un nombre de mètres égal à une fois et demie votre modificateur de caractéristique d''incantation. La main se déplace avec la cible de manière à rester dans un rayon de 1,50 mètre autour d''elle.' || E'\n' || '**Main agrippeuse**: La main tente d''empoigner une créature de taille Très Grande ou inférieure qui se trouve dans un rayon de 1,50 mètre. Utilisez la valeur de Force de la main pour résoudre le test d''empoignade. Si la cible est de taille Moyenne ou inférieure, vous êtes avantagé lors du test. Tant que la main agrippe la cible, vous pouvez utiliser une action bonus pour que la main la broie. Dans ce cas, la cible subit un montant de dégâts contondants égal à 2d6 + votre modificateur de caractéristique d''incantation.' || E'\n' || '**Main interposée**: La main s''interpose entre vous et une créature de votre choix jusqu''à ce que vous lui donniez un autre ordre. Elle se déplace de manière à toujours rester entre vous et la cible désignée et vous offre un abri partiel contre elle. La cible ne peut pas franchir la zone occupée par la main si sa valeur de Force est inférieure ou égale à celle de la main. Si elle est supérieure, elle peut se déplacer dans votre direction en traversant la zone de la main, qui est considérée comme un terrain difficile pour la cible.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, les dégâts de l''option poing serré augmentent de 2d8 et ceux de la main agrippeuse de 2d6 par niveau au-delà du 5e.',
        NULL
    ),
    (
        'Mur de force',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (une pincée de poudre de gemme translucide)',
        'concentration, jusqu''à 10 minutes',
        'Un mur de force invisible se matérialise soudain en un point de votre choix situé à portée. Il s''oriente comme bon vous semble, comme une barrière horizontale, verticale ou inclinée. Il peut flot ter librement ou reposer sur une surface solide. Vous pouvez lui donner une forme de dôme hémisphérique ou de sphère d''un rayon maximal de 3 mètres ou en fia re une surface plane composée de dix panneaux de 3 mètres sur 3. Chaque panneau doit être contigu à un autre. Quelle que soit sa forme, le mur fait 0,5 centimètre d''épaisseur et persiste pendant toute la durée du sort. Si le mur passe par l''emplacement d''une créature lorsqu''il apparaît, il la repousse d''un côté ou de l''autre (à vous de choisir).' || E'\n' || 'Aucun élément ne peut franchir physiquement le mur, qui est immunisé contre tous les dégâts et résiste à toute _dissipation de la magie_. En revanche, on peut le détruire instantanément avec une _désintégration_. Le mur s''étend également sur le plan éthéré, ce qui empêche de le franchir sous forme éthérée.',
        NULL
    ),
    (
        'Passe-muraille',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (une pincée de graines de sésame)',
        '1 heure',
        'Un passage apparaît en un point de votre choix situé à portée et dans votre champ de vision sur une surface de bois, de plâtre ou de pierre (comme un mur, un sol ou un plafond). Il persiste pendant toute la durée du sort. À vous de décider des dimensions de l''ouverture qui peut faire, au maximum, 1,50 mètre de large pour 2,50 mètres de haut et 6 mètres de profondeur. L''apparition du passage ne crée aucune faiblesse dans la structure qui l''entoure.' || E'\n' || 'Quand l''ouverture disparaît, les créatures et les objets qui s''y trouvaient encore sont expulsés en toute sécurité dans l''emplacement inoccupé le plus proche de la surface sur laquelle vous avez lancé le sort.',
        NULL
    ),
    (
        'Cercle de pouvoir',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle (9 mètres de rayon)',
        'V',
        'concentration, jusqu''à 10 minutes',
        'Une énergie divine émane de vous, qui déforme les énergies magiques pour les diffuser dans un rayon de 9 mètres autour de votre personne. La sphère est centrée sur vous et se déplace avec vous jusqu''à la fin du sort. Pendant toute la durée du sort, toutes les créatures amicales de la zone (vous y compris) ont l''avantage lors de leurs jets de sauvegarde contre les sorts et autres effets magiques. De plus, quand une créature affectée réussit son jet de sauvegarde contre un sort ou un effet magique qui inflige des dégâts réduits de moitié en cas de jet de sauvegarde réussi, elle ne subit absolument aucun dégât.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blobe_of_invulnerability_spell_abjuration_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Coercition mystique',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V',
        '30 jours',
        'Vous imposez une coercition magique sur une créature située à portée dans votre champ de vision, l''obligeant à vous accorder un service ou l''empêchant de commettre une action ou une suite d''actions, comme bon vous semble. Si la créature comprend votre langue, elle doit réussir un jet de sauvegarde de Sagesse, sans quoi vous la charmez pendant toute la durée du sort. Pendant toute cette période, elle subit 5d10 dégâts psychique chaque fois qu''elle agit de manière directement opposée à vos instructions, mais jamais plus d''une fois par jour. Si la créature ne vous comprend pas, ce sort n''a aucun effet sur elle.' || E'\n' || 'Vous pouvez donner n''importe quel ordre de votre choix, en dehors de ceux qui mènent directement à la mort. Le sort se termine si jamais vous donnez un ordre suicidaire. Vous pouvez mettre prématurément fin au sort en dépensant une action pour le dissiper. On peut aussi terminer le sort avec lever une malédiction, restauration supérieure ou souhait. **À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 7 ou 8, il dure 1 an. Avec un emplacement de sort de niveau 9, il persiste jusqu''à ce que quelqu''un le dissipe avec l''un des sorts mentionnés précédemment.',
        NULL
    ),
    (
        'Dissipation du mal et du bien',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle',
        'V, S, M (eau bénite ou poudre d''argent et de fer)',
        'concentration, jusqu''à 1 minute',
        'Une énergie scintillante vous entoure et vous protège contre les fées, les morts-vivants et les créatures originaires d''au-delà du plan matériel. Pendant toute la durée du sort, les célestes, les élémentaires, les fées, les fiélons et les morts-vivants sont désavantagés lors de leurs jets d''attaque contre vous.' || E'\n' || 'Vous pouvez terminer le sort plus tôt en utilisant l''une des fonctions spéciales suivantes.' || E'\n' || '**Annulation d''enchantement**: Vous utilisez votre action pour toucher une créature à votre portée qui se trouve charmée, terrorisée ou possédée par un céleste, un élémentaire, une fée, un fiélon ou un mort-vivant. Cette créature n''est alors plus charmée, terrorisée ou possédée par ces créatures.' || E'\n' || '**Renvoi**: Vous utilisez votre action pour faire une attaque de sort au corps à corps contre un céleste, un élémentaire, une fée, un fiélon ou un mort-vivant situé à une distance inférieure ou égale à votre allonge. Si vous touchez la créature, vous tentez de la renvoyer sur son plan natal. Elle doit réussir un jet de sauvegarde de Charisme ou retourner sur son plan natal (si elle ne s''y trouve pas déjà). Si un mort-vivant ne se trouve pas sur son plan natal, il est renvoyé dans l''Obscur tandis qu''une fée sera expulsée dans la Féerie sauvage.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dispelevilandgood-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Frappe du bannissement',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration, jusqu''à 1 minute',
        'La prochaine attaque armée qui vous permet de toucher une créature avant la fin de ce sort voit votre arme crépiter d''énergie et inflige 5d10 dégâts de force à votre cible. De plus, si cette attaque réduit la cible à 50 pv ou moins, elle la bannit. Si la cible est originaire d''un plan d''existence différent de celui sur lequel vous vous trouvez, elle disparaît, renvoyée dans son plan d''origine. Si elle est originaire du plan sur lequel vous vous trouvez, elle disparaît dans un demi-plan inoffensif. Elle est neutralisée tant qu''elle s''y trouve, c''est-à-dire jusqu''à la fin du sort. À ce moment, elle réapparaît à l''emplacement qu''elle a quitté ou dans l''emplacement le plus proche si le précédent est occupé.',
        NULL
    ),
    (
        'Relever les morts',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 heure',
        'contact',
        'V, S, M (un diamant d''une valeur minimale de 500 po, que le sort consume)',
        'instantanée',
        'Vous touchez une créature décédée et la ramenez à la vie, à condition que son trépas ne remonte pas à plus de 10 jours. Si l''âme de la créature est désireuse de rejoindre son corps et libre de le faire, le défunt revient à la vie avec 1 point de vie.' || E'\n' || 'Ce sort neutralise également les poisons et soigne les maladies non magiques qui affectaient la créature à sa mort. En revanche, il ne la débarrasse pas des maladies magiques, des malédictions et des effets similaires. Si on ne supprime pas ces effets sur le cadavre avant de lancer le sort, ils affectent de nouveau la créature ressuscitée. Ce sort est incapable de ramener un mort-vivant à la vie.' || E'\n' || 'Ce sort referme les plaies mortelles, mais ne restaure pas les parties manquantes du corps. Si la créature est privée d''un organe ou d''un morceau indispensable à sa survie, comme sa tête, le sort échoue automatiquement.' || E'\n' || 'Le retour d''entre les morts est une rude épreuve qui se traduit par un malus de -4 aux jets d''attaque et de sauvegarde ainsi qu''aux tests de caractéristique. Chaque fois que la cible termine un long repos, ce malus se réduit de 1 jusqu''à disparaître.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/speakwithdead-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Vague destructrice',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (9 mètres)',
        'V',
        'instantanée',
        'Vous frappez le sol et créez une onde d''énergie divine qui se répand alentour. Toutes les créatures de votre choix situées dans un rayon de 9 mètres autour de vous doivent faire un jet de sauvegarde de Constitution. Celles qui échouent subissent 5d6 dégâts de tonnerre et 5d6 dégâts radiants ou nécrotiques (à vous de choisir). De plus, elles sont projetées à terre. Celles qui réussissent subissent seulement la moitié des dégâts et ne tombent pas à terre.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/destructive-wave-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Carquois magique',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action bonus',
        'contact',
        'V, S, M (un carquois contenant au moins une munition)',
        'concentration, jusqu''à 1 minute',
        'Vous transmutez votre carquois de manière à ce qu''il produise une réserve infinie de munitions non magiques qui semblent bondir dans votre main dès que vous la tendez pour les saisir.' || E'\n' || 'Pendant toute la durée du sort, à chacun de vos tours, vous pouvez utiliser une action bonus pour effectuer deux attaques avec une arme utilisant les munitions venant du carquois. Chaque fois que vous portez une telle attaque à distance, le carquois remplace magiquement la munition dépensée par une autre, identique, non magique. Les munitions que produit le carquois se désintègrent quand le sort se termine. Si le carquois ne se trouve plus en votre possession, le sort se termine.',
        NULL
    ),
    (
        'Invoquer une volée de projectiles',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '15 mètres',
        'V, S, M (une munition ou une arme de jet)',
        'instantanée',
        'Vous lancez une arme de jet non magique ou un projectile non magique, et choisissez un point à portée. Des centaines de copies du projectile s''abattent sur la zone avant de disparaître. Chaque créature située dans un cylindre de 12 mètres de rayon, 6 mètres de hauteur et centré sur le point choisi doit réussir un jet de sauvegarde de Dextérité. Celles qui échouent subissent 8d8 dégâts, les autres la moitié seulement. Le type de dégâts est identique à celui du projectile utilisé comme composante.',
        NULL
    ),
    (
        'Contacter un autre plan',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 minute',
        'personnelle',
        'V',
        '1 minute',
        'Vous contactez mentalement un demi-dieu, l''esprit d''un sage décédé il y a longtemps, ou une autre entité mystérieuse issue d''un autre plan. Le contact avec cette intelligence extraplanaire met votre esprit à rude épreuve et risque même de le briser. Quand vous lancez ce sort, vous devez faire un jet de sauvegarde d''Intelligence DD 15. En cas d''échec, vous recevez 6d6 dégâts psychiques et vous devenez fou jusqu''à ce que vous ayez bénéficié d''un long repos. Tant que vous êtes fou, vous ne pouvez pas entreprendre la moindre action, vous ne comprenez pas ce que disent les au tres créatures, vous êtes incapable de lire et vous ne bredouillez que des paroles insensées. Une tierce personne peut mettre un terme à cet effet en vous lançant le sort de _restauration supérieure_.' || E'\n' || 'Si vous réussissez votre jet de sauvegarde, vous pouvez poser jusqu''à cinq questions à l''entité. Vous devez les poser avant la fin du sort. C''est le MD qui répond à chacune d''entre elles avec un mot, comme «oui», «non», «peut-être», «jamais», «hors sujet» ou «obscur» (si l''entité ignore la réponse à votre question). Si une réponse limitée à un seul mot risque de se révéler trompeuse, le MD peut la remplacer par une courte phrase.',
        NULL
    ),
    (
        'Rêve',
        5,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 minute',
        'spéciale',
        ' V, S, M (une poignée de sable, une goutte d''encre et une plume d''écrivain prélevée sur un oiseau endormi)',
        '8 heures',
        'Ce sort façonne les rêves d''une créature. Choisissez comme cible une créature de votre connaissance. Elle doit se trouver sur le même plan d''existence que vous. Il est impossible de contacter une créature qui ne dort pas, comme un elfe, via ce sort. Vous entrez dans un état de transe et servez de messager, à moins que vous ne confiiez ce rôle à une autre créature consentante. Pendant la transe, le messager est conscient de son environnement, mais il ne peut pas entreprendre d''action ni se déplacer.' || E'\n' || 'Si la cible est endormie, le messager apparaît dans son rêve et peut discuter avec elle tant qu''elle est endormie, pendant toute la durée du sort. Le messager peut aussi modeler l''environnement onirique, en créant des objets, un paysage et d''autres images. Il peut sortir de sa transe quand bon lui semble, mettant alors un terme prématuré au sort. La cible se souvient parfaitement de son rêve quand elle se réveille. Si la cible est éveillée quand vous lancez le sort, le messager le sait et peut sortir de sa transe (et mettre un terme au sort) ou attendre qu''elle s''endorme, car il apparaîtra dans ses rêves à ce moment. Vous pouvez affubler le messager d''une apparence que la cible trouvera monstrueuse et terrifiante. Dans ce cas, le message qu''il transmet ne peut excéder dix mots et la cible est obligée de faire unjet de sauvegarde de Sagesse. Si elle échoue, les échos de cette monstruosité fantasmagorique génèrent un cauchemar qui dure pendant tout le sommeil de la cible et l''empêche de bénéficier des avantages de sa période de repos. De plus, quand elle se réveille, elle subit 3d6 dégâts psychiques.' || E'\n' || 'Si vous êtes en possession d''un élément corporel de la cible, comme une mèche de cheveux, des rognures d''ongles ou autre, elle est désavantagée lors de son jet de sauvegarde.',
        NULL
    );