INSERT INTO sort (nom_sort,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Communication avec les morts',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        '3 mètres',
        'V, S, M (encens incandescent)',
        '10 minutes',
        'Vous donnez un semblant de vie et d''intelligence à un cadavre de votre choix situé à portée. Il est alors en mesure de répondre à vos questions. Le cadavre doit encore disposer d''une bouche et ne doit pas être devenu mort-vivant. Le sort échoue si le cadavre choisi a déjà été la cible de ce sort au cours des dix jours précédents.' || E'\n' || 'Vous pouvez poser jusqu''à cinq questions avant la fin de la durée du sort. Les connaissances du cadavre se limitent à ce qu''il savait de son vivant, y compris au niveau des langues qu''il parle. Les réponses sont souvent brèves, cryptiques ou répétitives et le cadavre n''est absolument pas obligé de vous donner une réponse sincère si vous lui êtes hostile ou s''il vous reconnaît comme étant un ennemi. Ce sort ne ramène pas l''âme de la cible dans son corps,juste l''esprit qui l''animait; le cadavre ne peut donc pas apprendre de nouvelles informations, ne comprend rien de ce qui s''est passé après sa mort et est incapable de faire des spéculations sur l''avenir.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/speakwithdead-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Communication avec les plantes',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'personnelle (9 mètres de rayon)',
        'V, S',
        '10 minutes',
        'Vous imprégnez la végétation située dans un rayon de 9 mètres autour de vous d''une conscience et d''une mobilité limitées, ce qui permet aux plantes de communiquer avec vous et de suivre des ordres simples. Vous pouvez interroger les végétaux sur les événements qui se sont déroulés la veille dans la zone du sort et ainsi obtenir des informations sur les créatures qui sont passées, sur les conditions météorologiques et autres.' || E'\n' || 'Vous pouvez également transformer un terrain rendu difficile à cause de la végétation (comme des buissons ou d''épais taillis) en terrain ordinaire pendant toute la durée du sort. Ou vous pouvez transformer un terrain ordinaire où poussent des plantes en terrain difficile pendant toute la durée du sort, par exemple de manière à ce que des plantes grimpantes et des branches gênent vos poursuivants.' || E'\n' || 'Les plantes peuvent exécuter d''autres tâches pour vous, si le MD donne son accord. Le sort ne leur permet pas de se déraciner et de se déplacer, mais elles peuvent agiter leurs branches, leurs vrilles et leurs tiges.' || E'\n' || 'Si une créature végétale se trouve dans la zone, vous pouvez communiquer avec elle comme si vous partagiez un même langage, mais vous ne gagnez pas de capacité magique permettant de l''influencer.' || E'\n' || 'Ce sort permet de libérer une créature entravée par les plantes nées d''un sort d''_enchevêtrement_.',
        NULL
    ),
    (
        'Envoi de message',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        'illimité',
        'V, S, M (un petit bout de fil de cuivre)',
        '1 round',
        'Vous envoyez un court message d''au maximum 25 mots à une créature qui vous est familière. Elle entend le message dans son esprit, sait que c''est vous qui le lui avez envoyé si elle vous connaît, et peut vous répondre immédiatement de la même manière. Le sort permet aux créatures dotées d''une Intelligence minimale de 1 de comprendre le sens de votre message.' || E'\n' || 'Vous pouvez envoyer votre message à n''importe quelle distance et même sur un autre plan d''existence, mais si la cible est sur un autre plan, il y a 5% de chances que le message n''arrive pas à destination.',
        NULL
    ),
    (
        'Feindre la mort',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        'contact',
        'V, S, M (une pincée de poussière tombale)',
        '1 heure',
        'Vous touchez une créature consentante et la plongez dans un état cataleptique si profond qu''elle semble morte.' || E'\n' || 'Pendant toute la durée du sort ou jusqu''à ce que vous utilisiez une action pour toucher la cible et révoquer le sort, la cible paraît morte, même suite à un examen externe ou après utilisation d''un sort visant à déterminer son statut. Elle est aveuglée et neutralisée et sa vitesse passe à O. Elle est résistante à tous les types de dégâts hormis les dégâts psychiques. Si elle est empoisonnée ou malade au moment où vous lancez le sort ou si elle le devient pendant la durée du sort, la maladie ou le poison n''a aucun effet tant que ce sort n''est pas terminé.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/feign_death_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Glyphe de protection',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        'contact',
        'V, S, M (encens et poudre de diamant d''une valeur minimale de 200 po, que le sort consume)',
        'jusqu''à dissipation ou déclenchement',
        'Lorsque vous lancez ce sort, vous inscrivez un glyphe capable de blesser autrui, soit sur une surface quelconque, comme une table, le sol ou un mur, soit dans un objet que l''on peut refermer pour dissimuler l''inscription, comme un livre, un parchemin ou un coffre au trésor. Si vous optez pour une surface, le glyphe peut couvrir une zone de 3 mètres de diamètre au maximum. Si vous choisissez un objet, il ne faut plus le déplacer par la suite: si quelqu''un le déplace à plus de 3 mètres de l''endroit où vous avez jeté ce sort, le glyphe se brise et le sort se termine sans avoir été déclenché.' || E'\n' || 'Le glyphe est presque invisible. Pour le discerner, il faut réussir un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort.' || E'\n' || 'Lors de l''incantation, c''est à vous de décider de ce qui déclenchera le sort. Pour les glyphes tracés sur une surface quelconque, les déclencheurs les plus courants consistent à toucher le glyphe ou se tenir dessus, à déplacer un objet recouvrant le glyphe, à s''approcher à une certaine distance du glyphe ou encore à manipuler l''objet sur lequel le glyphe est tracé. Pour les glyphes inscrits dans un objet, on trouve parmi les déclencheurs les plus répandus le fait d''ouvrir l''objet, de s''en approcher à une certaine distance ou de voir ou de lire le glyphe. Le sort se termine dès que le glyphe se déclenche.' || E'\n' || 'Vous pouvez affiner le déclencheur, de façon à ce que le sort s''active sous certaines conditions ou en fonction de certaines caractéristiques physiques (comme le poids ou la taille), selon un type de créature (pour un glyphe destiné aux aberrations ou aux drows par exemple) ou selon l''alignement. Vous pouvez aussi définir des conditions pour que certaines créatures ne déclenchent pas le glyphe, en prononçant un mot de passe par exemple.' || E'\n' || 'Lorsque vous dessinez le glyphe, vous devez choisir entre des _runes explosives_ ou un _glyphe à sort_.' || E'\n' || '**Runes explosives**: Quand le glyphe se déclenche, il explose dans une sphère de 6 mètres de rayon centrée sur lui. La sphère s''étend en contournant les angles si besoin. Chaque créature de la zone doit faire un jet de sauvegarde de Dextérité. Une créature reçoit 5d8 points de dégâts d''acide, de froid, de feu, de foudre ou de tonnerre si elle rate sonjet (à vous de choisir le type de dégâts lors de l''incantation), la moitié seulement si elle le réussit.' || E'\n' || '**Glyphe à sort**: Vous pouvez stocker un sort de niveau 3 ou inférieur dans le glyphe en le lançant lors de l''incantation du glyphe. Ce sort doit viser une créature unique ou une zone. Le sort stocké n''a aucun effet immédiat quand il est lancé ainsi. Il se lance quand quelqu''un déclenche le glyphe. Si le sort affecte une cible, il vise celle qui a déclenché le glyphe. S''il affecte une zone, cette dernière est centrée sur la créature qui a déclenché le glyphe. Si le sort invoque des créatures hostiles ou crée des objets néfastes ou des pièges, ils apparaissent aussi près de l''intrus que possible et s''en prennent à lui. Si le sort nécessite de la concentration, il persiste jusqu''à la fin de sa durée maximale.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort enutilisant un emplacement de niveau 4 ou plus, les dégâts des runes explosives augmentent de 1d8 par niveau au-delà du 3e. Si vous créez un glyphe à sort, vous pouvez stocker un sort d''un niveau égal ou inférieur à celui employé pour lancer le glyphe.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/glyph_of_warding_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Jeter une malédiction',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        'contact',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous touchez une créature qui doit réussir un jet de sauvegarde de Sagesse, sans quoi elle est maudite pour toute la durée du sort. À vous de choisir la nature de cette malédiction parmi les options suivantes au moment de l''incantation.' || E'\n' || '* Choisissez une caractéristique. Tant que la cible est maudite, elle est désavantagée lors des tests de caractéristique et des jets de sauvegarde basés sur cette caractéristique.' || E'\n' || '* Tant que la cible est maudite, elle est désavantagée lors de ses jets d''attaque contre vous.' || E'\n' || '* Tant que la cible est maudite, elle doit faire un jet de sauvegarde de Sagesse au début de chacun de ses tours. Si elle le rate, elle gaspille son action du tour et ne fait rien.' || E'\n' || '* Tant que la cible est maudite, les sorts et les attaques émanant de vous lui infligent 1d8 dégâts nécrotiques supplémentaires.' || E'\n' || 'Le sort _Lever une malédiction_ met un terme à cet effet. Si le MD est d''accord, vous pouvez choisir un autre effet de malédiction, mais il ne doit pas être plus puissant que ceux proposés ici. C''est au MD de décider s''il accepte ou non le nouvel effet de malédiction.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, le sort fait effet tant que vous vous concentrez, sans dépasser un maximum de 10 minutes. Si vous utilisez un emplacement de niveau 5 ou plus, la durée est de 8 heures, tandis qu''elle passe à 24 heures si vous utilisez un emplacement de sort de niveau 7 ou plus. Si vous utilisez un emplacement de niveau 9 , le sort persiste jusqu''à ce qu''il soit dissipé. L''utilisation d''un emplacement de niveau 5 ou plus vous dispense de vous concentrer.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/bestow_curse_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Non-détection',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        'contact',
        'V, S, M (une pincée de poussière de diamant d''une valeur de 25 po, que le sort consume une fois saupoudrée sur la cible)',
        '8 heures',
        'Pendant toute la durée du sort, vous dissimulez la cible que vous touchez aux yeux de la magie de divination. Vous pouvez prendre pour cible une créature consentante, un endroit ou un objet ne mesurant pas plus de 3 mètres dans chaque dimension. La magie de divination ne peut plus viser votre cible et les organes de scrutation magiques ne la perçoivent plus.',
        NULL
    ),
    (
        'Petite hutte de Léomund',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 minute',
        'personnelle (hémisphère de 3 mètres de rayon)',
        'V, S, M (une petite perle de cristal)',
        '8 heures',
        'Un dôme de force immobile, de 3 mètres de rayon, apparaît soudain autour et au-dessus de vous. Il reste stationnaire pendant toute la durée du sort. Ce dernier se termine si vous quittez sa zone.' || E'\n' || 'Le dôme peut abriter un maximum de neuf créatures de taille Moyenne ou inférieure, en plus de vous. Le sort échoue si la zone comprend une créature de taille supérieure ou plus de neuf créatures. Les créatures et les objets qui se trouvent à l''intérieur du dôme lors de l''incantation peuvent en sortir et y entrer librement; en revanche, les autres créatures sont incapables de franchir ses limites. Les sorts et autres effets magiques ne peuvent pas s''étendre au-delà de la limite du dôme ni se lancer à travers. L''atmosphère au sein du dôme est agréable et sèche, quelles que soient les conditions météorologiques à l''extérieur.' || E'\n' || 'Tant que le sort n''est pas terminé, vous pouvez faire en sorte que l''intérieur du dôme soit faiblement éclairé ou plongé dans le noir. Vu de l''extérieur, le dôme est opaque, de la couleur que vous désirez, mais vu de l''intérieur, il est transparent.',
        NULL
    ),
    (
        'Animation des morts',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 minute',
        '3 mètres',
        'V, S, M (une goutte de sang, un lambeau de chair et une pincée de poudre d''os)',
        'instantanée',
        'Ce sort crée un serviteur mort-vivant. Choisissez un tas d''os ou le cadavre d''un humanoïde de taille Moyenne ou Petite situé à portée. Votre sort imprègne la cible d''un ignoble simulacre de vie, la relevant sous forme de mort-vivant. Elle devient un squelette si vous avez lancé le sort sur un tas d''os, et un zombi si vous avez opté pour un cadavre (le MD dispose des statistiques de jeu de la créature).' || E'\n' || 'À chacun de vos tours, vous pouvez dépenser une action bonus pour donner un ordre mental à la créature générée via ce sort si elle se trouve dans un rayon de 18 mètres (si vous contrôlez plusieurs créatures, vous pouvez donner un ordre à l''une d''elles, certaines d''entre elles ou à toutes à la fois, à condition de transmettre le même ordre à chacune). À vous de décider quelles actions la créature va entreprendre et à quel endroit elle se déplacera au cours du tour suivant, mais vous pouvez aussi lui donner un ordre plus générique, comme de garder une salle ou un couloir. En l''absence d''ordre, la créature se contente de se défendre contre les créatures hostiles. Une fois qu''elle a reçu un ordre, elle continue à le suivre jusqu''à ce qu''elle ait accompli sa tâche.' || E'\n' || 'La créature est placée sous votre contrôle pendant 24 heures, après quoi elle cesse d''obéir aux ordres que vous lui avez donnés. Pour la contrôler pendant 24 heures de plus, il vous faut lui relancer ce sort avant la fin de la période de 24 heures pendant laquelle il fait effet. Si vous utilisez ce sort ainsi, il vous permet de réaffirmer votre contrôle sur un maximum de quatre créatures animées grâce à lui plutôt que d''en animer une nouvelle.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, vous animez ou réaffirmez votre contrôle sur deux créatures de plus par niveau au-delà du 3e. Chaque créature doit venir d''un tas d''os ou d''un cadavre différent.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/animate_dead_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Esprits gardiens',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        'personnelle (4,50 mètres de rayon)',
        'V, S, M (un symbole sacré)',
        'concentration, jusqu''à 10 minutes',
        'Vous appelez des esprits qui vous protègent. Ils volètent autour de vous dans un rayon de 4,50 mètres pendant toute la durée du sort. Si vous êtes Bon ou Neutre, ils ont une apparence angélique ou féerique (à vous de choisir). Si vous êtes Mauvais, ils ont une apparence fiélone.' || E'\n' || 'Quand vous lancez le sort, vous pouvez désigner autant de créatures que vous le voulez afin qu''il ne les affecte pas. Une créature affectée voit sa vitesse réduite de moitié dans la zone et, quand elle y entre pour la première fois de son tour ou quand elle y commence son tour, elle doit faire unjet de sauvegarde de Sagesse. Si elle échoue, elle subit 3d8 dégâts radiants (si vous êtes Bon ou Neutre) ou 3d8 dégâts nécrotiques (si vous êtes Mauvais). Si elle réussit son jet de sauvegarde, elle subit seulement la moitié de ces dégâts.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spiritguardians_conjuration_spell_bg3_wiki_64px.png'
    ),
    (
        'Fusion dans la pierre',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'contact',
        'V, S',
        '8 heures',
        'Vous entrez dans un objet ou une surface de pierre assez grande pour contenir entièrement votre corps, votre personne et votre équipement fusionnant avec la pierre pendant toute la durée du sort. Vous utilisez votre déplacement pour entrer dans la pierre en un point que vous êtes en mesure de toucher. Il ne reste alors rien de visible ni de détectable indiquant votre présence pour des sens non magiques.' || E'\n' || 'Tant que vous êtes fusionné avec la pierre, vous ne voyez pas ce qui se passe à l''extérieur et vous êtes désavantagé lors des tests de Sagesse (Perception) destinés à entendre les sons qui retentissent à l''extérieur de la pierre. Vous restez conscient du temps qui passe et vous pouvez lancer des sorts sur votre propre personne. Vous pouvez utiliser votre déplacement pour quitter la pierre par l''endroit par où vous y êtes entré, ce qui met fin au sort. En dehors de cela, vous êtes dans l''incapacité de vous déplacer.' || E'\n' || 'Vous n''êtes pas blessé si la pierre subit des dégâts mineurs, mais si elle est partiellement détruite ou change de forme (au point que vous ne tenez plus entièrement à l''intérieur), elle vous expulse et vous subissez 6d6 dégâts contondants. Si la pierre est complètement détruite (ou transmutée en une substance différente), elle vous expulse et vous subissez 50 dégâts contondants. Si vous vous faites expulser de la pierre, vous vous retrouvez à terre dans l''emplacement inoccupé le plus proche de celui par lequel vous êtes entré dans la roche.',
        NULL
    ),
    (
        'Lueur d''espoir',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        '9 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Ce sort offre espoir et robustesse. Choisissez autant de créatures consentantes à portée que vous le désirez. Pendant toute la durée du sort, elles sont avantagées lors des jets de sauvegarde de Sagesse et des jets de sauvegarde contre la mort. De plus, elles récupèrent le maximum de points de vie possible dès qu''elles reçoivent des soins.',
        NULL
    ),
    (
        'Mot de guérison de groupe',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action bonus',
        '18 mètres',
        'V',
        'instantanée',
        'Vous prononcez des paroles curatives qui rendent un montant de points de vie égal à 1d4 + votre modificateur de caractéristique d''incantation à un maximum de six créatures de votre choix situées à portée et dans votre champ de vision. Ce sort reste sans effet sur les morts-vivants et les créatures artificielles.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les soins augmentent de 1d4 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/mass_healing_word_icon_baldurs_gate_3_wiki_guide_64px.png'
    ),
    (
        'Appel de la foudre',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Un nuage orageux apparaît sous forme d''un cylindre de 3 mètres de haut pour 18 mètres de rayon, centré sur un point situé dans votre champ de vision et à 30 mètres directement au-dessus de vous. Le sort échoue si vous ne pouvez voir le point situé à cette hauteur, là où le nuage doit se former (si vous vous trouvez dans une pièce trop petite pour accueillir le nuage par exemple).' || E'\n' || 'Quand vous lancez le sort, vous devez choisir un point situé à portée et dans votre champ de vision. Un éclair jaillit du nuage et vient frapper ce point. Chaque créature située dans un rayon de 1,50 mètre autour de ce point doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 3d10 dégâts de foudre, les autres la moitié seulement. À chacun de vos tours jusqu''à la fin du sort, vous pouvez dépenser votre action pour appeler ainsi la foudre, en visant le même point ou un autre.' || E'\n' || 'Si, au moment de l''incantation, vous vous trouvez en extérieur et que les conditions sont déjà orageuses, le sort vous donne le contrôle de l''orage déjà présent au lieu d''en créer un nouveau. Dans ce cas, les dégâts du sort augmentent de 1d10.' || E'\n' || '**À plus haut niveau:** Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d10 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/call_lightning_icon_baldurs_gate_3_wiki_guide_64px.png'
    ),
    (
        'Invoquer des animaux',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez des esprits féeriques qui prennent la forme d''animaux et apparaissent dans des cases inoccupées situées à portée et dans votre champ de vision. Choisissez l''une des options suivantes pour déterminer quelles créatures apparaissent.' || E'\n' || '* Une bête d''une dangerosité de 2 ou moins.' || E'\n' || '* Deux bêtes d''une dangerosité de 1 ou moins.' || E'\n' || '* Quatre bêtes d''une dangerosité de 1/2 ou moins.' || E'\n' || '* Huit bêtes d''une dangerosité de 1/4 ou moins.' || E'\n' || 'Chacune de ces bêtes est aussi considérée comme une fée et disparaît dès qu''elle tombe à 0 point de vie ou quand le sort se termine.' || E'\n' || 'Les créatures invoquées se montrent amicales envers vous et vos compagnons. Lancez l''initiative pour les créatures invoquées en tant que groupe qui dispose de ses propres tours de jeu. Les animaux obéissent aux ordres verbaux que vous leur donnez (sans que cela vous demande d''utiliser une action). En l''absence d''ordre, ils se défendent contre les créatures hostiles, mais n''entreprennent pas d''autre action.' || E'\n' || 'C''est le MD qui dispose des statistiques des créatures.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant certains emplacements de niveau supérieur, vous choisissez l''une des options d''invocation décrites précédemment et faites apparaître plus de créatures : deux fois plus pour un emplacement de niveau 5, trois fois plus pour un emplacement de niveau 7 et quatre fois plus pour un emplacement de niveau 9.',
        NULL
    ),
    (
        'Mur de vent',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (un petit éventail et une plume exotique)',
        'concentration, jusqu''à 1 minute',
        'Un mur de vent fort se lève soudain depuis le sol en un point de votre choix à portée. Vous pouvez lui faire couvrir jusqu''à 15 mètres de long, 4,50 mètres de haut et 30 centimètres d''épaisseur. Vous pouvez lui donner la forme que vous voulez tant qu''il dessine un chemin continu au sol. Ce mur persiste pendant toute la durée du sort.' || E'\n' || 'Quand le mur apparaît, chaque créature située dans sa zone doit faire unjet de sauvegarde de Force. Les créatures qui échouent subissent 3d8 dégâts contondants, les autres la moitié seulement.' || E'\n' || 'Le vent fort maintient la brume, la fumée et les autres gaz à l''écart. Les créatures et objets volants de taille Petite ou inférieure ne peuvent pas traverser le mur. Les matériaux libres et légers s''envolent si on les apporte dans le mur. Les flèches, les carreaux et autres projectiles ordinaires visant une cible située derrière le mur sont systématiquement détournés vers le haut et ratent automatiquement leur cible. (Ce phénomène n''affecte pas les rochers que lancent les géants ou les engins de siège, ni les projectiles similaires.) Les créatures sous forme gazeuse ne peuvent pas franchir le mur.',
        NULL
    ),
    (
        'Boule de feu',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '45 mètres',
        'V, S, M (une petite boule de guano de chauve-souris et du soufre)',
        'instantanée',
        'Une traînée luisante part de votre doigt tendu et file vers un point de votre choix situé à portée et dans votre champ de vision, où elle explose dans une gerbe de flammes grondantes. Chaque créature située dans une sphère de 6 mètres de rayon centrée sur ce point doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 8d6 dégâts de feu, les autres la moitié seulement.' || E'\n' || 'Le feu s''étend en contournant les angles. Il embrase les objets inflammables de la zone, à moins que quelqu''un ne les porte ou ne les transporte.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fireball_spell_bg3_wiki_guide64px.png'
    ),
    (
        'Clairvoyance',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '10 minutes',
        '1,5 kilomètre',
        'V, S, M (un focaliseur d''une valeur minimale de 100 po, soit une corne incrustée de pierreries pour l''ouïe, soit un oeil de verre pour la vue)',
        'concentration,jusqu''à 10 minutes',
        'Vous créez un organe sensoriel invisible à portée dans un endroit qui vous est familier (un endroit où vous vous êtes déjà rendu ou que vous avez déjà vu) ou dans un endroit évident qui ne vous est pas familier (comme de l''autre côté d''une porte, derrière un coin,dans un bosquet...). L''organe reste là pendant toute la durée du sort. Il est impossible de l''attaquer ou d''interagir avec.' || E'\n' || 'Vous choisissez la vue ou l''ouïe au moment où vous lancez le sort. Vous pouvez alors utiliser le sens choisi à travers l''organe comme si vous occupiez son emplacement. Vous pouvez dépenser une action pour passer de la vue à l''ouïe ou inversement.' || E'\n' || 'Une créature capable de voir l''organe sensoriel (en bénéficiant par exemple de _voir l''invisible_ ou de _vision parfaite_) le perçoit comme un orbe lumineux intangible de la taille de votre poing.',
        NULL
    ),
    (
        'Clignotement',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'personnelle',
        'V, S',
        '1 minute',
        'Pendant toute la durée du sort, vous lancez 1d20 à la fin de chacun de vos tours. Sur un 11 ou plus, vous disparaissez de votre plan d''existence actuel et apparaissez sur le plan éthéré (si vous vous trouviez déjà là, le sort échoue et l''incantation est gaspillée). Au début de votre tour suivant et quand le sort se termine alors que vous vous trouvez sur le plan éthéré, vous retournez sur un emplacement inoccupé de votre choix que vous pouvez voir dans un rayon de 3 mètres autour de l''emplacement dont vous avez disparu. S''il n''y a pas d''emplacement disponible dans ce rayon, vous apparaissez dans l''espace inoccupé le plus proche (choisi au hasard s''il y en a plusieurs à égale distance). Vous pouvez révoquer ce sort par une action.' || E'\n' || 'Tant que vous êtes sur le plan éthéré, vous voyez et entendez ce qui se passe sur le plan d''où vous venez, qui apparaît sous forme d''ombres grises, mais votre vision ne porte pas au-delà de 18 mètres. Vous pouvez seulement affecter des créatures se trouvant sur le plan éthéré et elles sont les seules à pouvoir vous affecter. Les créatures qui ne se trouvent pas sur ce plan ne peuvent ni vous percevoir, ni interagir avec vous, à moins qu''elles ne disposent d''un pouvoir le leur permettant.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blink-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Contresort',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 réaction à utiliser quand vous voyez une créature située dans un rayon de 18 mètres autour de vous lancer un sort',
        '18 mètres',
        'S',
        'instantanée',
        'Vous tentez d''interrompre une créature en pleine incantation. Si elle essayait de lancer un sort de niveau 3 ou moins, il échoue et reste sans effet. Si le sort est de niveau 4 ou plus, faites un test de caractéristique en utilisant votre caractéristique d''incantation. Le DD est de 10 + niveau du sort. Si vous réussissez, le sort de la créature échoue et reste sans effet.' || E'\n' || 'Au moment de l''incantation, vous pouvez désigner plusieurs créatures de votre choix que le sort ignorera.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, le sort à interrompre est automatiquement sans effet s''il est d''un niveau égal ou inférieur à celui de l''emplacement de sort utilisé.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/counterspell_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Eclair',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (ligne de 30 mètres)',
        'V, S, M (un peu de fourrure et une baguette en ambre, en cristal ou en verre)',
        'instantanée',
        'Un éclair formant une ligne de 30 mètres de long pour 1,50 mètre de large jaillit de votre personne et file dans la direction de votre choix. Chaque créature située sur la ligne doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 8d6 dégâts de foudre, les autres la moitié seulement.' || E'\n' || 'La foudre embrase les objets inflammables de la zone qui ne sont ni portés ni transportés par une créature.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/lightningbolt-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Forme gazeuse',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (un morceau de gaze et une volute de fumée)',
        'concentration, jusqu''à 1 heure',
        'Vous touchez une créature consentante et la transformez, ainsi que tous les objets qu''elle porte et qu''elle transporte, en nuage brumeux pour toute la durée du sort. Ce dernier se termine si la créature tombe à O point de vie. Le sort n''affecte pas les créatures intangibles.' || E'\n' || 'Sous cette forme, la cible n''a plus qu''un seul mode de déplacement : le vol, à une vitesse de 3 mètres. Elle peut entrer dans l''espace d''une autre créature et l''occuper. Elle est résistante aux dégâts non magiques et elle est avantagée lors des jets de sauvegarde de Force, de Dextérité et de Constitution. Elle peut passer à travers de petits trous, de minces ouvertures et même de simples fissures ; en revanche, les liquides équivalent pour elle à des surfaces solides. Elle ne peut pas tomber et continue de flotter dans les airs même si elle est étourdie ou neutralisée.' || E'\n' || 'Sous forme de nuage brumeux, la cible ne peut pas parler ni manipuler d''objet. Il lui est impossible de lâcher les objets qu''elle portait et qu''elle transportait et personne ne peut les utiliser ni interagir avec eux. Elle ne peut pas attaquer ni lancer de sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/gaseous_form_spell_bg3_wiki_guide64px.png'
    ),
    (
        'Hâte',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (un copeau de racine de réglisse)',
        'concentration, jusqu''à 1 minute',
        'Choisissez une créature consentante située à portée dans votre champ de vision. Jusqu''à la fin du sort, la cible voit sa vitesse doubler, gagne un bonus de +2 à la CA, est avantagée lors des jets de sauvegarde de Dextérité et dispose d''une action de plus par tour. Cette action est uniquement réservée aux actions suivantes : attaquer (une attaque à l''arme seulement), se précipiter, se désengager, se cacher ou utiliser un objet.' || E'\n' || 'Quand le sort se termine, la cible ne peut pas se déplacer ni effectuer une action avant que son prochain tour ne se soit écoulé, car une vague de léthargie déferle sur elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/haste_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Image majeure',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        '36 mètres',
        'V, S, M (un morceau de toison)',
        'concentration, jusqu''à 10 minutes',
        'Vous créez l''image d''un objet, d''une créature ou d''un phénomène visible pas plus grand qu''un cube de 6 mètres d''arête. L''image apparaît en un point situé à portée et dans votre champ de vision et persiste pendant toute la durée du sort. Elle a l''air absolument réelle et s''accompagne des sons, des odeurs et de la température appropriés pour la chose qu''elle représente. En revanche, elle ne dégage pas assez de chaleur ou de froid pour blesser quelqu''un, ne génère pas de sons assez puissants pour provoquer des dégâts de tonnerre ou assourdir une créature, et n''émet pas une odeur assez puissante pour écœurer une créature (comme le fait la puanteur du troglodyte).' || E'\n' || 'Tant que vous êtes à portée de l''illusion, vous pouvez utiliser votre action pour déplacer l''image vers un autre point situé à portée. Quand l''image bouge, vous pouvez modifier son apparence de manière à ce que ses mouvements paraissent naturels. Par exemple, si vous créez l''image d''une créature et la déplacez, vous pouvez modifier l''image pour donner l''impression que la créature marche. De même, vous pouvez modifier les sons que l''image émet, à tel point que vous pouvez lui faire tenir une conversation, par exemple.' || E'\n' || 'Les interactions physiques avec l''image révèlent qu''elle n''est qu''une illusion, car les objets la traversent. Si une créature utilise son action pour examiner l''image, elle comprend que c''est une illusion à condition de réussir un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort. Si une créature perce l''illusion à jour, elle voit à travers l''image et ne perçoit plus que faiblement ses autres propriétés sensorielles.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 6 ou plus, le sort persiste jusqu''à dissipation, sans que vous ayez besoin de vous concentrer.',
        NULL
    ),
    (
        'Langues',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'contact',
        'V, M (un modèle réduit de ziggourat en argile)',
        '1 heure',
        'Ce sort permet à la créature que vous touchez de comprendre toutes les langues parlées qu''elle entend. De plus, quand elle parle, toute créature qui maîtrise au moins une langue et l''entend comprend ce qu''elle dit.',
        NULL
    ),
    (
        'Lenteur',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '36 mètres',
        'V, S, M (une goutte de mélasse)',
        'concentration, jusqu''à 1 minute',
        'Vous modifiez le cours du temps autour d''un maximum de six créatures de votre choix situées dans un cube de 12 mètres d''arête situé à portée. Chaque cible doit réussir un jet de sauvegarde de Sagesse, sans quoi le sort l''affecte pendant toute sa durée.' || E'\n' || 'Une cible affectée voit sa vitesse réduite de moitié. De plus, elle subit un malus de -2 à la CA et aux jets de sauvegarde de Dextérité et ne peut plus utiliser de réaction. À son tour, elle peut utiliser une action ou une action bonus, mais pas les deux. Elle ne peut pas faire plus d''une attaque au corps à corps ou à distance à son tour, quels que soient ses pouvoirs et ses objets magiques.' || E'\n' || 'Si la créature affectée tente de lancer un sort doté d''un temps d''incantation de 1 action, lancez un d20. Sur un 11 ou plus, le sort agit seulement au prochain tour de la créature qui doit utiliser son action de ce tour pour terminer l''incantation. Si elle est en incapable, le sort est gâché.' || E'\n' || 'Une créature affectée par ce sort fait un nouveau jet de sauvegarde de Sagesse à la fin de son tour. Si elle le réussit, le sort se termine pour elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/slow_spell_transmutation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Marche sur l''eau',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (un bout de liège)',
        '1 heure',
        'Ce sort permet de se déplacer sur n''importe quelle surface liquide (comme de l''eau, de l''acide, de la boue, de la neige, des sables mouvants ou de la lave) comme s''il s''agissait d''un sol ferme et inoffensif (ceci dit, les créatures qui marchent sur la lave subissent tout de même les dégâts liés à la chaleur dégagée). Vous pouvez accorder cette capacité pendant toute la durée du sort à un maximum de dix créatures consentantes situées à portée et dans votre champ de vision.' || E'\n' || 'Si vous prenez pour cible une créature immergée dans un liquide, le sort la ramène à la surface du liquide à une vitesse de 18 mètres par round.',
        NULL
    ),
    (
        'Motif hypnotique',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        '36 mètres',
        'S, M (un bâtonnet d''encens incandescent ou une fiole de cristal remplie d''une matière phosphorescente)',
        'concentration, jusqu''à 1 minute',
        'Vous tissez dans les airs un motif aux couleurs mouvantes dans un cube de 9 mètres d''arête situé à portée. Le motif apparaît pendant un bref instant avant de s''évanouir. Chaque créature qui se trouve dans la zone et voit le motif doit faire un jet de sauvegarde de Sagesse. Celles qui échouent sont charmées pendant la durée du sort. Tant qu''une créature est charmée par ce sort, elle est neutralisée et a une vitesse de 0.' || E'\n' || 'Le sort se termine pour une créature donnée si elle subit le moindre dégât ou si quelqu''un d''autre utilise son action pour la secouer et la sortir de sa torpeur.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hypnotic_pattern_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Nuage puant',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '27 mètres',
        'V, S, M (un œuf pourri ou des feuilles de chou pourri)',
        'concentration,jusqu''à 1 minute',
        'Vous créez une sphère d''un gaz jaunâtre et nauséabond de 6 mètres de rayon centrée sur un point à portée. Le nuage se répand en contournant les angles et la visibilité est nulle dans toute sa zone. Le nuage persiste dans la zone affectée pendant toute la durée du sort.' || E'\n' || 'Chaque créature entièrement englobée dans le nuage au début de son tour doit faire un jet de sauvegarde de Constitution contre le poison. Celles qui échouent passent toute leur action du tour à vomir. Les créatures qui ne respirent pas et celles qui sont immunisées contre le poison réussissent automatiquement ce jet.' || E'\n' || 'Un vent modéré (au moins 15 km/h) disperse le nuage après 4 rounds. Un vent fort (au moins 30 km/h) le disperse au bout de seulement 1 round.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/stinking_cloud_spell_bg3_wiki_guide64px.png'
    ),
    (
        'Peur',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'personnelle (cône de 9 mètres)',
        'V, S, M (une plume blanche ou un cœur de poule)',
        'concentration, jusqu''à 1 minute.',
        'Vous projetez une image fantasmagorique des pires terreurs d''une créature. Chaque créature située dans un cône de 9 mètres doit réussir un jet de sauvegarde de Sagesse ou lâcher tout ce qu''elle tient en main et être terrorisée pendant toute la durée du sort.' || E'\n' || 'Tant qu''une créature est terrorisée par ce sort, elle est obligée d''utiliser l''action se précipiter à chacun de ses tours et de s''éloigner de vous par l''itinéraire le plus sûr, à moins qu''elle n''ait nulle part où aller. Si elle termine son tour en un endroit où vous ne figurez plus dans son champ de vision, elle peut faire un jet de sauvegarde de Sagesse. Si elle le réussit, le sort se termine pour elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fear_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Protection contre l''énergie',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Pendant toute la durée du sort, la créature consentante que vous touchez devient résistante à un type de dégâts de votre choix : acide, feu, froid, foudre ou tonnerre.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/protection_from_energy_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Respiration aquatique',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (un petit roseau ou un brin de paille)',
        '24 heures',
        'Grâce à ce sort, un maximum de dix créatures situées à portée et dans votre champ de vision deviennent capables de respirer sous l''eau jusqu''à la fin du sort. Les créatures affectées conservent en plus leur mode de respiration normal.',
        NULL
    ),
    (
        'Tempête de neige',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '45 mètres',
        'V, S, M (une pincée de poussière et quelques gouttes d''eau)',
        'concentration, jusqu''à 1 minute',
        'Jusqu''à la fin du sort, une averse de flocons et de neige fondue s''abat dans un cylindre de 6 mètres de haut pour un rayon de 12 mètres centré sur un point de votre choix situé à portée. Dans la zone, la visibilité est fortement obstruée et les flammes à nu s''éteignent.' || E'\n' || 'Le sol de la zone est couvert d''une couche de glace si glissante que le terrain devient difficile. Quand une créature entre dans la zone d''effet pour la première fois de son tour ou y commence son tour, elle doit faire un jet de sauvegarde de Dextérité. Si elle échoue, elle tombe à terre.' || E'\n'|| 'Si une créature se concentre dans la zone d''effet du sort, elle doit faire un jet de sauvegarde de Constitution contre le DD du jet de sauvegarde de votre sort. Si elle échoue, elle perd sa concentration.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/sleet_storm_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Vol',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une rémige)',
        'concentration, jusqu''à 10 minutes',
        'Vous touchez une créature consentante et lui conférez la capacité de voler à une vitesse de 18 mètres pendant toute la durée du sort. Si la cible se trouve dans les airs quand le sort se termine, elle tombe, à moins de pouvoir arrêter sa chute.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fly_spell_bg3_wiki_guide64px.png'
    ),
    (
        'Monture fantôme',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        '9 mètres',
        'V, S',
        '1 heure',
        'Une créature équine de taille Grande quasi réelle apparaît dans un emplacement au sol de votre choix situé à portée. À vous de décider de l''apparence de la créature, mais elle est systématiquement équipée d''une selle, d''un mors et d''un filet. Toutes les pièces d''équipement nées de ce sort disparaissent dans une volute de fumée si quelqu''un les emporte à plus de 3 mètres de la monture.' || E'\n' || 'Pendant toute la durée du sort, vous et une créature de votre choix pouvez chevaucher la monture. Cette dernière possède les mêmes statistiques qu''un cheval de selle, sauf qu''elle a une vitesse de 30 mètres et peut parcourir 15 kilomètres en une heure ou 20 kilomètres si elle galope. Quand le sort se termine, la monture s''estompe progressivement, ce qui laisse une minute au cavalier pour mettre pied à terre. Le sort se termine si vous utilisez une action pour le révoquer ou si la monture subit le moindre dégât.',
        NULL
    ),
    (
        'Arme élémentaire',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S',
        'concentration,jusqu''à 1 heure',
        'Vous touchez une arme non magique pour la rendre magique. Choisissez l''un des types de dégâts suivants : acide, feu, foudre, froid ou tonnerre. Pendant toute la durée du sort, l''arme bénéficie d''un bonus de +1 aux jets d''attaque et inflige 1d4 dégâts supplémentaires du type choisi.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 5 ou 6, le bonus aux jets d''attaque passe à+2 et les dégâts supplémentaires à 2d4. Quand vous utilisez un emplacement de sort de niveau 7 ou plus, le bonus passe à +3 et les dégâts supplémentaires à 3d4.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/elementalweapon-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Aura de vitalité',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (9 m de rayon)',
        'V',
        'concentration,jusqu''à 1 minute',
        'Une énergie curative émane de vous et forme une aura dans un rayon de 9 mètres. Cette aura se déplace avec vous jusqu''à la fin du sort et reste centrée sur vous. Vous pouvez utiliser une action bonus pour rendre 2d6 points de vie à une créature située au sein de l''aura, vous y compris.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wardenofvitality-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Aura du croisé',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle',
        'V',
        'concentration,jusqu''à 1 minute',
        'Une puissance sacrée émane de vous et forme une aura d''un rayon de 9 mètres, réveillant la combativité de vos amis. L''aura est centrée sur vous et se déplace avec vous jusqu''à la fin du sort. Toutes les créatures non hostiles (y compris vous-même) situées en son sein infligent 1d4 dégâts radiants de plus quand elles touchent une cible avec une attaque armée.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/crusadersmantle-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Cercle magique',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 minute',
        '3 mètres',
        'V, S, M (eau bénite/poudre d''argent et de fer d''une (valeur>=100 po), que le sort consume)',
        '1 heure',
        'Vous créez un cylindre d''énergie magique de 3 mètres de rayon pour 6 mètres de haut, centré sur un point au sol situé à portée et dans votre champ de vision. Des runes luisantes apparaissent là où le cylindre touche le sol ou une autre surface.' || E'\n' || 'Choisissez l''un des types de créatures suivants: célestes, élémentaires, fées, fiélons ou morts-vivants. Le cercle affecte une créature du type choisi de la manière suivante.' || E'\n' || 'La créature ne peut pas entrer de son plein gré dans le cylindre par des moyens non magiques. Si elle tente d''utiliser la téléportation ou le voyage extraplanaire pour y pénétrer, elle doit auparavant réussir un jet de sauvegarde de Charisme.' || E'\n' || 'La créature est désavantagée lors des jets d''attaque contre les créatures se trouvant dans le cylindre.' || E'\n' || 'La créature ne peut ni charmer, ni terroriser, ni posséder les créatures situées dans le cylindre.' || E'\n' || 'Quand vous lancez ce sort, vous pouvez décider que sa magie agira à l''envers, empêchant les créatures du type choisi de quitter le cercle et protégeant contre elles les individus situés à l''extérieur du cercle.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, la durée du sort augmente d''une heure par niveau au-delà du 3e.',
        NULL
    ),
    (
        'Création de nourriture et d''eau',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '9 mètres',
        'V, S',
        'instantanée',
        'Vous créez 22,5 kilos de nourriture et 120 litres d''eau, soit par terre, soit dans des récipients installés à portée. Cela suffit à nourrir et abreuver un maximum de quinze humanoïdes ou de cinq montures pendant 24 heures. Les vivres sont fades mais nourrissants. Ils se gâtent si personne ne les a mangés dans les 24 heures suivant leur création. L''eau est claire et ne croupit pas.',
        NULL
    ),
    (
        'Dissipation de la magie',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        '36 mètres',
        'V, S',
        'instantanée',
        'Choisissez une créature, un objet ou un effet magique à portée. Tout sort de niveau 3 ou inférieur qui l''affecte se termine. Si la cible est affectée par un sort de niveau 4 ou plus, faites un test de caractéristique en utilisant votre caractéristique d''incantation. Le DD est de 10 + niveau du sort. Ce dernier se termine si vous réussissez votre test.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, vous mettez automatiquement un terme à un sort affectant la cible quand le niveau de ce sort est égal ou inférieur au niveau de l''emplacement de sort que vous utilisez.',
        NULL
    ),
    (
        'Frappe aveuglante',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration,jusqu''à 1 minute',
        'La prochaine attaque armée qui vous permet de toucher une créature avant la fin de ce sort voit votre arme briller d''une vive lumière et inflige 3d8 dégâts radiants de plus à votre cible. De plus, la cible doit réussir un jet de sauvegarde de Constitution, sans quoi elle est aveuglée jusqu''à la fin du sort.' || E'\n' || 'Une créature aveuglée par ce sort a droit à un nouveau jet de sauvegarde de Constitution à la fin de chacun de ses tours. Dès qu''elle en réussit un, elle n''est plus aveuglée.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blindingsmite-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Lever une malédiction',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S',
        'instantanée',
        'À votre contact, toutes les malédictions qui affectent une créature ou un objet disparaissent. Si l''objet est un objet magique maudit, la malédiction persiste, mais le sort rompt l''harmonisation entre l''objet et son détenteur, ce qui permet à ce dernier de l''ôter ou de s''en débarrasser.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/remove_curse_spells_bg3_wiki_guide150px.png'
    ),
    (
        'Lumière du jour',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '18 mètres',
        'V, S',
        '1 heure',
        'Une sphère de lumière de 18 mètres de rayon s''étend depuis un point de votre choix situé à portée. Elle émet une lumière vive dans ce rayon et une lumière faible dans un rayon de 18 mètres de plus.' || E'\n' || 'Si le point que vous avez choisi est un objet en votre possession ou un objet qui n''est ni porté ni transporté par autrui, la lumière irradie de l''objet et se déplace avec lui. Il suffit de recouvrir complètement l''objet affecté avec un objet opaque, comme un bol ou un heaume, pour bloquer la lumière.' || E'\n' || 'Si une partie de la zone affectée par ce sort chevauche une zone de ténèbres issue d''un sort de niveau 3 ou moins, elle dissipe le sort de ténèbres.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/daylight_spell_bg3_wiki_guide150px.png'
    ),
    (
        'Revigorer',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        'contact',
        'V, S, M (diamant d''une valeur de 300 po, que le sort consume)',
        'instantanée',
        'Vous touchez une créature morte au cours de la minute précédente. Elle revient à la vie avec 1 point de vie. Ce sort ne ramène pas à la vie les créatures mortes de vieillesse et ne restaure pas les parties manquantes du corps.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/revivify_necromancy_spell_bg3_wiki_150px.png'
    ),
    (
        'Flèche de foudre',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action bonus',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Lors de la prochaine attaque que vous effectuez avec une arme à distance pendant que ce sort est actif, la munition (ou l''arme s''il s''agit d''une arme de jet) se change en éclair. Faites un jet d''attaque ordinaire. Si vous touchez, la cible subit 4d8 dégâts de foudre au lieu des dégâts normaux, la moitié si vous la ratez.' || E'\n' || 'Que vous touchiez ou ratiez votre cible, toutes les créatures situées dans un rayon de 3 mètres autour d''elle doivent faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 2d8 dégâts de foudre, les autres la moitié seulement.' || E'\n' || 'La munition ou l''arme de jet reprend ensuite sa forme normale.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts dus à chacun des deux effets du sort augmentent de 1d8 par emplacement de sort au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/lightningarrow-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Invoquer un tir de barrage',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        'personnelle (cône de 18 mètres)',
        'V, S, M (une munition ou une arme de jet)',
        'instantanée',
        'Vous lancez une arme de jet non magique ou un projectile non magique, afin de créer un cône d''armes identiques qui filent dans les airs avant de disparaître. Chaque créature située dans un cône de 18 mètres doit réussir un jet de sauvegarde de Dextérité. Celles qui échouent subissent 3d8 dégâts, les autres la moitié seulement. Le type de dégâts est identique à celui du projectile utilisé comme composante.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/conjurebarrage-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Appétit d''Hadar',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '45 mètres',
        'V, S, M (tentacule de pieuvre en saumure)',
        'concentration, jusqu''à 1 minute',
        'Vous ouvrez un portail sur le vide intersidéral, une région plongée dans les ténèbres et infestée par des horreurs inconnues. Une sphère de 6 mètres de rayon apparaît. Elle est faite de ténèbres et d''un froid mordant et centrée sur un point à portée. Elle reste là pendant toute la durée du sort. Dans ce néant, on entend une cacophonie de sinistres murmures et de bruits de mastication, audibles dans un rayon de 9 mètres. Aucune lumière, ni magique ni autre, ne peut illuminer la zone et toute créature entièrement englobée en son sein est aveuglée. Le néant crée une distorsion dans le tissu de l''espace et la zone est considérée comme un terrain difficile. Toute créature qui y commence son tour subit 2d6 dégâts de froid. Une créature qui y termine son tour doit réussir un jet de sauvegarde de Dextérité, sans quoi des tentacules laiteux venus d''ailleurs la palpent et lui infligent 2d6 dégâts d''acide.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hunger_of_hadar_conjuration_spell_bg3_wiki_64px.png'
    ),
    (
        'Caresse du vampire',
        3,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Le simple contact de votre main enveloppée d''ombres peut siphonner la force vitale d''autrui pour soigner vos propres plaies. Faites une attaque de sort au corps à corps contre une créature située à une distance inférieure ou égale à votre allonge. Si vous touchez, elle subit 3d6 dégâts nécrotiques et vous récupérez un montant de points de vie égal à la moitié des dégâts infligés. Vous pouvez dépenser votre action à chacun de vos tours pour répéter cette attaque jusqu''à la fin du sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 3e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/vampiric_touch_spells_bg3_wiki_guide64px.png'
    );