INSERT INTO sort (nom_sort,alias,nom_sort_en,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Apaisement des émotions',
        NULL,
        'Calm emotions',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous tentez de supprimer les émotions fortes au sein d''un groupe de gens. Chaque humanoïde qui se trouve dans une sphère de 6 mètres de rayon centrée autour d''un point de votre choix situé à portée doit faire un jet de sauvegarde de Charisme. Une créature peut décider de rater volontairement ce jet, sachant que lorsqu''une créature rate son jet de sauvegarde, vous l''affectez avec l''un des deux effets suivants, à votre choix.' || E'\n' || 'Vous débarrassez temporairement la cible de tout état charmé ou terrorisé. Une fois le sort terminé, l''état s''applique de nouveau, à moins que sa durée n''ait expiré.' || E'\n' || 'Sinon, vous rendez la cible indifférente vis-à-vis des créatures de votre choix, envers lesquelles elle était auparavant hostile. Cette indifférence prend fin si la cible est attaquée ou affectée par un sort néfaste, ou bien si elle voit l''un de ses amis se faire ainsi molester. La cible redevient hostile dès que le sort se termine, à moins que le MD n''en décide autrement.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/calm_emotions_spell_bg3_wiki_guide_75px.png'
    ),
    (
        'Bouche magique',
        NULL,
        'Magic mouth',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 minute',
        '9 mètres',
        'V, S, M (un rayon de miel et de la poussière de jade d''une valeur de 10 po, que le sort consume)',
        'jusqu''à dissipation',
        'Vous implantez un message dans un objet situé à portée. On entend le message dès que les conditions le déclenchant sont remplies. Choisissez un objet situé dans votre champ de vision qui n''est ni porté ni transporté par une autre créature. Prononcez ensuite le message, qui doit se composer de 25 mots au maximum, mais peut se répéter pendant un maximum de 10 minutes. Enfin, déterminez les circonstances dans lesquelles Je message s''activera.' || E'\n' || 'Quand les conditions de déclenchement sont remplies, une bouche magique apparaît sur l''objet et récite le message avec la même voix que vous et au volume où vous l''avez prononcé. Si l''objet choisi possède une bouche ou quelque chose qui y ressemble (comme la bouche d''une statue), la bouche magique apparaît de manière à donner l''impression que les paroles sortent des lèvres de l''objet. Lors de l''incantation, vous pouvez décider que le sort se termine une fois le message transmis ou qu''il reste actif et répète le message chaque fois que les conditions de déclenchement sont remplies.' || E'\n' || 'Ces dernières peuvent être aussi génériques ou spécifiques que vous le désirez, mais elles doivent se baser sur des données visuelles ou audibles, perceptibles dans un rayon de 9 mètres autour de l''objet. Par exemple, vous pouvez ordonner à la bouche de parler dès qu''une créature approche à 9 mètres ou moins de l''objet ou quand une cloche d''argent retentit dans un rayon de 9 mètres.',
        NULL
    ),
    (
        'Chauffer le métal',
        'Métal brûlant',
        'Heat metal',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '18 mètres',
        'V, S, M (un bout de fer et une flamme)',
        'concentration, jusqu''à 1 minute',
        'Choisissez un objet manufacturé en métal, comme une arme métallique ou une armure métallique lourde ou intermédiaire. Il doit être situé à portée et dans votre champ de vision et se met alors à luire d''un rouge incandescent. Une créature en contact physique avec l''objet reçoit 2d8 dégâts de feu lorsque vous lancez le sort. Vous pouvez dépenser une action bonus à chacun de vos tours suivants jusqu''à la fin du sort pour infliger de nouveau ce montant de dégâts.' || E'\n' || 'Si une créature tient l''objet qui lui inflige des dégâts ou le porte sur elle, elle doit réussir un jet de sauvegarde de Constitution, sans quoi elle le lâche, si elle peut. Si elle le conserve, elle est désavantagée lors des jets d''attaque et des tests de caractéristique jusqu''au début de votre prochain tour.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/heat_metal_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Localiser des animaux ou des plantes',
        'Localisation d''animaux ou de plantes',
        'Locate animals or plants',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 action',
        'contact',
        'V, S, M (des poils de chien de chasse)',
        'instantanée',
        'Décrivez ou nommez un type spécifique de bête ou de plante. Vous vous concentrez sur la voix de la nature qui vous entoure et découvrez dans quelle direction et à quelle distance se trouve le spécimen le plus proche dans un rayon de 7,5 kilomètres,s''il y en a.',
        NULL
    ),
    (
        'Messager animal',
        NULL,
        'Animal messenger',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '9 mètres',
        'V,S,M (un peu de nourriture)',
        '24 heures',
        'Grâce à ce sort, vous chargez un animal de livrer un message pour vous. Choisissez une bête de taille Très Petite située à portée dans votre champ de vision, comme un écureuil ,un geai ou une chauve-souris. Vous lui précisez l''endroit où se rendre (où vous devez vous être déjà vous-même rendu auparavant) et donnez une description générale du destinataire, comme « un homme ou une femme vêtus de l''uniforme de la garde de la ville » ou « un nain roux avec un chapeau pointu ». Vous prononcez ensuite votre message, de vingt-cinq mots au maximum. La bête chargée du message fait alors route vers la destination indiquée pendant toute la durée du sort. Elle parcourt dans les 75 kilomètres par 24 heures si elle vole ou dans les 35 kilomètres si elle en est incapable.' || E'\n' || 'Quand elle arrive sur place, elle transmet votre message à la créature que vous avez décrite, imitant le son de votre voix. Le messager parle uniquement à une créature correspondant à la description que vous lui avez donnée. S''il n''atteint pas sa destination avant la fin du sort, le message est perdu et l''animal retourne là où vous avez lancé le sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, la durée du sort augmente de 48 heures par niveau au-delà du 2e.',
        NULL
    ),
    (
        'Silence',
        NULL,
        'Silence',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Pendant toute la durée du sort, aucun son ne peut se créer au sein d''une sphère de 6 mètres de rayon centrée sur un point de votre choix situé à portée, ni la traverser. Une créature ou un objet entièrement contenu dans la sphère sont immunisés contre les dégâts de tonnerre, et les créatures entièrement contenues dans la sphère sont sourdes. Il est impossible de lancer un sort à composante verbale dans la sphère.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/silence_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Arme spirituelle',
        NULL,
        'Spiritual weapon',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action bonus',
        '18 mètres',
        'V, S',
        '1 minute',
        'Vous créez à portée une arme spectrale flottante qui persiste pendant toute la durée du sort ou jusqu''à ce que vous le lanciez de nouveau. Lors de l''incantation, vous pouvez faire une attaque de sort au corps à corps contre une créature située dans un rayon de 1,50 mètre autour de l''arme. Si vous touchez, la cible reçoit un montant de dégâts de force égal à 1d8 + votre modificateur de caractéristique d''incantation.' || E'\n' || 'À votre tour et par une action bonus, vous pouvez déplacer l''arme d''un maximum de 6 mètres et répéter l''attaque contre une créature située dans un rayon de 1,50 mètre autour d''elle.' || E'\n' || 'L''arme peut revêtir la forme de votre choix. Les clercs des divinités associées àune arme particulière (comme St Cuthbert, connu pour sa masse ou Thor pour son marteau) font en sorte que l''arme générée ressemble à l''arme iconique de leur protecteur.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spiritual-weapon-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Augure',
        NULL,
        'Augury',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 minute',
        'personnelle',
        'V, S, M (bâtonnets, os ou petits objets similaires d''une valeur minimale de 25 po, portant des marques spéciales)',
        'instantanée',
        'Vous lancez des bâtonnets ornés de gemmes ou des os de dragon, tirez des cartes ornementées ou utilisez une autre méthode de divination pour recevoir un présage de la part d''une entité d''un autre monde. Ce présage concerne les résultats de la conduite que vous comptez tenir dans les trente prochaines minutes. C''est au MD de choisir l''un des présages suivants :' || E'\n' || '* _Bonheur_ pour un résultat positif' || E'\n' || '* _Malheur_ pour un résultat négatif' || E'\n' || '* _Bonheur_ et _malheur_ pour un résultat compor tant du positif et du négatif' || E'\n' || '* _Rien_ pour un résultat n''étant ni positif ni négatif' || E'\n' || 'Le sort ne tient pas compte d''une éventuelle modification des circonstances, comme l''incantation de sorts supplémentaires, ou la perte ou l''arrivée d''un compagnon.' || E'\n' || 'Si vous lancez ce sort à deux reprises ou plus avant un long repos, il y a 25% de chances par incantation en sus de la première que vous obteniez une prémonition aléatoire au lieu d''une prémonition fiable. C''est au MD de faire ce jet en secret.',
        NULL
    ),
    (
        'Doux repos',
        'Préservation des morts',
        'Gentle repose',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        'contact',
        'V, S, M (une pincée de sel et une pièce de cuivre à poser sur chaque œil du cadavre et qui doivent rester en place pendant toute la durée du sort)',
        '10 jours',
        'Vous touchez un cadavre ou assimilé. Pendant toute la durée du sort, la cible est protégée contre la décomposition et ne peut pas se transformer en mort-vivant.' || E'\n' || 'Le sort rallonge aussi la période pendant laquelle on peut rappeler la cible d''entre les morts, car les jours passés sous l''influence de ce sort ne sont pas décomptés de la période pendant laquelle on peut utiliser des sorts comme _relever les morts_.',
        NULL
    ),
    (
        'Flamme éternelle',
        NULL,
        'Continual flame',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        'contact',
        'V, S, M (poussière de rubis d''une valeur de 50 po, que le sort consume)',
        'jusqu''à disssipation',
        'Une flamme à la luminosité égale à celle d''une torche embrase soudain l''objet que vous touchez. L''effet du sort ressemble à une flamme ordinaire, mais ne dégage pas de chaleur et ne consomme pas d''oxygène. On peut couvrir ou cacher la _flamme éternelle_, mais pas l''étouffer ni l''éteindre avec de l''eau.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/flaming_sphere_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Lien de protection',
        NULL,
        'Warding bond',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        'contact',
        'V,S, M (une paire d''anneaux de platine valant chacun au moins 50 po, que la cible et vous devez porter pendant toute la durée)',
        '1 heure',
        'Ce sort protège une créature consentante et crée un lien mystique entre vous et votre cible jusqu''à la fin du sort. Tant que la cible se trouve dans un rayon de 18 mètres autour de vous, elle gagne un bonus de +1 à la CA et aux jets de sauvegarde et devient résistante à tous les types de dégâts. En revanche, chaque fois qu''elle subit des dégâts, vous subissez exactement les mêmes.' || E'\n' || 'Le sort se termine si vous tombez à 0 point de vie ou si votre cible et vous êtes séparés de plus de 18 mètres. Il se termine aussi si vous le lancez de nouveau sur l''une des deux créatures liées. Vous pouvez également révoquer le sort par une action.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wardingbond-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Prière de soins',
        'Prière de guérison',
        'Prayer of healing',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '10 minutes',
        '9 mètres',
        'V',
        'instantanée',
        'Un maximum de six créatures de votre choix, situées à portée et dans votre champ de vision, récupèrent chacune un montant de points de vie égal à 2d8 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les morts-vivants et les créatures artificielles.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les soins augmentent de 1d8 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/prayer_of_healing_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Trouver les pièges',
        'Detection des pièges',
        'Find traps',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 action',
        '36 mètres',
        'V, S',
        'instantanée',
        'Vous percevez la présence de tout piège se trouvant à portée et dans votre champ de vision. Concernant ce sort, le terme de piège désigne toute chose qui inflige soudainement ou de façon inattendue un effet considéré comme néfaste ou indésirable et que son créateur a conçue dans ce but. Ainsi, le sort prévient si une zone est affectée par une alarme, un _glyphe de garde_ ou une fosse piégée mécanique, mais il ne révèle pas une faiblesse naturelle dans un plancher, un plafond instable ou une doline cachée.' || E'\n' || 'Le sort indique simplement qu''il y a un piège ; il ne précise pas où, mais vous donne une idée générale de la nature du danger qu''il représente.',
        NULL
    ),
    (
        'Croissance d''épines',
        NULL,
        'Spike growth',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '45 mètres',
        'V, S, M (sept épines acérées ou sept brindilles taillées en pointe)',
        'concentration, jusqu''à 10 minutes',
        'Dans une zone de 6 mètres de rayon centrée sur un point à portée, le sol se met à se déformer et donne naissance à un tapis de pointes et d''épines. La zone se mue en terrain difficile pendant toute la durée du sort. Quand une créature entre dans la zone ou s''y déplace, elle reçoit 2d4 dégâts perforants par tranche de 1,50 mètre parcouru.' || E'\n' || 'La transformation du sol est camouflée, de manière à ce que le terrain ait l''air naturel. Une créature dans l''incapacité de voir la zone au moment de l''incantation doit faire un test de Sagesse (Perception) contre le DD du jet de sauvegarde de votre sort. Si elle le réussit, elle remarque que le terrain est dangereux avant d''y entrer.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spike_growth_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Lame de feu',
        NULL,
        'Flame blade',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V, S, M (feuille de sumac)',
        'concentration, jusqu''à 10 minutes',
        'Vous invoquez une lame enflammée dans votre main libre. Au niveau de la taille et de la forme, elle ressemble à un cimeterre et persiste pendant toute la durée du sort. Si vous la lâchez, elle disparaît, mais vous pouvez l''invoquer de nouveau par une action bonus.' || E'\n' || 'Vous pouvez utiliser votre action pour faire une attaque de sort au corps à corps avec la lame enflammée. Si vous touchez la cible, cette dernière subit 3d6 dégâts de feu.' || E'\n' || 'La lame enflammée émet une vive lumière dans un rayon de 3 mètres et une faible lumière dans un rayon de 3 mètres de plus.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, les dégâts augmentent de 1d6 tous les deux niveaux au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/flame_blade_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Passage sans trace',
        NULL,
        'Pass without trace',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle',
        'V, S, M (cendres d''une feuille de gui et une brindille d''épicéa)',
        'concentration, jusqu''à 1 heure',
        'Une aura d''ombre et de silence émane de vous et enveloppe vos compagnons, vous dissimulant aux sens d''autrui. Pendant toute la durée du sort, chaque créature que vous choisissez et qui se trouve dans un rayon de 9 mètres (vous y compris) bénéficie d''un bonus de +10 aux tests de Dextérité (Discrétion) et il devient impossible de suivre sa piste à moins de recourir à des méthodes magiques. Une créature qui profite de ce bonus ne laisse aucune trace ni autre indice de son passage derrière elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/pass_without_trace_spell_baldursgate3_wiki_guide_150px_.png'
    ),
    (
        'Peau d''écorce',
        NULL,
        'Barkskin',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une poignée d''écorce de chêne)',
        'concentration, jusqu''à 1 heure',
        'Vous touchez une créature consentante. Pendant toute la durée du sort, sa peau prend la consistance et l''apparence de l''écorce, et sa CA ne peut pas descendre au-dessous de 16, quelle que soit l''armure qu''elle porte.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/barkskin_spell_baldursgate3_wiki_guide_35px.png'
    ),
    (
        'Sens animal',
        NULL,
        'Beast sense',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'contact',
        'S',
        'concentration, jusqu''à 1 heure',
        'Vous touchez un animal consentant. Pendant toute la durée du sort, vous pouvez utiliser votre action pour voir par ses yeux et entendre par ses oreilles. Vous continuez de percevoir le monde ainsi jusqu''à ce que vous utilisiez votre action pour reprendre l''usage de vos propres sens. Tant que vous utilisez les sens de la créature, vous bénéficiez de ses éventuels sens spéciaux, mais vous êtes sourd et aveugle à tout ce qui se passe autour de vous.',
        NULL
    ),
    (
        'Sphère de feu',
        NULL,
        'Flaming sphere',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (un bout de suif, une pincée de soufre et un peu de poudre de fer)',
        'concentration, jusqu''à 1 minute',
        'Une sphère de feu de 1,50 mètre de diamètre apparaît dans un espace inoccupé de votre choix situé à portée et subsiste pendant toute la durée du sort. Chaque créature qui termine son tour dans un rayon de 1,50 mètre autour de la sphère doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 2d6 dégâts de feu, les autres la moitié seulement.' || E'\n' || 'Vous pouvez déplacer la sphère sur un maximum de 9 mètres par une action bonus. Si vous lui faites heurter une créature, cette dernière doit réussir un jet de sauvegarde contre les dégâts de la sphère qui arrête de se déplacer pour ce tour.' || E'\n' || 'Quand vous déplacez la sphère, vous pouvez lui faire franchir des obstacles de 1,50 mètre de haut et la faire sauter par-dessus des fosses de 3 mètres de large. Elle embrase les objets inflammables qui ne sont ni portés ni transportés. Elle émet une vive lumière dans un rayon de 6 mètres et une faible lu�ière dans un rayon de 6 mètres de plus.' || E'\n' || '**A plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/flaming_sphere_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Agrandir/rétrécir',
        'Agrandissement/rétrécissement',
        'Enlarge/reduce',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (une pincée de limaille de fer)',
        'concentration, jusqu''à 1 minute',
        'Vous agrandissez ou rétrécissez une créature ou un objet situé à portée et dans votre champ de vision pendant toute la durée du sort. Choisissez soit une créature, soit un objet qui n''est ni porté ni transporté. Si la cible n''est pas consentante, elle a droit à un jet de sauvegarde de Constitution. Si elle le réussit, le sort reste sans effet.' || E'\n' || 'Si la cible est une créature, tout ce qu''elle porte et tout ce qu''elle transporte change de taille avec elle. En revanche, si elle lâche un objet, il reprend sa taille normale sur-le-champ.' || E'\n' || '**Agrandir**: La cible double dans toutes les dimensions, et son poids est multiplié par huit. Cette croissance augmente sa catégorie de taille d''un cran, de Moyenne à Grande par exemple. Si la cible n''a pas assez de place pour doubler de volume, elle atteint la taille maximale possible dans l''espace dont elle dispose. Elle est avantagée lors des tests de Force et des jets de sauvegarde de Force jusqu''à la fin du sort. Les armes de la cible grandissent pour s''adapter à sa nouvelle taille. Tant qu''elles sont ainsi agrandies, elles infligent 1d4 dégâts de plus.' || E'\n' || '**Rétrécir**: La cible réduit de moitié dans toutes les dimensions et son poids est divisé par huit. Ce rétrécissement réduit sa catégorie de taille d''un cran, de Moyenne à Petite par exemple. La cible est désavantagée lors des tests de Force et des jets de sauvegarde de Force jusqu''à la fin du sort. Les armes de la cible rétrécissent pour s''adapter à sa nouvelle taille. Tant qu''elles sont ainsi réduites, elles infligent 1d4 dégâts de moins (mais cela ne peut pas faire passer les dégâts en dessous de 1).',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enlarge_reduce_spell_baldurs_gate3_wiki_guide_150px.png'
    ),
    (
        'Amélioration de caractéristique',
        NULL,
        'Enhance ability',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M des poils ou des plumes venant d''un animal)',
        'concentration, jusqu''à 1 heure',
        'Vous touchez une créature pour lui accorder une amélioration magique. Choisissez l''un des effets suivants dont la cible bénéficiera jusqu''à la fin du sort.' || E'\n' || '**Endurance de l''ours**: La cible est avantagée lors des tests de Constitution. Elle gagne aussi 2d6 points de vie temporaires qui disparaissent quand le sort se termine.' || E'\n' || '**Force du taureau**: La cible est avantagée lors des tests de Force et sa capacité de charge est doublée.' || E'\n' || '**Grâce du chat**: La cible est avantagée lors des tests de Dextérité. De plus, elle ne subit pas de dégâts quand elle chute sur 6 mètres ou moins, à condition qu''elle ne soit pas neutralisée.' || E'\n' || '**Splendeur de l''aigle**: La cible est avantagée lors des tests de Charisme.' || E'\n' || '**Ruse du renard**: La cible est avantagée lors des tests d''intelligence.' || E'\n' || '**Sagesse du hibou**: La cible est avantagée lors des tests de Sagesse.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez prendre une créature de plus pour cible par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enhance_ability_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Bourrasque',
        NULL,
        'Gust of wind',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (ligne de 18 mètres)',
        'V, S, M (une graine de légume)',
        'concentration, jusqu''à 1 minute',
        'Une zone de vent fort de 18 mètres de long sur 3 de large souffle depuis votre position dans la direction que vous avez choisie pendant toute la durée du sort. Chaque créature commençant son tour dans la zone doit réussir un jet de sauvegarde de Force, sans quoi elle est repoussée de 4,50 mètres à l''opposé de vous, dans la direction où souffle le vent.' || E'\n' || 'Une créature qui se trouve dans la zone doit dépenser 60 centimètres de mouvement pour se rapprocher de vous de 30 centimètres.' || E'\n' || 'La bourrasque disperse les gaz et les vapeurs et éteint les bougies, les torches et autres flammes nues similaires dans la zone. Les flammes protégées, par une lanterne par exemple, s''agitent follement et ont 50% de chance de s''éteindre.' || E'\n' || 'Vous pouvez changer la direction dans laquelle souffle la bourrasque par une action bonus à chacun de vos tours jusqu''à la fin du sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/gustofwind-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Fracassement',
        'Briser',
        'Shatter',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '18 mètres',
        'V, S, M (un éclat de mica)',
        'instantanée',
        'Un bruit retentit soudain avec une intensité douloureuse, à partir d''un point situé à portée. Chaque créature située dans une sphère de 3 mètres de rayon centrée sur ce point doit faire un jet de sauvegarde de Constitution. Les créatures qui le ratent subissent 3d8 dégâts de tonnerre, les autres la moitié seulement. Une créature faite de matière inorganique, comme de la pierre, du cristal ou du métal est désavantagée sur ce jet de sauvegarde.' || E'\n' || 'Un objet non magique que personne ne porte ni ne transporte subit aussi ces dégâts s''il se trouve dans la zone dun sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/shatter_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Cécité/surdité',
        NULL,
        'Blindness/Deafness',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        '9 mètres',
        'V',
        '1 minute',
        'Vous pouvez rendre un ennemi sourd ou aveugle. Choisissez une créature autre que vous qui se situe à portée et dans votre champ de vision. Elle doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle est soit aveugle, soit sourde (à vous de choisir) pendant toute la durée du sort. Elle a droit à un nouveau jet de sauvegarde de Constitution à la fin de chacun de ses tours, le sort se terminant si elle le réussit' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blindness_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Couronne du dément',
        NULL,
        'Crown of madness',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Choisissez un humanoïde situé à portée dans votre champ de vision. Il doit réussir un jet de sauvegarde de Sagesse, sans quoi vous le charmez pendant toute la durée du sort. Tant que la cible est sous votre charme, une couronne tordue en acier dentelé apparaît sur sa tête et une lueur démente brille dans son regard.' || E'\n' || 'À chacun de ses tours, avant de se déplacer, la cible doit utiliser son action pour porter une attaque armée contre une créature (autre qu''elle-même) que vous choisissez mentalement. Si vous ne choisissez pas de créature ou qu''il n''y en a pas à portée, la cible agit normalement.' || E'\n' || 'Lors de vos tours suivants, vous devez utiliser votre action pour garder le contrôle de la cible, sinon le sort se termine. La cible peut faire un jet de sauvegarde de Sagesse à la fin de chacun de ses tours. Si elle réussit, le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/crown_of_madness_enchantment_bg3_spell_wiki_guide64px.png'
    ),
    (
        'Déblocage',
        NULL,
        'Knock',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V',
        'instantanée',
        'Choisissez un objet situé à portée et dans votre champ de vision. Ce peut être une porte, une boîte, un coffre, des menottes, un cadenas ou un autre objet disposant d''un système de fermeture ordinaire ou magique.' || E'\n' || 'Une cible fermée par une serrure ordinaire, coincée ou bloquée par une barre se déverrouille ou se débloque. Si l''objet a plusieurs serrures, le sort en ouvre une seule.' || E'\n' || 'Si vous visez une cible fermée par un _verrou magique_, ce dernier est supprimé pendant 10 minutes, au cours desquelles on peut ouvrir et fermer la cible normalement.' || E'\n' || 'Quand vous lancez le sort, un cliquetis émane de l''objet et retentit si fort qu''on l''entend dans un rayon de 90 mètres.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/knock_spell_transmutation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Détection des pensées',
        NULL,
        'Detect thoughts',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S,M (une pièce de cuivre)',
        'concentration, jusqu''à 1 minute',
        'Pendant toute la durée du sort, vous parvenez à lire les pensées de certaines créatures. Quand vous lancez ce sort, puis en tant qu''action à votre tour jusqu''à la fin du sort, vous pouvez focaliser vos pensées sur une créature située dans votre champ de vision et dans un rayon de 9 mètres. Si elle dispose d''une Intelligence de 3 ou moins ou ne parle aucune langue, elle n''est pas affectée.' || E'\n' || 'Au départ, vous découvrez les pensées de surface de la créature, c''est-à-dire ce qu''elle a à i''esprit à ce moment-là. Par une action, vous pouvez tourner votre attention vers les pensées d''une autre créature ou tenter de vous enfoncer plus profondément dans l''esprit de celle que vous sondez actuellement. Dans ce cas, cette créature doit faire un jet de sauvegarde de Sagesse. Si elle échoue,vous avez un aperçu de son mode de raisonnement (le cas échéant), de son état émotionnel ou de ce qui occupe une place importante dans son esprit (par exemple quelque chose qui l''inquiète fortement, qu''elle aime, qu''elle déteste...). Si elle réussit, le sort se termine. Dans les deux cas,la cible sait que vous sondez son esprit et, à moins que vous ne tourniez votre attention vers une autre créature, votre cible peut utiliser son action à son tour pour faire un test d''Intelligence opposé au vôtre. Si elle réussit, le sort se termine.' || E'\n' || 'Les questions directement posées à l''oral à une cible orientent naturellement le cours de ses pensées,ce sort est donc particulièrement utile lors d''un interrogatoire.' || E'\n' || 'Vous pouvez aussi utiliser ce sort pour détecter la présence de créatures intelligentes que vous ne voyez pas. Vous pouvez chercher les pensées qui se trouvent dans un rayon de 9 mètres autour de vous au moment où vous lancez ce sort ou bien par une action tandis que le sort est actif. Le sort peut franchir des obstacles, mais il est arrêté par soixante centimètres de roche, 2,5 centimètres de métal autre que le plomb ou une mince feuille de plomb. Vous ne pouvez pas repérer les créatures dotées d''une Intelligence de 3 ou moins, ni celles qui ne parlent aucune langue.' || E'\n' || 'Une fois que vous avez ainsi détecté la présence d''une créature, vous pouvez lire ses pensées pendant le reste de la durée du sort, comme expliqué plus haut, même si vous ne la voyez pas, mais elle doit tout de même se trouver à portée.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/detect_toughts_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Flou',
        NULL,
        'Blur',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'personnelle',
        'V',
        'concentration, jusqu''à 1 minute',
        'Votre corps devient flou, il ondule et vacille comme une flamme aux yeux d''autrui. Pendant toute la durée du sort, les créatures sont désavantagées lorsqu''elles font un jet d''attaque contre vous. Un attaquant est immunisé contre cet effet s''il ne se repose pas sur sa vue, s''il dispose de vision aveugle par exemple, ou s''il peut percer les illusions à jour, avec vision parfaite.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blur_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Force fantasmagorique',
        NULL,
        'Phantasmal force',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        '18 mètres',
        'V, S, M (un peu de laine)',
        'concentration, jusqu''à 1 minute',
        'Vous façonnez une illusion et l''implantez dans l''esprit d''une créature située à portée dans votre champ de vision. Elle doit faire un jet de sauvegarde d''intelligence. Si elle échoue, vous créez un objet, une créature ou un phénomène visible fantasmagorique de votre choix. L''illusion doit tenir dans un cube de 3 mètres d''arête. La cible est seule à la percevoir, et ce pendant toute la durée du sort. Ce dernier ne fonctionne pas contre les morts-vivants ni les créatures artificielles.' || E'\n' || 'L''illusion comprend des bruits, une température et d''autres stimuli, mais, de même, la cible du sort est la seule à les percevoir.' || E'\n' || 'La cible peut utiliser une action pour examiner l''illusion avec un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort. Si elle réussit son test, elle comprend qu''elle a affaire à une simple illusion et le sort se termine.' || E'\n' || 'Tant que la cible est sous l''effet du sort, elle traite l''illusion comme un élément réel et invente une explication rationnelle aux résultats illogiques issus de ses interactions avec elle. Par exemple, si elle tente de traverser un pont fantasmagorique enjambant un ravin et tombe dès qu''elle pose le pied sur ce pont, si elle survit à la chute, elle croit toujours que le pont est réel et trouve une explication logique à sa chute : on l''a poussée, elle a glissé, une forte bourrasque l''a fait basculer...' || E'\n' || 'Une cible affectée croit si fort à la réalité de l''illusion que cette dernière peut même la blesser. Une illusion créée à l''image d''une créature peut attaquer la cible. De même, une illusion représentant du feu, un bassin d''acide ou une nappe de lave peut brûler la cible. À chaque round, à votre tour, votre illusion inflige 1d6 dégâts psychiques à la cible si elle se trouve au sein de l''illusion ou dans un rayon de 1,50 mètre autour d''elle et que cette illusion représente une créature ou un danger qui devrait logiquement la blesser, en l''attaquant par exemple. La cible perçoit les dégâts comme étant d''un type approprié à l''illusion qu''elle voit.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/phantasmal_force_spell_bg3_wiki_guide_75px.png'
    ),
    (
        'Image miroir',
        NULL,
        'Miror image',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'personnelle',
        'V, S',
        '1 minute',
        'Trois répliques illusoires de votre personne apparaissent dans votre emplacement. Jusqu''à la fin du sort, ces répliques se déplacent en même temps que vous et imitent toutes vos actions, changeant de position de manière à ce qu''il soit impossible de savoir quelles versions de vous sont des images et quelle version est réelle. Vous pouvez utiliser une action pour révoquer les répliques illusoires.' || E'\n' || 'Pendant toute la durée du sort, chaque fois qu''une créature vous prend pour cible d''une attaque, vous devez lancer 1d20 pour savoir si l''attaque touche votre personne ou l''un de vos doubles.' || E'\n' || 'Si vous avez trois répliques, vous devez obtenir 6 ou plus pour que l''attaque touche une réplique. Si vous n''en avez plus que deux, vous devez faire 8 ou plus et si vous n''en avez plus qu''une, vous devez faire 11 ou plus.' || E'\n' || 'Chaque réplique possède une CA de 10 + votre modificateur de Dextérité. Si l''attaque touche une réplique, elle la détruit. Le seul moyen de détruire une réplique est de la toucher avec une attaque, car elle ignore tous les autres effets et dégâts. Le sort se termine quand les trois répliques sont détruites.' || E'\n' || 'Une créature n''est pas affectée par ce sort si elle ne voit pas, si elle se sert d''un mode de perception autre que la vue (comme la vision aveugle) ou encore si elle perçoit les illusions comme telles avec vision parfaite, par exemple.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/mirror_image_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Immobiliser un humanoïde',
        'Immobilisation de personne',
        'Hold person',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, S, M (un petit morceau de fer bien droit)',
        'concentration, jusqu''à 1 minute',
        'Choisissez un humanoïde situé à portée et dans votre champ de vision. Il doit réussir un jet de sauvegarde de Sagesse, sans quoi il est paralysé pour toute la durée du sort. À la fin de chacun de ses tours, la cible a droit à un nouveau jet de sauvegarde de Sagesse. Si eUe le réussit, le sort se termine.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser un humanoïde de plus par niveau au-delà du 2e. Les humanoïdes visés doivent se trouver à 9 mètres ou moins les uns des autres au moment où vous lancez le sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hold_person_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Invisibilité',
        NULL,
        'Invisibility',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'contact',
        'V, S, M (un cil enrobé de gomme arabique)',
        'concentration, jusqu''à 1 heure',
        'La créature que vous touchez devient invisible jusqu''à la fin du sort. Tout ce qu''elle porte et transporte reste invisible tant qu''elle le garde sur elle. Le sort se termine pour la cible qui attaque ou lance un sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/invisivility_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Lévitation',
        NULL,
        'Levitate',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V, S, M (soit une petite boucle de cuir, soit un bout de fil de métal doré formant la silhouette d''une cuillère au long manche)',
        'concentration, jusqu''à 10 minutes',
        'Une créature ou un objet situé à portée et dans votre champ de vision s''élève à la verticale à une hauteur de 6 mètres et reste suspendu là pendant toute la durée du sort. Ce dernier peut soulever une cible d''au maximum 250 kilos. Si la créature visée n''est pas consentante, elle doit réussir un jet de sauvegarde de Constitution pour que le sort ne l''affecte pas.' || E'\n' || 'La cible peut se déplacer uniquement en se propulsant ou se tractant en prenant appui sur un objet fixe ou une surface à proximité (comme un mur ou un plafond). Elle se meut alors comme si elle était en pleine escalade. Quand vient votre tour, vous pouvez modifier l''altitude de la cible d''un maximum de 6 mètres dans la direction de votre choix. Si vous êtes la cible, vous pouvez monter ou descendre lors de votre déplacement. En dehors de cela, vous devez dépenser une action pour déplacer la cible qui doit rester dans le rayon de portée du sort. Si la cible est encore en l''air quand le sort se termine, elle flotte délicatement jusqu''au sol.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/telekinesis-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Modifier son apparence',
        'Modification d''apparence',
        'Alter self',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous revêtez une forme différente. Quand vous lancez ce sort, choisissez l''une des options suivantes, dont les effets dureront aussi longtemps que le sort. Tant qu''il est actif, vous pouvez utiliser une action pour mettre un terme à une option afin de bénéficier d''une autre.' || E'\n' || '**Adaptation aquatique**: Vous adaptez votre corps à un environnement aquatique, générant des branchies et des palmures entre vos doigts. Vous pouvez respirer sous l''eau et gagnez une vitesse de nage égale à votre vitesse de marche.' || E'\n' || '**Changer d''apparence**: Vous modifiez votre apparence et choisissez votre taille, votre poids, vos traits, le son de votre voix, la longueur de vos cheveux, votre pigmentation, et toute caractéristique distinctive désirée. Vous pouvez vous faire passer pour un membre d''une autre race, mais vos caractéristiques ne changent pas. Vous ne pouvez pas vous faire passer pour une créature d''une catégorie de taille différente de la vôtre, et votre silhouette générale doit rester la même (par exemple, si vous êtes un bipède, vous ne pouvez pas utiliser ce sort pour prendre l''apparence d''un quadrupède). À tout moment lors de la durée du sort, vous pouvez dépenser une action pour modifier de nouveau votre apparence de cette manière.' || E'\n' || '**Armes naturelles**: Vous gagnez des griffes, des crocs, des épines, des cornes ou une autre arme naturelle de votre choix. Vos attaques à mains nues infligent 1d6 dégâts contondants, perforants ou tranchants, comme il sied à l''arme naturelle que vous avez choisie et vous maîtrisez automatiquement les attaques à mains nues. Enfin, votre arme naturelle est de nature magique et vous disposez d''un bonus de +1 aux jets d''attaque et de dégâts quand vous l''utilisez.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/polymorph-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Nuée de dagues',
        NULL,
        'Cloud of daggers',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (un éclat de verre)',
        'concentration, jusqu''à 1 minute',
        'Vous emplissez de dagues tournoyantes un cube de 1,50 mètre d''arête. Ce cube est centré sur un point de votre choix situé à portée. Une créature subit 4d4 dégâts tranchants quand elle entre dans la zone du sort pour la première fois d''un tour ou quand elle y débute son tour.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 2d4 par emplacement de sort au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/cloud_of_daggers_spells_bg3_wiki_guide64px.png'
    ),
    (
        'Pattes d''araignée',
        NULL,
        'Spider climb',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une goutte de bitume et une araignée)',
        'concentration, jusqu''à 1 heure',
        'Jusqu''à la fin du sort, une créature consentante que vous touchez devient capable de se déplacer sur les surfaces verticales, et même au plafond la tête en bas, tout en gardant les mains libres. La cible bénéficie aussi d''une vitesse d''escalade égale à sa vitesse de marche.',
        NULL
    ),
    (
        'Rayon ardent',
        NULL,
        'Scorching ray',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '36 mètres',
        'V, S',
        'instantanée',
        'Vous créez trois rayons de feu et les projetez sur des cibles à portée. Vous pouvez les diriger contre une même cible ou contre des cibles différentes.' || E'\n' || 'Faites une attaque de sort à distance pour chaque rayon. Si vous touchez, la cible reçoit 2d6 dégâts.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous créez un rayon de plus par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/scorching_ray_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Suggestion',
        NULL,
        'Suggestion',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '9 mètres',
        'V, M (une langue de serpent et un rayon de miel ou une goutte d''huile d''olive)',
        'concentration, jusqu''à 8 heures',
        'Vous visez une créature située à portée dans votre champ de vision et à même de vous entendre et de vous comprendre. Vous l''influencez par magie de façon à ce qu''elle suive la conduite que vous lui proposez (en seulement une phrase ou deux). Les créatures insensibles au charme sont immunisées contre ce sort. Vous devez formuler votre suggestion de manière à ce que la conduite à tenir semble tout à fait raisonnable. Si vous demandez à une créature de se poignarder, de se laisser tomber sur une lance, de s''immoler ou d''accomplir n''importe quelle action à l''évidence néfaste, le sort se termine automatiquement.' || E'\n' || 'La cible doit faire un jet de sauvegarde de Sagesse. En cas d''échec, elle fait de son mieux pour suivre la conduite que vous lui avez suggérée et cela peut continuer pendant toute la durée du sort. Si l''activité suggérée peut se finir plus rapidement, le sort se termine quand la cible a accompli ce que vous lui avez demandé.' || E'\n' || 'Vous pouvez spécifier des conditions qui déclenchent une activité spéciale pendant la durée du sort. Par exemple, vous pouvez suggérer à un chevalier de donner son cheval de guerre au premier mendiant qu''il rencontre. Si les conditions ne sont pas remplies avant la fin du sort, la cible n''accomplit pas l''activité.' || E'\n' || 'Si vous (ou l''un de vos compagnons) blessez une créature affectée par ce sort, le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enthrall-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Ténèbres',
        NULL,
        'Darkness',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '18 mètres',
        'V, M (des poils de chauve-souris et une goutte de poix ou un bout de charbon)',
        'concentration, jusqu''à 10 minutes',
        'Des ténèbres magiques se répandent depuis un point de votre choix situé à portée, jusqu''englober une sphère de 4,50 mètres de rayon. Les ténèbres s''étendent en franchissant tout angle éventuel. La vision dans le noir d''une créature ne suffit pas à percer ces ténèbres et les lumières non magiques se révèlent incapables de les éclairer.' || E'\n' || 'Si le point que vous avez choisi est un objet en votre possession ou un objet qui n''est ni porté ni transporté par autrui, les ténèbres émanent de l''objet et se déplacent avec lui. Il suffit de recouvrir complètement l''objet affecté avec un objet opaque, comme un bol ou un heaume, pour bloquer les ténèbres.' || E'\n' || 'Si une partie de la zone affectée par ce sort chevauche une zone de lumière issue d''un sort de niveau 2 ou moins, elle dissipe le sort de lumière.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/darkness_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Toile d''araignée',
        NULL,
        'Web',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (un bout de toile d''araignée)',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez une masse de toiles d''araignées épaisses et collantes en un point de votre choix situé à portée. Pendant toute la durée du sort, les toiles occupent un cube de 6 mètres d''arête centré sur le point choisi. Elles forment un terrain difficile à la visibilité légèrement obstruée.' || E'\n' || 'Si les toiles ne sont pas ancrées entre deux éléments solides, comme des murs ou des arbres, ou disposées en couches sur le sol, le plafond ou un mur, elles s''effondrent sur elles-mêmes et le sort se termine au début de votre prochain tour. Des toiles disposées en couches superposées sur une surface plane s''accumulent sur une épaisseur de 1,50 mètre.' || E'\n' || 'Chaque créature qui commence son tour dans les toiles ou qui y pénètre lors de son tour doit faire un jet de sauvegarde de Dextérité. En cas d''échec, la créature est entravée tant qu''elle reste dans les toiles ou jusqu''à ce qu''elle se libère.' || E'\n' || 'Une créature entravée par les toiles peut utiliser son action pour faire un test de Force contre le DD du jet de sauvegarde de votre sort. Si elle le réussit, elle n''est plus entravée.' || E'\n' || 'Les toiles sont inflammables. Un cube de toiles de 1,50 mètre d''arête exposé au feu brûle en 1 round, infligeant 2d4 dégâts de feu à toute créature qui commence son tour dans les flammes.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/web_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Vision dans le noir',
        NULL,
        'Darkvision',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une pincée de carotte séchée ou une agate)',
        '8 heures',
        'Vous touchez une créature consentante pour lui permettre de voir dans le noir. Pendant toute la durée du sort, elle bénéficie de la vision dans le noir à une portée de 18 mètres.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/darkvision_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Voir l''invisible',
        'Détection de l''invisibilité',
        'See invisibility',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S, M (une pincée de talc et un saupoudrage de poudre d''argent)',
        '1 heure',
        'Pendant toute la durée du sort, vous voyez les créatures et les objets invisibles comme s''ils étaient bien visibles et vous pouvez aussi observer le plan éthéré. Les créatures et les objets éthérés vous apparaissent comme des silhouettes translucides ët fantomatiques.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/seeinvisibility_spell_divination_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Aura magique de Nystul',
        NULL,
        'Nystul''s magic aura',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        'contact',
        'V, S, M (un petit carré de soie)',
        '24 heures',
        'Vous enveloppez la créature ou l''objet touché d''une illusion, afin que les sorts de divination révèlent des informations erronées à son propos. La cible du sort doit être une créature consentante ou un objet qui n''est ni porté ni transporté par une autre créature.' || E'\n' || 'Lorsque vous lancez le sort, vous choisissez l''un des effets suivants, ou les deux, qui persistent pendant toute la durée du sort. Si vous lancez ce sort sur la même créature ou le même objet chaque jour pendant 30 jours,en lui attribuant le même effet à chaque fois, l''illusion persiste jusqu''à ce que quelqu''un la dissipe.' || E'\n' || '**Aura factice**: Vous modifiez la manière dont la cible apparaît vis-à-vis des sorts et effets magiques détectant les auras magiques, comme détection de la magie. Vous pouvez ainsi faire en sorte qu''un objet magique paraisse dépourvu de magie ou qu''un objet ordinaire semble magique, ou vous pouvez modifier l''aura magique de la cible de manière à ce qu''elle paraisse appartenir à l''école de magie de votre choix. Quand vous apposez cet effet sur un objet, vous pouvez faire en sorte que la magie factice se montre à toute personne qui manipule l''objet.' || E'\n' || '**Masque**: Vous modifiez la manière dont la cible apparaît aux sorts et effets magiques qui détectent les types de créatures, comme le sens divin d''un paladin ou le déclencheur d''un sort de symbole. Vous choisissez un type de créature : les autres sorts et effets magiques traitent la cible comme si elle appartenait au type ou à l''alignement choisi.',
        NULL
    ),
    (
        'Corde enchantée',
        NULL,
        'Rope trick',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'contact',
        'V, S, M (extrait de maïs en poudre et boucle de parchemin torsadé)',
        '1 heure',
        'Vous touchez une longueur de corde d''au maximum 18 mètres. L''une de ses extrémités s''élève alors dans les airs, jusqu''à ce que toute la corde se dresse perpendiculairement au sol. Une entrée invisible s''ouvre à l''extrémité supérieure de la corde et débouche sur un espace extradimensionnel qui persiste jusqu''à la fin du sort.' || E'\n' || 'On peut atteindre cet espace extradimensionnel en grimpant jusqu''au sommet de la corde. Il peut accueillir un maximum de huit créatures de taille Moyenne ou inférieure. On peut ensuite tirer la corde dans l''espace extradimensionnel, afin que personne ne la voie en dehors de l''abri.' || E'\n' || 'Les attaques et les sorts ne peuvent pas traverser l''entrée de l''espace extradimensionnel, ni depuis l''intérieur ni depuis l''extérieur. En revanche, les créatures qui se trouvent à l''intérieur peuvent regarder dehors grâce à une fenêtre de 90 centimètres sur 1,50 mètre centrée sur la corde.' || E'\n' || 'Tout ce qui se trouve dans l''espace extradimensionnel tombe à l''extérieur quand Je sort se termine.',
        NULL
    ),
    (
        'Flèche acide de Melf',
        NULL,
        'Melf''s acid arrow',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '27 mètres',
        'V, S, M ( poudre de feuille de rhubarbe et estomac de vipère)',
        'instantanée',
        'Une flèche d''un vert chatoyant file vers une cible située à portée et explose en une gerbe d''acide. Faites une attaque de sort à distance contre la cible. Si vous touchez, la cible reçoit 4d4 dégâts d''acide immédiatement et 2d4 dégâts d''acide à la fin de son prochain tour. Si vous ne touchez pas, l''acide éclabousse la cible et lui inflige la moitié des dégâts initiaux, mais aucun à la fin de son prochain tour.' || E'\n' || '**À plus haut niveau**: Quand vous utilisez ce sort via un emplacement de niveau 3 ou plus, les dégâts initiaux et secondaires augmentent de 1d4 par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/melft''s_acid_arrow_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Verrou magique',
        NULL,
        'Arcane lock',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action',
        'contact',
        'V, S, M (poussière d''or d''une valeur minimum de 25 po, que le sort consume)',
        'jusqu''à dissipation',
        'Vous touchez une ouverture fermée, comme une porte, une fenêtre, un portail, un coffre ou autre. Elle se verrouille alors pour toute la durée du sort. Vous et toutes les créatures désignées lors de l''incantation du sort pouvez ouvrir l''ouverture normalement. Vous pouvez aussi définir un mot de passe qui, une fois prononcé dans un rayon de 1,50 mètre autour de l''objet fermé, dissipe le sort pendant 1 minute. Sinon, impossible d''ouvrir l''objet à moins de le briser ou de dissiper ou supprimer le sort. Un sort de _déblocage_ supprime le _verrou magique_ pendant 10 minutes.' || E'\n' || 'Tant que l''objet est affecté par ce sort, il est bien plus difficile à briser ou à ouvrir de force: le DD pour le briser ou crocheter ses éventuelles serrures augmente de 10.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/arcanelock-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Aide',
        NULL,
        'Aid',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        '9 mètres',
        'V, S, M (une minuscule bandelette de tissu blanc)',
        '8 heures',
        'Le sort renforce vos alliés qui deviennent plus robustes et plus résolus. Choisissez jusqu''à trois créatures à portée. Le maximum de points de vie et les points de vie actuels de chacune d''entre elles augmentent de 5 pendant toute la durée du sort.' || E'\n' || '**À plus haut niveau**, quand vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les points de vie de chaque cible augmentent de 5 points supplémentaires pour chaque niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/aid_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Arme magique',
        NULL,
        'Magic weapon',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action bonus',
        'contact',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous touchez une arme non magique.Jusqu''à la fin du sort, elle devient magique et bénéficie d''un bonus de +1 aux jets d''attaque et de dégâts.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 4 ou plus, le bonus passe à +2, et à +3 si vous utilisez un emplacement de niveau 6 ou plus.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/magic_weapon_spell_transmutation_bg3_wik_64px.png'
    ),
    (
        'Frappe lumineuse',
        'Châtiment révélateur',
        'Branding smite',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration,jusqu''à 1 minute',
        'La prochaine attaque armée qui vous permet de toucher une créature avant la fin de ce sort voit votre arme briller d''une lumière astrale et inflige 2d6 dégâts radiants de plus à votre cible, qui devient visible si elle était invisible et émet une faible lumière dans un rayon de 1,50 mètrejusqu''à la fin du sort. Elle ne peut plus devenir invisible pendant toute cette durée.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts supplémentaires augmentent de 1d6 par emplacement de sort au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/branding_smite_melee_spell_evocation_bg3_wiki_64px.png'
    ),
    (
        'Localiser un objet',
        'Localisation d''objet',
        'Locate object',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S, M (une branche fourchue)',
        'concentration,jusqu''à 10 minutes',
        'Décrivez ou nommez un objet qui vous est familier. Vous sentez dans quelle direction il se trouve, à condition qu''il soit dans un rayon de 300 mètres. S''il se déplace, vous savez dans quelle direction.' || E'\n' || 'Le sort permet de localiser un objet spécifique de votre connaissance à condition que vous l''ayez vu de près, c''est-à-dire vous être trouvé à 9 mètres ou moins au moins de lui une fois dans votre vie. Sinon, le sort peut localiser l''objet d''un type donné le plus proche, comme un type d''appareil, de bijou, de meuble, d''outil ou d''arme.' || E'\n' || 'Le sort ne parvient pas à localiser l''objet si une couche de plomb, aussi mince soit-elle, bloque une trajectoire directe entre vous et l''objet.',
        NULL
    ),
    (
        'Protection contre le poison',
        'Protection from poison',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S',
        '1 heure',
        'Vous touchez une créature. Si elle est empoisonnée, vous neutralisez ce poison. Si elle est victime de plusieurs poisons, vous en neutralisez un dont vous avez détecté la présence ou un au hasard.' || E'\n' || 'Pendant toute la durée du sort, la cible est avantagée lors des jets de sauvegarde contre le poison et se montre résistante aux dégâts de poison.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/protection_from_poison_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Restauration inférieure',
        'Restauration partielle',
        'Lesser restoration',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S',
        'instantanée',
        'Vous touchez une créature et mettez fin à une maladie ou à un état qui l''affectait, cet état étant aveugle, sourd, paralysé ou empoisonné.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/lesser_restoration_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Trouver une monture',
        'Appel de destrier',
        'Find steed',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '10 minutes',
        '9 mètres',
        'V, S',
        'instantanée',
        'Vous invoquez un esprit qui prend la forme d''une monture dotée d''une intelligence, d''une puissance et d''une loyauté hors du commun, et créez un lien durable avec lui. La monture apparaît dans un emplacement inoccupé à portée et prend l''apparence de votre choix : un cheval de guerre, un poney, un chameau, un élan, ou un mastiff. (Votre MD peut autoriser d''autres formes animales.) La monture possède les statistiques de la forme choisie, mais au lieu d''être de type normal, elle est céleste, féerique ou fiélone (à vous de choisir). De plus, si elle a d''ordinaire une Intelligence de 5 ou moins, cette caractéristique passe à 6 et elle comprend um langage de votre choix que vous maîtrisez.' || E'\n' || 'Vous pouvez chevaucher votre monture au combat ou en dehors des affrontements, et le lien instinctif que vous partagez avec elle vous permet de vous battre ensemble comme si vous étiez une seule et même entité. Tant que vous la chevauchez, les sorts qui vous visent exclusivement l''affectent aussi si vous le désirez.' || E'\n' || 'Quand la monture tombe à O point de vie, elle disparaît sans laisser de cadavre physique. Vous pouvez la renvoyer quand vous le désirez par une action qui la fait disparaître. Si vous lancez de nouveau ce sort, c''est la même monture qui apparaît, disposant à nouveau de tous ses points de vie.' || E'\n' || 'Vous pouvez communiquer par télépathie avec votre monture tant qu''elle se trouve dans un rayon de 1,5 kilomètre.' || E'\n' || 'Vous ne pouvez vous lier qu''à une seule monture issue de ce sort à la fois. Vous pouvez libérer la monture du lien quand vous le désirez, par une action qui la fait disparaître.',
        NULL
    ),
    (
        'Zone de vérité',
        NULL,
        'Zone of truth',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, S',
        '10 minutes',
        'Vous créez une zone magique, capable de protéger contre la duplicité, sous forme d''une sphère de 4,50 mètres de rayon centrée sur un point de votre choix situé à portée. Jusqu''à la fin du sort, une créature qui pénètre dans la sphère pour la première fois de son tour ou y commence son tour doit réussir un jet de sauvegarde de Charisme. Si elle échoue, elle ne peut pas mentir délibérément tant qu''elle reste dans la zone du sort. Vous savez si chaque créature présente a réussi ou raté son jet de sauvegarde.' || E'\n' || 'Une créature affectée est consciente du sort qui la limite et peut donc soigneusement éviter de répondre aux questions qui susciteraient normalement un mensonge de sa part. Une telle créature peut rester évasive dans ses réponses, tant qu''elle reste dans les limites de la vérité.',
        NULL
    ),
    (
        'Cordon de flèches',
        NULL,
        'Cordon of arrows',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '1,5 mètres',
        'V, S, M (quatre flèches ou carreaux ou plus)',
        '8 heures',
        'Vous fichez quatre projectiles (flèches ou carreaux) non magiques en terre, à portée, et les imprégnez de magie afin de protéger une zone. Jusqu''à la fin du sort, dès qu''une créature autre que vous approche dans un rayon de 9 mètres autour des projectiles pour la première fois de son tour ou finit son tour à un tel endroit, une munition s''envole pour la frapper. La créature doit réussir un jet de sauvegarde de Dextérité, sans quoi elle subit 1d6 dégâts perforants. Le projectile est ensuite détruit. Le sort se termine s''il ne reste plus de projectiles.' || E'\n' || 'Au moment de l''incantation,vous pouvez désigner plusieurs créatures de votre choix que le sort ignorera.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez enchanter deux projectiles de plus par niveau au-delà du 2e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spell_conjuration_hailofthorns_baldurs_gate_3_wiki_guide_65px.png'
    ),
    (
        'Envoûtement',
        'Discours captivant',
        'Enthrall',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, S',
        '1 minute',
        'Vous entonnez une suite de paroles envoûtantes qui obligent les créatures de votre choix qui vous entendent et sont situées à portée et dans votre champ de vision à faire un jet de sauvegarde de Sagesse. Une créature qui ne peut pas être charmée réussit automatiquement ce jet de sauvegarde. Si vous ou vos compagnons vous battez contre une de ces créatures, elle est avantagée lors du jet de sauvegarde. Si la créature rate son jet, elle est désavantagée lors des tests de Sagesse (Perception) destinés à percevoir une créature autre que vous jusqu''à ce que le sort se termine ou jusqu''à ce qu''elle ne puisse plus vous entendre. Le sort se termine si vous êtes neutralisé ou dans l''incapacité de parler.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enthrall-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Rayon affaiblissant',
        NULL,
        'Ray of Enfeeblement',
        2,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Un rayon noir fait d''énergie débilitante jaillit de votre doigt en direction d''une créature à portée. Faites une attaque de sort à distance contre la cible. Si vous la touchez, la créature inflige seulement la moitié des dégâts habituels lorsqu''elle attaque avec une arme basée sur la Force.' || E'\n' || 'La cible a droit à un jet de sauvegarde de Constitution contre le sort à la fin de chacun de ses tours. Le sort se termine si elle réussit.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/ray_of_enfeeblement_spell_baldursgate3_wiki_guide_150px_2.png'
    );