INSERT INTO sort (nom_sort,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Amitié avec les animaux',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '9 mètres',
        'V, S, M (un peu de nourriture)',
        '24 heures',
        'Grâce à ce sort, vous convainquez une bête que vous ne lui voulez pas de mal. Choisissez une bête située à portée dans votre champ de vision. Elle doit vous voir et vous entendre. Le sort échoue si elle possède une Intelligence de 4 ou plus. Dans le cas contraire, elle doit réussir unjet de Sagesse, sans quoi vous la charmez pendant toute la durée du sort. Le sort se termine si vous ou l''un de vos camarades blessez la cible.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez affecter une bête supplémentaire par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/animal_friendship_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Fou rire de Tasha',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '9 mètres',
        'V, S, M (de minuscules tartes et une plume à agiter dans les airs)',
        'concentration, jusqu''à 1 minute',
        'Une créature de votre choix située à portée dans votre champ de vision trouve soudain tout ce qui l''entoure d''une drôlerie hilarante et succombe à un fou rire irrépressible dès que ce sort l''affecte. Elle doit réussir un jet de sauvegarde de Sagesse ou se retrouver à terre, neutralisée et incapable de se relever pendant toute la durée du sort. Ce sort n''affecte pas les créatures dotées d''une Intelligence de 4 ou moins.' || E'\n' || 'À la fin de chacun de ses tours et chaque fois qu''elle subit des dégâts, la cible a droit à un nouveau jet de sauvegarde de Sagesse. Elle est avantagée lors de ce jet si ce sont des dégâts qui l''ont provoqué. Si la cible le réussit, le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/tasha''s_hideous_laughter_spell_baldursgate3_wiki_guide_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Grande foulée',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une pincée de poussière)',
        '1 heure',
        'Vous touchez une créature dont la vitesse augmente de 3 mètres jusqu''à la fin du sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez affecter une créature de plus par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/longstrider_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Identification',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 minute',
        'contact',
        'V, S, M (une perle d''une valeur minimale de 100 po et une plume de hibou)',
        'instantanée',
        'Vous choisissez un objet avec lequel vous devez rester en contact pendant toute l''incantation du sort. Si c''est un objet magique ou un objet imprégné de magie,vous apprenez immédiatement quelles sont ses propriétés et comment vous en servir. Vous savez aussi s''il faut s''harmoniser avec lui pour l''utiliser et combien de charges il possède, le cas échéant. Vous savez si des sorts affectent l''objet et quel est leur nom. Si l''objet a été créé grâce à un sort, vous apprenez quel sort lui a dqnné naissance.' || E'\n' || 'Si,à la place,vous touchez une créature pendant toute l''incantation, vous découvrez quels sorts l''affectent présentement,le cas échéant.',
        NULL
    ),
    (
        'Lueurs féeriques',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '18 mètres',
        'V',
        'concentration, jusqu''à 1 minute',
        'Tous les objets contenus dans un cube de 6 mètres d''arête situé à portée sont auréolés d''une lumière bleue, verte ou violette (à vous de choisir). Les créatures qui se trouvent dans la zone au moment de l''incantation sont aussi entourées de lumière, à moins de réussir un jet de sauvegarde de Dextérité. Pendant toute la durée du sort, les créatures et les objets affectés émettent une faible luminosité dans un rayon de 3 mètres.' || E'\n' || 'Un assaillant a l''avantage lors du jet d''attaque contre une cible affectée s''il peut la voir. Les créatures et les objets affectés ne peuvent pas bénéficier des effets de l''invisibilité.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/faerie_fire_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Mot de guérison',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action bonus',
        '18 mètres',
        'V',
        'instantanée',
        'Une créature de votre choix située à portée dans votre champ de vision récupère un montant de points de vie égal à 1d4 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les créatures artificielles et les morts-vivants.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les soins augmentent de 1d4 par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/healing_word_spell_icon_baldursgate3_wiki_guide_200px.png'
    ),
    (
        'Murmures dissonants',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '18 mètres',
        'V',
        'instantanée',
        'Vous fredonnez une mélodie discordante qu''entend une seule créature de votre choix, située à portée. La malheureuse est alors victime de terribles douleurs et doit faire unjet de sauvegarde de Sagesse. Si elle échoue, elle subit 3d6 dégâts psyclùques et doit immédiatement dépenser sa réaction (si elle le peut) pour s''éloigner de vous autant que sa vitesse de déplacement le lui permet. Elle ne s''avance pas dans des zones à l''évidence dangereuses, comme un brasier ou une fosse. Si la cible réussit son jet de sauvegarde, elle subit seulement la moitié des dégâts et n''a pas à s''éloigner. Une créature assourdie réussit automatiquement sonjet de sauvegarde.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d6 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dissonant_whispers_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Balisage',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '36 mètres',
        'V, S',
        '1 round',
        'Un rayon de lumière frappe une créature de votre choix située à portée. Faites un jet d''attaque de sort à distance contre elle. Si vous touchez, elle subit 4d6 dégâts radiants et scintille d''une faible lumière mystique jusqu''à la fin de votre prochain tour. D''ici là et grâce à cette lueur, le prochain jet d''attaque effectué contre elle est avantagé.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/guiding_bolt_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Blessure',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        'contact',
        'V, S',
        'instantanée',
        'Faites une attaque de sort au corps à corps contre une créature située à une distance inférieure ou égale à votre allonge. Si vous la touchez, elle subit 3d10 dégâts nécrotiques.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d1O par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/inflict_wounds_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Création ou destruction d''eau',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '9 mètres',
        'V, S, M (une goutte d''eau pour créer de l''eau ou quelques grains de sable pour en détruire)',
        'instantanée',
        'Vous créez ou détruisez de l''eau.' || E'\n' || '**Création d''eau**: Vous créez jusqu''à 40 litres d''eau potable qui apparaissent à portée, dans un récipient ouvert.' || E'\n' || 'Sinon, l''eau peut tomber en pluie dans un cube de 9 mètres d''arête à portée, éteignant toutes les flammes à nu dans la zone.' || E'\n' || '**Destruction d''eau**: Vous détruisez jusqu''à 40 litres d''eau situés à portée dans un récipient ouvert.' || E'\n' || 'Sinon, vous pouvez détruire le brouillard dans un cube de 9 mètres d''arête situé à portée.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous créez ou détruisez 40 litres d''eau de plus par niveau au-delà du 1er ou bien l''arête du cube affecté augmente de 1,50 mètre par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/create_water_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Sanctuaire',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action bonus',
        '9 mètres',
        'V, S, M (un petit miroir en argent)',
        '1 minute',
        'Vous protégez une créature à portée contre les attaques. Jusqu''à la fin du sort, toute créature qui vise la cible avec une attaque ou un sort néfaste doit d''abord faire un jet de sauvegarde. Si elle le rate, elle doit choisir une nouvelle cible, sans quoi l''attaque ou le sort est perdu. Ce sort ne protège pas la cible contre les effets de zone, comme l''explosion d''une boule de feu.' || E'\n' || 'Ce sort se termine si la créature protégée attaque ou lance un sort affectant une créature ennemie.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/sanctuary_spell_abjuration_bg3_wiki_64px.png'
    ),
    (
        'Baies nourricières',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (un brin de gui)',
        'instantanée',
        'Jusqu''à dix baies apparaissent dans votre main. Elles sont imprégnées de magie pendant une journée. Une créature peut utiliser son action pour manger une baie, ce qui lui rend un point de vie et la nourrit pour la journée.' || E'\n' || 'Les baies perdent leurs propriétés si personne ne les mange dans les 24 heures qui suivent l''incantation.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/goodberry_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Enchevêtrement',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '27 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Des herbes et des lianes entremêlées jaillissent du sol dans un carré de 6 mètres de côté centré sur un point à portée. Pendant toute la durée du sort, les végétaux transforment la zone en terrain difficile.' || E'\n' || 'Une créature qui se trouve dans la zone affectée lorsque vous lancez le sort doit réussir un jet de sauvegarde de Force, sans quoi elle reste entravée dans les plantes jusqu''à ce que le sort se termine. Une créature entravée peut utiliser une action pour faire un test de Force contre le DD du sort. Si elle réussit, elle se libère.' || E'\n' || 'Quand le sort se termine, les plantes invoquées se flétrissent.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/entangle_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Armure du mage',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S, M (un bout de cuir tanné)',
        '8 heures',
        'Vous touchez une créature consentante qui ne porte pas d''armure et l''enveloppez d''une force magique protectrice jusqu''à la fin du sort. La CA de base de la cible passe à 13 + son modificateur de Dextérité. Le sort se termine si la cible revêt une armure ou si vous révoquez le sort par une action.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/mage_armour_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Bouclier',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 réaction à effectuer lorsque vous êtes touché par une attaque ou un sort de projectile magique',
        'personnelle',
        'V, S',
        '1 round',
        'Une barrière invisible faite de force magique apparaît autour de vous et vous protège. Jusqu''au début de votre prochain tour, vous avez un bonus de +5 à la CA, y compris contre l''attaque qui a déclenché l''incantation du sort, et vous ne subissez aucun dégât de la part de projectile magique.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/shield-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Carreau ensorcelé',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '9 mètres',
        'V, S, M (une brindille issue d''un arbre frappé par la foudre)',
        'concentration, jusqu''à 1 minute',
        'Un éclair d''énergie bleutée frappe une cible à portée et forme un arc électrique persistant entre elle et vous. Faites une attaque de sort à distance contre cette créature. Si vous touchez, elle subit 1d12 dégâts de foudre et, à chacun de vos tours pendant toute la durée du sort, vous pouvez utiliser votre action pour lui infliger automatiquement 1d12 dégâts de foudre. Le sort se termine si vous utilisez votre action pour faire autre chose. Il se termine également si la cible passe hors de portée du sort ou bénéficie d''un abri total contre vous.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts initiaux augmentent de 1d12 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/witch_bolt_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Charme-personne',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '9 mètres',
        'V, S',
        '1 heure',
        'Vous tentez de charmer un humanoïde se trouvant à portée et dans votre champ de vision. Il doit faire un jet de sauvegarde de Sagesse, pour lequel il est avantagé si vous ou vos compagnons êtes actuellement en train de le combattre. S''il rate son test, vous le charmez jusqu''à la fin du sort ou jusqu''à ce que vous ou vos compagnons lui fassiez du mal. La créature charmée vous considère comme un ami. Quand le sort se termine, elle sait que vous l''avez charmée.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez charmer une créature de plus par niveau au-delà du 1er. Toutes les cibles doivent se trouver à 9 mètres ou moins les unes des autres lorsque vous lancez le sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/charm_person_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Compréhension des langues',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S, M (une pincée de suie et de sel)',
        '1 heure',
        'Pendant toute la durée du sort, vous comprenez le sens littéral de tout langage parlé que vous entendez. Vous comprenez aussi les langues écrites que vous voyez, à condition de toucher la surface sur laquelle on a tracé les mots. Il vous faut 1 minute pour lire une page de texte.' || E'\n' || 'Ce sort ne décode pas les messages secrets compris dans un texte ni les glyphes qui n''appartiennent pas à un langage écrit, comme un symbole magique.',
        NULL
    ),
    (
        'Couleurs dansantes',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'personnelle (cône de 4,50 mètres)',
        'V, S, M (une poignée de poudre ou de sable, colorée en rouge, jaune et bleu)',
        '1 round',
        'Un éventail de lumières colorées éblouissantes jaillit de votre main. Lancez 6d10. Le total représente le nombre de points de vie de créatures que le sort affecte. Les créatures situées dans un cône de 4,50 mètres, prenant votre personne comme point d''origine, sont affectées dans l''ordre croissant de leurs points de vie actuels (en ignorant les créatures inconscientes et les créatures aveugles).' || E'\n' || 'Chaque créature affectée, en commençant par celle qui possède actuellement le moins de points de vie, est aveuglée jusqu''à la fin du sort. Soustrayez du total obtenu le nombre de points de vie actuel de chaque créature affectée avant de passer à la suivante, en choisissant chaque fois celle qui possède le moins de points de vie. Pour qu''une créature soit affectée, elle doit posséder un nombre de points de vie actuel inférieur ou égal au total restant.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, lancez 2d10 supplémentaires par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/colour_spray_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Déguisement',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'personnelle',
        'V, S',
        '1 heure',
        'Vous faites en sorte que votre personne (y compris vos vêtements, votre armure, vos armes et les autres objets en votre possession) prenne une apparence différente jusqu''à la fin du sort ou jusqu''à ce que vous utilisiez une action pour y mettre un terme. Vous pouvez passer pour une personne de trente centimètres de plus ou de moins, sembler gros, maigre ou entre les deux. Vous ne pouvez pas changer le type de votre corps, vous devez choisir une forme possédant la même conformation que vous au niveau des membres. En dehors de cela, les détails de l''illusion sont laissés à votre imagination.' || E'\n' || 'Les changements qu''apporte le sort ne résistent pas à un examen physique. Par exemple, si vous l''utilisez pour ajouter un chapeau à votre tenue, les objets passent au travers et toute personne qui essaie de le toucher ne sentira que de l''air, ou des cheveux et un crâne. Si vous utilisez le sort pour paraître plus mince qu''en réalité, la main de quelqu''un qui tente de vous toucher se heurtera à vous alors que, visuellement, elle semble encore dans le vide.' || E'\n' || 'Pour percer votre déguisement à jour, une créature peut dépenser une action pour vous examiner. Elle doit alors réussir un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde du sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/desguise_self_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Image silencieuse',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        '18 mètres',
        'V, S, M (un morceau de toison)',
        'concentration, jusqu''à 10 minutes',
        'Vous créez l''image d''un objet, d''une créature ou d''un phénomène visible tenant dans un cube de 4,50 mètres de côté. L''image apparaît en un point situé à portée et persiste pendant toute la durée du sort. L''image comporte seulement des composantes visuelles, elle ne s''accompagne pas d''odeurs, de sons, ni d''autres effets sensoriels.' || E'\n' || 'Vous pouvez utiliser votre action pour déplacer l''image vers un autre point à portée. Pendant qu''elle se déplace, vous pouvez modifier son apparence pour donner l''impression d''un mouvement naturel. Par exemple, si vous créez l''image d''une créature et que vous la déplacez, vous pouvez modifier l''image pour donner l''impression que la créature est en train de marcher.' || E'\n' || 'Les interactions physiques révèlent que l''image n''est qu''une illusion, car les objets la traversent. Si une créature utilise son action pour examiner l''image, elle comprend que c''est une illusion à condition de réussir un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort. Si une créature perce l''illusion à jour, elle voit à travers l''image.',
        NULL
    ),
    (
        'Léger comme une plume',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 réaction, que vous effectuez quand vous-même ou une créature située dans un rayon de 18 mètres tombe soudain',
        '18 mètres',
        'V, M (une petite plume ou un peu de duvet)',
        '1 minute',
        'Choisissez jusqu''à cinq créatures en train de tomber à portée. La vitesse de chute de chacune passe à 18 mètres par round jusqu''à la fin du sort. Si une créature atterrit avant la fin du sort, elle ne subit pas de dégâts de chute et se reçoit sur ses pieds, le sort se terminant alors pour elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/feather_fall_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Mains brûlantes',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'contact (cône de 4,50 mètres)',
        'V, S',
        'instantanée',
        'Alors que vous vous tenez les doigts écartés en éventail et les pouces l''un contre l''autre, une mince nappe de feu s''étend depuis vos mains tendues. Chaque créature située dans un cône de 4,50 mètres doit faire un jet de sauvegarde de Dextérité. Celles qui échouent reçoivent 3d6 dégâts de feu, les autres la moitié seulement.' || E'\n' || 'Le feu embrase tous les objets inflammables de la zone, à moins que quelqu''un ne les porte ou ne les transporte.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/burning_hands_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Nappe de brouillard',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous créez une sphère de brouillard de 6 mètres de rayon centrée sur un point à portée. La sphère s''étend en contournant les angles et, dans la zone qu''elle occupe, la visibilité est fortement obstruée. Le brouillard persiste pendant toute la durée du sort ou jusqu''à ce qu''un vent modéré ou plus violent (soufflant au moins à 15 kilomètres/heure) le disperse.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, le rayon de la sphère augmente de 6 mètres par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fog_cloud_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Orbe chromatique',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '27 mètres',
        'V, S, M (un diamant d''une valeur minimale de 50 po)',
        'instantanée',
        'Vous lancez une sphère d''énergie de 10 centimètres de diamètre sur une créature située à portée dans votre champ de vision. Cet orbe est fait d''acide, de feu, de froid, de foudre, de poison ou de tonnerre (à vous de choisir). Vous effectuez ensuite un jet d''attaque à distance contre votre cible. Si vous la touchez, elle subit 3d8 dégâts du type de l''orbe.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d8 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/chromatic_orb_spell_icon_baldurs_gate3_wiki_guide_64px.png'
    ),
    (
        'Projectile magique',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '36 mètres',
        'V, S',
        'instantanée',
        'Vous créez trois fléchettes faites d''énergie magique luisante. Chacune touche une créature de votre choix, située à portée dans votre champ de vision. Une fléchette inflige 1d4+1 dégâts de force à la cible. Toutes les fléchettes frappent leur cible en même temps, sachant que vous pouvez toutes les diriger contre une seule et même créature ou les répartir entre plusieurs.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, le sort crée une fléchette de plus par niveau au-delà du 1er·',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/magic_missile_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Rayon empoisonné',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        '18 mètres',
        'V, S',
        'instantanée',
        'Un rayon d''énergie d''un vert maladif frappe une créature à portée. Faites un jet d''attaque de sort à distance contre elle. Si vous la touchez, elle subit 2d8 dégâts de poison et doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle est empoisonnée jusqu''à la fin de votre prochain tour.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d8 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/ray_of_sickness_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Repli expéditif',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action bonus',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Ce sort vous permet de vous déplacer à une vitesse incroyable. Vous pouvez utiliser l''action "se précipiter"  (+9 mètres) quand vous le lancez, puis par une action bonus à chacun de vos tours jusqu''à ce qu''il se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/expeditious_retreat_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Saut',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        'contact',
        'V, S, M (une patte arrière de sauterelle)',
        '1 minute',
        'Vous touchez une créature et triplez sa distance de saut jusqu''à ce que Je sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/jump_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Simulacre de vie',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        'personnelle',
        'V, S, M (une petite quantité d''alcool ou de spiritueux)',
        '1 heure',
        'Vous renforcez votre corps avec un ersatz de vie et gagnez 1d4+4 points de vie temporaires pendant la durée du sort.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous gagnez 5 points de vie temporaires de plus par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/false_life_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Sommeil',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '27 mètres',
        'V, S, M (une pincée de sable fin, des pétales de rose ou un criquet)',
        '1 minute',
        'Ce sort plonge quelques créatures dans un sommeil magique. Lancez 5d8. Le total indique le nombre de points de vie de créatures que le sort affecte. Les créatures se trouvant dans un rayon de 6 mètres autour d''un point de votre choix situé à portée sont affectées dans l''ordre croissant de leur montant de points de vie actuel (en ignorant les créatures inconscientes).' || E'\n' || 'Chaque créature affectée par le sort tombe inconsciente, en commençant par celle qui possède actuellement le moins de vie. Elle reste ainsi jusqu''à la fin de la durée du sort, jusqu''à ce qu''elle subisse des dégâts ou jusqu''à ce que quelqu''un utilise son action pour la réveiller en la secouant ou en la giflant.' || E'\n' || 'Soustrayez le nombre de points de vie de la créature endormie du total auquel vous avez droit avant de passer à la suivante, c''est-à-dire celle qui a le moins de points de vie après elle. Le nombre de points de vie de la créature doit être égal ou inférieur au total vous restant, sinon le sort n''affecte pas la créature.' || E'\n' || 'Ce sort reste sans effet sur les morts-vivants et les créatures insensibles aux effets de charme.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, lancez 2d8 de plus par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/sleep_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Vague tonnante',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (cube de 4,50 mètres)',
        'V, S',
        'instantanée',
        'Une vague de force tonnante émane de vous. Chaque créature située dans un cube de 4,50 mètres d''arête partant de vous doit faire un jet de sauvegarde de Constitution. Les créatures qui échouent subissent 2d8 dégâts de tonnerre et sont repoussées de 3 mètres en face de vous. Les autres subissent seulement la moitié des dégâts et ne sont pas repoussées.' || E'\n' || 'De plus, les objets qui ne sont pas arrimés et se trouvent entièrement englobés dans la zone affectée sont automatiquement repoussés de 3 mètres à l''opposé de vous. Le sort émet un grondement de tonnerre qui s''entend dans un rayon de 90 mètres.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/thunderwave_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Appel de familier',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 heure',
        '3 mètres',
        'V, S, M (10 po de charbon, d''encens et d''herbes à faire brûler dans un brasero en laiton)',
        'instantanée',
        'Vous vous attachez les services d''un familier, un esprit qui prend la forme d''un animal de votre choix : une chauve-souris, un chat, un crabe, une grenouille (ou un crapaud), un faucon, un lézard, une pieuvre, une chouette, un serpent venimeux, un poisson (un piranha), un rat, un corbeau, un hippocampe, une araignée ou une belette. Le familier apparaît dans un emplacement inoccupé à portée et possède les mêmes statistiques que l''animal dont il revêt la forme, bien qu''il soit un céleste, une fée ou un fiélon (à vous de choisir) au lieu d''une bête.' || E'\n' || 'Votre familier agit indépendamment de vous, mais il obéit toujours à vos ordres. Lors d''un combat, il lance son propre dé d''initiative et agit à son tour. Il ne peut pas attaquer, mais il peut effectuer d''autres actions normalement.' || E'\n' || 'Quand le familier tombe à 0 point de vie, il disparaît sans laisser de cadavre derrière lui. Il réapparaît si vous lancez de nouveau ce sort.' || E'\n' || 'Vous pouvez communiquer par télépathie avec votre familier tant qu''il se trouve dans un rayon de 30 mètres autour de vous. De plus, vous pouvez dépenser votre action pour percevoir le monde par les yeux et les oreilles de votre familier jusqu''au début de votre prochain tour. Vous bénéficiez aussi de tout sens spécial que possède votre familier. Pendant ce temps, vos yeux et vos oreilles ne fonctionnent plus.' || E'\n' || 'Vous pouvez renvoyer temporairement votre familier par une action. Il gagne alors une poche dimensionnelle où il attend que vous le rappeliez. Vous pouvez aussi le renvoyer définitivement. Vous pouvez utiliser une action alors qu''il est temporairement renvoyé pour le faire réapparaitre dans un emplacement inoccupé situé dans un rayon de 9 mètres autour de vous.' || E'\n' || 'Vous ne pouvez avoir qu''un familier à la fois. Si vous lancez ce sort alors que vous avez déjà un familier, vous attribuez simplement une nouvelle forme à celui que vous possédez déjà choisissez une des formes de la liste précédente, que votre familier adopte de suite.' || E'\n' || 'Enfin, quand vous lancez un sort avec une portée de « contact » votre familier peut délivrer le sort comme si c''était lui qui le lançait. Il doit se trouver à 30 mètres de vous ou moins et utiliser sa réaction pour transmettre le sort au moment où vous le lancez. Si le sort exige un jet d''attaque, vous utilisez votre propre modificateur d''attaque lors du jet.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/find_familiar_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Disque flottant de Tenser',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '3 mètres',
        'V, S, M (une goutte de mercure)',
        '1 heure',
        'Ce sort crée un plan de force circulaire horizontal d''un mètre de diamètre pour 2,5 centimètres d''épaisseur. Il flotte à un mètre du sol dans un espace inoccupé de votre choix situé à portée et dans votre champ de vision. Le disque persiste pendant toute la durée du sort et peut accueillir jusqu''à 250 kilos. Si on pose plus de poids dessus, le sort se termine et tout ce qui se trouvait sur le disque tombe à terre.' || E'\n' || 'Le disque reste immobile tant que vous vous tenez dans un rayon de 6 mètres. Si vous vous en éloignez plus que cela, il vous suit de manière à rester dans les 6 mètres autour de vous. Il peut se déplacer sur un terrain irrégulier, monter ou descendre des escaliers, des pentes, etc. Mais il ne peut pas franchir une différence de niveau de trois mètres ou plus.' || E'\n' || 'Par exemple, il ne peut pas passer au-dessus d''une fosse de 3 mètres de profondeur ni la quitter s''il a été formé au fond.' || E'\n' || 'Si vous vous éloignez à plus de 30 mètres du disque (typiquement parce qu''il ne peut pas contourner un obstacle pour vous suivre), le sort se termine.',
        NULL
    ),
    (
        'Graisse',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (de la couenne de porc ou du beurre)',
        '1 minute',
        'Une couche de graisse particulièrement glissante recouvre le sol dans une zone de 3 mètres de côté centrée sur un point situé à portée et le change en terrain difficile pour toute la durée du sort.' || E'\n' || 'Lorsque la graisse apparaît, chaque créature se trouvant dans la zone affectée doit réussir un jet de sauvegarde de Dextérité ou tomber à terre. Une créature qui entre dans la zone ou y termine son tour doit aussi réussir ce jet sous peine de se retrouver à terre.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/grease_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Bénédiction',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '9 mètres',
        'V, S, M (un peu d''eau bénite à asperger)',
        'concentration,jusqu''à 1 minute',
        'Vous bénissez jusqu''à trois créatures de votre choix situées à portée. Quand une cible fait un jet d''attaque ou de sauvegarde avant la fin du sort, elle lance 1d4 et ajoute le montant obtenu au jet d''attaque ou de sauvegarde.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez affecter une créature de plus par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/bless_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Bouclier de la foi',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action bonus',
        '18 mètres',
        'V, S, M (un petit parchemin avec un extrait de texte sacré)',
        'concentration,jusqu''à 10 minutes',
        'Un champ scintillant apparaît autour d''une créature de votre choix située à portée et lui donne un bonus de +2 à la CA pendant toute la durée du sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/shield_of_faith_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Détection de la magie',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action (rituel)',
        'personnelle',
        'V, S',
        'concentration.jusqu''à 10 minutes',
        'Pendant toute la durée du sort, vous percevez la présence de magie dans un rayon de 9 mètres. Si vous percevez ainsi une magie, vous pouvez dépenser votre action pour discerner une faible aura autour d''une créature ou d''un objet visible dans la zone et imprégné de magie. Vous découvrez aussi à quelle école appartient cette magie, le cas échéant.' || E'\n' || 'Le sort ignore la plupart des obstacles, mais il ne peut pas franchir 30 centimètres de pierre, 2,5 centimètres de métal ordinaire, une mince feuille de plomb, ni 1 mètre de bois ou de terre.',
        NULL
    ),
    (
        'Détection du bien et du mal',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S',
        'concentration.jusqu''à 10 minutes',
        'Pendant toute la durée du sort, vous savez s''il y a une aberration, un céleste, un élémentaire, une fée, un fiélon ou un mort-vivant dans un rayon de 9 mètres autour de vous et vous savez précisément où il se trouve. De même, vous savez si un lieu ou un objet situé dans un rayon de 9 mètres a été consacré ou profané.' || E'\n' || 'Le sort ignore la plupart des obstacles, mais il ne peut pas franchir 30 centimètres de pierre, 2,5 centimètres de métal ordinaire, une mince feuille de plomb, ni 1 mètre de bois ou de terre.',
        NULL
    ),
    (
        'Détection du poison et des maladies',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action (rituel)',
        'personnelle',
        'V, S, M (un brin d''if )',
        'concentration.jusqu''à 10 minutes',
        'Pendant toute la durée du sort, vous percevez la présence de poisons, de créatures venimeuses et de maladies dans un rayon de 9 mètres autour de vous. Vous déterminez également leur emplacement et identifiez à chaque fois le type de poison, de créature ou de maladie concerné.' || E'\n' || 'Le sort ignore la plupart des obstacles, mais il ne peut pas franchir 30 centimètres de pierre, 2,5 centimètres de métal ordinaire, une mince feuille de plomb, ni 1 mètre de bois ou de terre.',
        NULL
    ),
    (
        'Duel forcé',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action bonus',
        '9 mètres',
        'V',
        'concentration,jusqu''à 1 minute',
        'Vous poussez une créature à vous affronter en duel. Une créature située à portée dans votre champ de vision doit faire un jet de sauvegarde de Sagesse. Si elle le rate, vous l''obnubilez et elle ne peut résister à votre injonction divine. Pendant toute la durée du sort, elle est désavantagée lors des jets d''attaque effectués contre toute créature autre que vous et doit faire un jet de sauvegarde de Sagesse chaque fois qu''elle tente de s''éloigner à plus de 9 mètres de vous. Si elle réussit ce jet de sauvegarde, le sort ne gêne pas ses mouvements pour ce tour.' || E'\n' || 'Le sort se termine si vous attaquez une créature autre que celle visée par ce sort, si vous lancez un sort sur une créature hostile autre qu''elle, si une créature amicale envers vous la blesse ou lui lance un sort néfaste ou si vous terminez votre tour à plus de 9 mètres d''elle.',
        NULL
    ),
    (
        'Faveur divine',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vos prières vous imprègnent d''une aura radieuse. Jusqu''à la fin du sort, les attaques que vous portez avec une arme infligent 1d4 dégâts radiants supplémentaires en cas de coup au but.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/divine_favor_spell_evocation_bg3_wiki_150px.png'
    ),
    (
        'Frappe ardente',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration,jusqu''à 1 minute',
        'Lors de la prochaine attaque armée qui vous permet de toucher une créature pendant la durée du sort, votre arme flamboie, comme chauffée à blanc, et l''attaque inflige 1d6 dégâts de feu supplémentaires. Elle embrase également la cible qui doit faire un jet de sauvegarde de Constitution au début de chacun de ses tours jusqu''à la fin du sort. Si elle échoue, elle subit 1d6 dégâts de feu, si elle réussit le sort se termine. Si la cible ou une créature située dans un rayon de 1,50 mètre autour d''elle utilise une action pour éteindre les flammes ou si un effet les étouffe (si la cible est plongée dans l''eau par exemple), le sort se termine.' || E'\n' || '**À plus haut niveau**, si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts initiaux augmentent de 1d6 par emplacement de sort au-delà du 1e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/searing_smite_spell_baldurs_gate_3_wiki_guide_150px.png'
    ),
    (
        'Frappe colérique',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration,jusqu''à 1 minute',
        'Lorsque vous touchez une cible avec une attaque armée au corps à corps pour la première fois pendant la durée de ce sort, votre attaque inflige 1d6 dégâts psychiques supplémentaires. De plus, si la cible est une créature, elle doit réussir un jet de sauvegarde de Sagesse, sans quoi elle est terrorisée à votre vue jusqu''à ce que le sort se termine. Par une action, elle peut faire un jet de sauvegarde de Sagesse contre le DD du jet de sauvegarde de votre sort pour rassembler son courage et mettre fin au sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wrathful_smite_spell_evocation_bg3_wiki_150px.png'
    ),
    (
        'Frappe tonitruante',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration, jusqu''à 1 minute',
        'Lorsque vous touchez une cible avec une attaque armée au corps à corps pour la première fois pendant la durée de ce sort, votre arme fait retentir un fracas tonitruant audible dans un rayon de 90 mètres autour de vous, et l''attaque inflige 2d6 dégâts de tonnerre supplémentaires. De plus, si la cible est une créature, elle doit réussir un jet de sauvegarde de Force ou se trouver repoussée sur 3 mètres à l''opposé de votre position et tomber à terre.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/thunderous_smite_spell_evocation_bg3_wiki_150px.png'
    ),
    (
        'Héroïsme',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        'contact',
        'V, S',
        'concentration,jusqu''à 1 minute',
        'Vous imprégnez une créature consentante que vous touchez de courage. Jusqu''à la fin du sort, elle est immunisée contre l''état terrorisé et, au début de chacun de ses tours, elle gagne un montant de points de vie temporaires égal à votre modificateur de caractéristique d''incantation. Quand le sort se termine, la cible perd les éventuels points de vie temporaires restants issus de ce sort.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez affecter une créature de plus par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/heroism_spell_bg3_wiki_guide_150px.png'
    ),
    (
        'Injonction',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V',
        '1 round',
        'Vous lancez un ordre d''un mot à une créature située à portée dans votre champ de vision. Elle doit réussir un jet de sauvegarde de Sagesse, sans quoi elle exécute votre ordre à son prochain tour. Le sort reste sans effet si la cible est un mort vivant, si elle ne comprend pas votre langue ou si votre ordre la met directement en danger.' || E'\n' || 'Voici quelques ordres typiques et leurs effets. Vous pouvez donner un ordre différent de ceux présentés là, mais dans ce cas, c''est au MD de décider comment la victime se comporte. Le sort se termine si elle se trouve dans l''incapacité d''obéir à l''ordre reçu.' || E'\n' || '* **Approche**: La cible s''approche de vous en empruntant l''itinéraire le plus court et le plus direct. Elle termine son tour dès qu''elle arrive dans un rayon de 1,50 mètre autour de vous.' || E'\n' || '* **Lâche**: La cible lâche ce qu''elle tient et son tour se termine.' || E'\n' || '* **Fuis**: La cible passe son tour à s''éloigner de vous par la méthode la plus rapide à sa disposition.' || E'\n' || '* **Rampe**: La cible se laisse tomber à terre et termine son tour.' || E'\n' || '* **Stop**: La cible ne bouge pas et n''entreprend aucune action.' || E'\n' || 'Une créature en vol reste dans les airs, à condition qu''elle soit en mesure de le faire. Si elle est obligée de se déplacer pour rester en vol, elle parcourt la distance minimum requise pour ce faire. **À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, vous pouvez affecter une créature de plus par niveau au-delà du 1er . Ces créatures doivent toutes se trouver à 9 mètres ou moins les unes des autres lorsque vous lancez le sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/command_halt_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Protection contre le mal et le bien',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S, M (eau bénite ou poudre de fer et d''argent, que le sort consume)',
        'concentration, jusqu''à 10 minutes',
        'Jusqu''à la fin du sort, une créature consentante que vous touchez est protégée contre certains types de créatures : les aberrations, les célestes, les élémentaires, les fées, les fiélons et les morts-vivants.' || E'\n' || 'Cette protection se traduit par plusieurs avantages. Les créatures des types précédemment nommés sont désavantagées lors des jets d''attaque contre la cible et ne peuvent pas la charmer, la terroriser, ni la posséder. Si elle est déjà sous l''effet d''un tel état émanant d''une telle créature, elle est avantagée lors d''un éventuel nouveau jet de sauvegarde contre l''effet en question.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/protection_from_good_and_evil_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Purification de la nourriture et de l''eau',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '3 mètres',
        'V, S',
        'instantanée',
        'Toute la nourriture et les boissons non magiques présentes dans une sphère d''un rayon de 1,50 mètre centrée autour d''un point de votre choix situé à portée sont purifiées et débarrassées de tout poison et maladie.',
        NULL
    ),
    (
        'Soin des blessures',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'contact',
        'V, S',
        'instantanée',
        'La créature que vous touchez récupère un nombre de points de vie égal à 1d8 + votre modificateur de caractéristique d''incantation. Ce sort n''a aucun effet sur les morts-vivants et les créatures artificielles.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les soins augmentent de 1d8 par niveau au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/cure_wounds_spell_baldursgate3_wiki_guide_150px.png'
    ),
    (
        'Alarme',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 minute',
        '9 mètres',
        'V, S, M (une minuscule clochette et un filament en argent)',
        '8 heures',
        'Vous installez une alarme pour vous avertir en cas d''intrusion. Choisissez une porte, une fenêtre ou une zone à portée qui ne fasse pas plus qu''un cube de 6 mètres d''arête. Tant que le sort fait effet, une alarme vous alerte dès qu''une créature de taille Très Petite ou supérieure touche la zone protégée ou y pénètre. Au moment où vous lancez le sort, vous pouvez désigner des créatures qui ne déclencheront pas l''alarme. Vous pouvez aussi choisir si l''alarme sera audible ou mentale.' || E'\n' || 'Une alarme mentale vous avertit d''un tintement dans votre tête tant que vous vous trouvez dans un rayon de 1,5 kilomètre autour de la zone protégée. Ce tintement suffit à vous réveiller si vous êtes endormi.' || E'\n' || 'Une alarme audible émet le même son qu''une cloche d''alerte pendant 10 secondes et retentit dans un rayon de 18 mètres.',
        NULL
    ),
    (
        'Grêle d''épines',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration, jusqu''à 1 minute',
        'La prochaine fois que vous touchez une créature avec une attaque armée à distance avant la fin du sort, ce dernier crée une pluie d''épines qui jaillit de votre arme ou de votre munition. En plus de l''effet normal de l''attaque, la cible et toutes les créatures situées dans un rayon de 1,50 mètre autour d''elle doivent faire un jet de sauvegarde de Dextérité. Une créature subit 1d10 dégâts perforants en cas d''échec, la moitié en cas de réussite.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d10 par emplacement de sort au-delà du 1er (pour un maximum de 6d10).',
        NULL
    ),
    (
        'Armure d''Agathys',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle',
        'V, S, M (un verre d''eau)',
        '1 heure',
        'Une force magique protectrice vous entoure et se manifeste sous la forme d''une pellicule de givre spectral qui recouvre votre personne et votre équipement. Vous gagnez 5 points de vie temporaires pendant toute la durée du sort. Si une créature vous touche avec une attaque de corps à corps alors que vous possédez encore ces points de vie temporaires, elle subit 5 dégâts de froid.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les points de vie temporaires et les dégâts de froid augmentent de 5 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/armor_of_agathys_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Maléfice',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action bonus',
        '27 mètres',
        'V, S, M (œil de triton pétrifié)',
        'concentration, jusqu''à 1 heure',
        'Vous lancez une malédiction sur une créature située à portée dans votre champ de vision. Tant que la durée du sort n''a pas expiré, vous infligez 1d6 dégâts nécrotiques supplémentaires à la cible chaque fois que vous la touchez avec une attaque. Lorsque vous lancez le sort, choisissez une caractéristique. La cible est désavantagée lors des tests concernant cette caractéristique.' || E'\n' || 'Si la cible tombe à O point de vie avant que le sort n''expire, vous pouvez utiliser votre action bonus lors d''un tour ultérieur pour affecter une nouvelle créature.' || E'\n' || 'Si la cible bénéficie du sort _lever une malédiction_, _maléfice_ se termine immédiatement.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou 4, vous pouvez vous concentrer sur le sort pendant 8 heures. Si vous utilisez un emplacement de niveau 5 ou plus, vous pouvez maintenir votre concentration sur le sort jusqu''à 24 heures.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hex_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Représailles infernales',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 réaction en réponse aux dégâts que vous inflige une créature située dans votre champ de vision et dans un rayon de 18 mètres autour de vous',
        '18 mètres',
        'V, S',
        'instantanée',
        'Il vous suffit de pointer le doigt vers la créature qui vient de vous blesser pour qu''elle soit momentanément enveloppée d''un linceul de flammes infernales. Elle doit faire un jet de sauvegarde de Dextérité. Si elle échoue, elle subit 2d10 dégâts de feu, sinon la moitié seulement.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d10 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hellish_rebuke_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Serviteur invisible',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (un bout de ficelle et un morceau de bois)',
        '1 heure',
        'Ce sort crée une force invisible, dépourvue de forme et d''intellect, mais capable d''accomplir des tâches simples sur votre ordre jusqu''à la fin du sort. Le serviteur se matérialise au sol, dans un emplacement inoccupé situé à portée. Il a une CA de 10, 1 pv, une Force de 2 et il est incapable d''attaquer. S''il tombe à 0 point de vie, le sort se termine.' || E'\n' || 'Une fois à chacun de vos tours, vous pouvez utiliser une action bonus pour ordonner mentalement à votre serviteur de se déplacer d''un maximum de 4,50 mètres et d''interagir avec un objet. Le serviteur peut accomplir des tâches simples, à la portée d''un domestique humain, comme aller chercher des affaires, faire le ménage, repriser, plier les habits, allumer la cheminée, servir les plats et la boisson, etc. Une fois que vous avez donné votre ordre, il fait de son mieux pour y obéir jusqu''à ce qu''il ait terminé. Il attend alors l''ordre suivant.' || E'\n' || 'Si vous ordonnez à votre serviteur d''accomplir une tâche qui l''éloigne à plus de 18 mètres de vous, le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/faerie_fire_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Tentacules d''Hadar',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        'personnelle (3 mètres de rayon',
        'V, S',
        'instantanée',
        'Vous invoquez la puissance d''Hadar, le Sombre Appétit. Des filaments d''énergie noire jaillissent de vous et fouettent toutes les créatures situées dans un rayon de 3 mètres. Chacune doit faire un jet de sauvegarde de Force. En cas d''échec, une créature subit 2d6 dégâts nécrotiques et ne peut pas utiliser de réaction jusqu''à son prochain tour. Une créature qui réussit son jet de sauvegarde subit seulement la moitié des dégâts et ne souffre pas d''autres effets.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 2 ou plus, les dégâts augmentent de 1d6 par emplacement de sort au-delà du 1er.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/arms_of_hadar_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Texte illusoire',
        1,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 minute',
        'contact',
        'S, M (de l''encre à base de plomb valant au minimum 10 po, que le sort consume)',
        '10 jours',
        'Vous écrivez sur un papier, un parchemin ou un autre matériau adapté à l''écriture et l''imprégnez d''une puissante illusion qui persiste pendant toute la durée du sort.' || E'\n' || 'À vos yeux et à ceux de toutes les créatures que vous désignez lors de l''incantation, l''écriture semble normale, de votre main, et transmet le message que vous aviez en tête en rédigeant le texte. Pour les autres personnes, vos écrits semblent appartenir à une langue inconnue ou magique complètement inintelligible, ou alors ils transmettent un message complètement différent de la réalité, rédigé d''une main qui n''est pas la vôtre et dans une autre langue de votre connaissance.' || E'\n' || 'Si quelqu''un dissipe le sort, l''illusion disparaît, mais le message original aussi.' || E'\n' || 'Une créature dotée de vision parfaite est capable de lire le message original.',
        NULL
    );