INSERT INTO sort (nom_sort,alias,nom_sort_en,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Compulsion',
        NULL,
        'Compulsion',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '9 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Les créatures de votre choix situées à portée dans votre champ de vision et en mesure de vous entendre doivent faire un jet de sauvegarde de Sagesse. Une cible impossible à charmer réussit automatiquement sonjet. Si la cible rate son jet, elle est affectée par le sort. Jusqu''à la fin de celui-ci, vous pouvez, à chaque tour, utiliser une action bonus pour désigner une direction horizontale par rapport à vous. Chaque cible affectée doit alors utiliser son déplacement au mieux pour aller dans cette direction à son prochain tour. Elle peut effectuer son action avant de se déplacer. Une fois qu''elle s''est ainsi déplacée, elle peut faire un nouveau jet de sauvegarde de Sagesse pour tenter de mettre un terme à l''effet du sort.' || E'\n' || 'Une cible n''est pas obligée de se rendre au sein d''une zone à l''évidence dangereuse, comme un brasier ou une fosse béante, mais elle est prête à provoquer des attaques d''opportunité pour se déplacer dans la direction indiquée.',
        NULL
    ),
    (
        'Contrôle de l''eau',
        NULL,
        'Control Water',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        '90 mètres',
        'V, S, M (une goutte d''eau et une pincée de poussière)',
        'concentration, jusqu''à 10 minutes',
        'Jusqu''à la fin du sort, vous contrôlez toute étendue d''eau indépendante située dans la zone de votre choix, cette dernière devant tenir dans un cube d''au maximum 30 mètres d''arête. Quand vous lancez ce sort, vous pouvez choisir l''un des effets suivants. À votre tour, vous pouvez utiliser une action pour répéter l''effet ou en appliquer un nouveau.' || E'\n' || '**Inondation**: Vous faites monter le niveau d''une étendue d''eau isolée d''un maximum de 6 mètres. Si la zone comprend une rive, l''eau déborde et se répand sur la terre ferme.' || E'\n' || 'Si vous avez lancé le sort sur une grande étendue d''eau, vous créez une vague de 6 mètres de haut qui traverse la zone affectée d''un bout à l''autre pour se briser une fois arrivée à la fin de la zone. Tous les véhicules de taille Très Grande ou inférieure qui se trouvent sur le chemin de la vague sont emportés jusqu''au bout de la zone. Tous ces véhicules ont 25% de chances de chavirer.' || E'\n' || 'Le niveau de l''eau reste plus élevé jusqu''à la fin du sort ou jusqu''à ce que vous choisissiez un autre effet. Si l''effet d''inondation produit une vague, elle se reforme au début de votre prochain tour tant que vous gardez cet effet actif.' || E'\n' || '**Écarter les eaux**: Vous écartez les eaux de la zone pour y créer un passage. Il traverse toute la zone, les eaux formant une muraille de chaque côté. Le passage demeure jusqu''à la fin du sort ou jusqu''à ce que vous optiezpour un effet différent. Dans ces deux cas, l''eau remplit alors progressivement le passage, au fil du round suivant, jusqu''à ce que le niveau de l''eau revienne à la normale.' || E'\n' || '**Modifier le cours de l''eau**: Vous changez l''itinéraire de l''eau courante qui traverse la zone et l''envoyez dans la direction de votre choix, même si elle doit pour cela franchir des obstacles comme passer par-dessus un mur ou couler dans une direction improbable. L''eau suit vos instructions dans la zone affectée, mais dès qu''elle en sort, elle reprend un cours normal défini par le terrain qu''elle parcourt. L''eau continue de couler là où vous l''avez choisi jusqu''à la fin du sort oujusqu''à ce que vous décidiez d''un autre effet.' || E'\n' || '**Tourbillon**: Cet effet nécessite une étendue d''eau d''au moins 15 mètres carrés pour 7,50 mètres de fond et se traduit par la formation d''un tourbillon au centre de la zone. Il se présente sous forme d''un vortex de 1,50 mètre de large à sa base pour un maximum de 15 mètres de large au sommet et une hauteur de 7,50 mètres. Toutes les créatures et tous les objets qui se trouvent dans l''eau et dans un rayon de 7,50 mètres autour du tourbillon sont entraînés vers lui sur 3 mètres. Une créature peut s''éloigner à la nage si elle réussit un test de Force (Athlétisme) contre le DD du jet de sauvegarde de votre sort.' || E'\n' || 'Quand une créature entre dans le vortex pour la première fois de son tour ou qu''elle y commence son tour, elle doit faire un jet de sauvegarde de Force. Si elle échoue, elle reçoit 2d8 dégâts contondants et se fait emporter par le vortex jusqu''à la fin du sort. Si elle réussit son jet, elle subit seulement la moitié des dégâts et n''est pas prise dans le vortex. Une créature emportée par le vortex peut utiliser une action pour tenter de s''en éloigner comme décrit plus haut, mais elle est désavantagée lors de son test de Force (Athlétisme). À chaque tour, la première fois qu''un objet entre dans le vortex, il subit 2d8 dégâts contondants. Ces dégâts se répètent à chaque round passé dans le vortex.',
        NULL
    ),
    (
        'Divination',
        NULL,
        'Divination',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'personnelle',
        'V, S, M (de l''encens et une offrande sacrificielle adaptée à votre religion, l''ensemble valant au moins 25 po, et que le sort consume)',
        'instantanée',
        'Grâce à votre magie et à une offrande, vous entrez en contact avec un dieu ou l''un de ses serviteurs. Vous lui posez une unique question à propos d''un objectif, d''un événement ou d''une activité qui doit se dérouler dans les sept jours à venir. Le MD vous donne une réponse sincère, pouvant être une courte phrase, des vers cryptiques ou un présage.' || E'\n' || 'Le sort ne tient pas compte d''une éventuelle modification des circonstances susceptible de bouleverser l''issue des événements, comme l''incantation de sorts supplémentaires ou la perte ou l''arrivée d''un compagnon.' || E'\n' || 'Si vous lancez ce sort à deux reprises ou plus avant un long repos, il y a 25% de chances par incantation en sus de la première que vous obteniez une prémonition aléatoire au lieu d''une prémonition fiable. C''est au MD de faire ce jet en secret.',
        NULL
    ),
    (
        'Façonnage de la pierre',
        NULL,
        'Stone Shape',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '1 action',
        'contact',
        'V, S, M (argile molle, à façonner pour lui donner approximativement la forme de l''objet de pierre désiré)',
        'instantanée',
        'Vous touchez un objet de pierre de taille Moyenne ou inférieure ou une section de pierre d''un maximum de 1,50 mètre dans toutes les dimensions et lui donnez la forme que vous désirez. Vous pouvez, par exemple, façonner un gros caillou de manière à en faire une arme, une idole ou un coffre, ou bien creuser un étroit passage dans un mur, à condition que ce dernier ne fasse pas plus de 1,50 mètre d''épaisseur. Vous pouvez façonner une porte de pierre ou son chambranle pour la sceller. L''objet créé peut avoir au maximum deux charnières et un loquet, mais il est impossible de créer des mécanismes plus complexes.',
        NULL
    ),
    (
        'Insecte géant',
        NULL,
        'Giant Insect',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '9 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Vous transformez un maximum de dix mille-pattes, trois araignées, cinq guêpes ou un scorpion situés à portée, en version géante de leur forme naturelle pendant toute la durée du sort. Un mille-patte devient donc un mille-patte géant, une araignée une araignée géante, une guêpe une guêpe géante et un scorpion un scorpion géant.' || E'\n' || 'Chaque créature obéit à vos ordres verbaux et, lors d''un combat, agit à chaque round à votre tour. C''est le MD qui dispose des statistiques de ces créatures et gère leurs actions et leurs déplacements.' || E'\n' || 'Une créature reste sous sa forme géante pendant toute la durée du sort,jusqu''à ce qu''elle tombe à O point de vie ou jusqu''à ce que vous utilisiez une action pour révoquer l''effet du sort sur elle.' || E'\n' || 'Le MD peut vous autoriser à choisir une cible différente. Par exemple, si vous transformez une abeille, sa version géante peut disposer des mêmes statistiques qu''une guêpe géante.',
        NULL
    ),
    (
        'Invoquer des élémentaires mineurs',
        'Invocation d''élémentaires mineurs',
        'Conjure Minor Elementals',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 minute',
        '27 mètres',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez des élémentaires qui apparaissent dans des cases inoccupées situées à portée et dans votre champ de vision. Choisissez l''une des options suivantes pour déterminer quelles créatures apparaissent.' || E'\n' || '* Un élémentaire d''une dangerosité de 2 ou moins.' || E'\n' || '* Deux élémentaires d''une dangerosité de 1 ou moins.' || E'\n' || '* Quatre élémentaires d''une dangerosité de 1/2 ou moins.' || E'\n' || '* Huit élémentaires d''une dangerosité de 1/4 ou moins.' || E'\n' || 'Un élémentaire ainsi invoqué disparaît dès qu''il tombe à 0 point de vie ou quand le sort se termine.' || E'\n' || 'Les créatures invoquées se montrent amicales envers vous et vos compagnons. Lancez l''initiative pour les créatures invoquées en tant que groupe qui dispose de ses propres tours de jeu. Les élémentaires obéissent aux ordres verbaux que vous leur donnez (sans que cela vous demande d''utiliser une action). En l''absence d''ordre, ils se défendent contre les créatures hostiles, mais n''entreprennent pas d''autre action.' || E'\n' || 'C''est le MD qui dispose des statistiques des créatures.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant certains emplacements de niveau supérieur, vous choisissez l''une des options d''invocation décrites précédemment et faites apparaître plus de créatures : deux fois plus pour un emplacement de niveau 6 et trois fois plus pour un emplacement de niveau 8.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/conjureminorelementals-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Invoquer des êtres des bois',
        'Invocation d''êtres sylvestres',
        'Conjure Woodland Beings',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '18 mètres',
        'V, S, M (une baie de houx par créature invoquée)',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez des créatures féeriques qui apparaissent dans des cases inoccupées situées à portée et dans votre champ de vision. Choisissez l''une des options suivantes pour déterminer quelles créatures apparaissent.' || E'\n' || '* Une créature féerique d''une dangerosité de 2 ou moins.' || E'\n' || '* Deux créatures féeriques d''une dangerosité de 1 ou moins.' || E'\n' || 'Quatre créatures féeriques d''une dangerosité de 1/2 ou moins.' || E'\n' || '* Huit créatures féeriques d''une dangerosité de 1/4 ou moins.' || E'\n' || 'Une créature invoquée disparaît dès qu''elle tombe à 0 point de vie ou quand le sort se termine.' || E'\n' || 'Les créatures invoquées se montrent amicales envers vous et vos compagnons. Lancez l''initiative pour les créatures invoquées en tant que groupe qui dispose de ses propres tours de jeu. Les créatures féeriques obéissent aux ordres verbaux que vous leur donnez (sans que cela vous demande d''utiliser une action). En l''absence d''ordre, elles se défendent contre les créatures hostiles, mais n''entreprennent pas d''autre action.' || E'\n' || 'C''est le MD qui dispose des statistiques des créatures.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant certains emplacements de niveau supérieur, vous choisissez l''une des options d''invocation décrites précédemment et faites apparaître plus de créatures : deux fois plus pour un emplacement de niveau 6, et trois fois plus pour un emplacement de niveau 8.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/conjurewoodlandbeings-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Liane agrippeuse',
        'Liane avide',
        'Grasping Vine',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action bonus',
        '9 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous invoquez une liane qui sort de terre dans un emplacement inoccupé de votre choix situé à portée dans votre champ de vision. Lorsque vous lancez ce sort, vous pouvez indiquer à la liane de s''enrouler autour d''une créature située dans un rayon de 9 mètres autour d''elle et dans votre champ de vision. La créature doit réussir un jet de sauvegarde de Dextérité, sans quoi elle est traînée sur 6 mètres en direction du pied de la liane.' || E'\n' || 'Tant que la durée du sort ne s''est pas écoulée, vous pouvez ordonner à la liane de continuer de s''en prendre à la même créature ou de changer de cible, et cela par une action bonus à chacun de vos tours.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/conjuration_graspingvine-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Confusion',
        NULL,
        'Confusion',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '27 mètres',
        'V, S, M (trois coquilles de noix)',
        'concentration, jusqu''à 1 minute',
        'Ce sort assaille et pervertit l''esprit des créatures, générant des hallucinations et provoquant des réactions incontrôlées. Toutes les créatures situées dans une sphère de 3 mètres de rayon autour d''un point de votre choix situé à portée doivent faire un jet de sauvegarde de Sagesse quand vous lancez le sort. Si elles échouent, le sort les affecte.' || E'\n' || 'Une cible affectée ne peut pas accomplir de réaction et doit lancer 1d1O au début de chacun de ses tours pour déterminer comment elle se comporte pendant le tour.' || E'\n' || '**d1O Comportement**' || '**1)** La créature utilise la totalité de son mouvement pour se déplacer dans une direction aléatoire. Pour déterminer cette dernière, lancez un d8 en assignant une direction à chaque face. La créature n''effectue aucune action pour ce tour.' || E'\n' || '**2-6)** La créature ne bouge pas et n''entreprend pas la moindre action pour ce tour.' || E'\n' || '**7-8)** La créature utilise son action pour porter une attaque au corps à corps contre une créature aléatoire à portée d''allonge. S''il n''y a pas de créature à portée, elle ne fait rien du tour.' || E'\n' || '**9-10)** La créature peut agir et se déplacer normalement.' || E'\n' || 'Une créature affectée peut faire un jet de sauvegarde de Sagesse à la fin de chacun de ses tours. En cas de succès, l''effet se termine pour elle.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, le rayon de la sphère augmente de 1,50 mètre par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/confusion-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Dominer une bête',
        'Domination de bête',
        'Dominate Beast',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous tentez d''envoûter une bête située à portée dans votre champ de vision. Elle doit réussir un jet de sauvegarde de Sagesse, sans quoi vous la charmez pendant toute la durée du sort. Elle est avantagée lors du jet de sauvegarde si vous ou des créatures amicales envers vous êtes en train de la combattre.' || E'\n' || 'Tant que la bête est charmée, vous entretenez un lien télépathique avec elle, qui persiste tant que vous vous trouvez sur le même plan d''existence. Vous pouvez utiliser ce lien télépathique pour donner des ordres à cette créature tant que vous êtes conscient (ce qui ne vous demande pas d''action). Elle fait de son mieux pour vous obéir. Vous pouvez lui donner un ordre simple et générique, comme « attaque cette créature », « cours jusque là-bas » ou « va chercher cet objet ». Si elle ne reçoit pas de nouvelles instructions de votre part une fois l''ordre exécuté, elle se contente de se défendre et de se préserver au mieux.' || E'\n' || 'Vous pouvez utiliser votre action pour prendre le contrôle total de votre cible et la diriger de façon précise. Jusqu''à la fin de votre prochain tour, elle exécute seulement les actions que vous choisissez et ne fait rien que vous ne lui ayez autorisé. Pendant cette période, vous pouvez aussi lui faire exécuter une réaction, mais pour cela, vous devez également dépenser votre propre réaction.' || E'\n' || 'Chaque fois que la cible subit des dégâts, elle a droit à un nouveau jet de sauvegarde de Sagesse contre le sort. Si elle le réussit, le sort prend fin.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5, la durée devient « concentration, jusqu''à 10 minutes ». Si vous lancez ce sort en utilisant un emplacement de niveau 6, la durée devient « concentration, jusqu''à 1 heure ». Si vous lancez ce sort en utilisant un emplacement de niveau 7, la durée devient « concentration, jusqu''à 8 heures ».',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dominatebeast-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Flétrissement',
        NULL,
        'Blight',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        '9 mètres',
        'V, S',
        'instantanée',
        'L''énergie nécromantique inonde une créature de votre choix située à portée dans votre champ de vision, et draine ses fluides corporels et sa vitalité. La cible doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle reçoit 8d8 dégâts nécrotiques, la moitié seulement si elle réussit sonjet. Ce sort n''a aucun effet sur les morts-vivants ou les créatures artificielles.' || E'\n' || 'Si vous visez une créature végétale ou une plante magique, elle est désavantagée lors du jet de sauvegarde et le sort lui inflige le maximum de dégâts possible.' || E'\n' || 'Si vous visez une plante non magique qui n''est pas une créature, comme un arbre ou un buisson, elle n''a pas droit au moindre jet de sauvegarde, mais se flétrit et meurt.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/necromancy-blight-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Invisibilité supérieure',
        'Invisibilité suprême',
        'Greater Invisibility',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '1 action',
        'contact',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous devenez invisible jusqu''à ce que le sort se termine, ou vous pouvez accorder cet effet à une créature consentante que vous touchez. Tout ce que porte la cible devient invisible tant que les objets restent sur sa personne.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/greaterinvisibility-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Métamorphose',
        NULL,
        'Polymorph',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V, S, M (un cocon de chenille)',
        'concentration, jusqu''à 1 heure',
        'Ce sort change la forme d''une créature située à portée dans votre champ de vision. Une créature non consentante doit faire un jet de sauvegarde de Sagesse pour éviter cet effet. Le sort n''a aucun effet sur un métamorphe ou une créature à 0 point de vie.' || E'\n' || 'La transformation persiste pendant toute la durée du sort ou jusqu''à ce que la cible tombe à O point de vie ou meure. Vous pouvez donner comme nouvelle forme celle de n''importe quelle bête dont l''indice de dangerosité est égal ou inférieur à celui de la cible (ou à son niveau,si elle n''a pas d''indice de dangerosité). Les statistiques de jeu de la cible, y compris ses valeurs de caractéristique mentales, sont remplacées par celles de la bête choisie. Elle conserve en revanche son alignement et sa personnalité.' || E'\n' || 'La cible possède les points de vie correspondant à sa nouvelle forme. Quand elle reprend sa forme normale, elle se retrouve avec le nombre de points de vie qui était le sien avant la transformation. Si elle reprend sa forme normale parce qu''elle est tombée à O point de vie, les éventuels dégâts en excès sont déduits des points de vie de sa forme normale. Tant que les dégâts en excès ne réduisent pas les points de vie normaux de la créature à 0, elle n''est pas inconsciente.' || E'\n' || 'La nouvelle forme de la créature limite les actions qu''elle peut entreprendre et elle ne peut ni parler, ni lancer de sorts, ni effectuer une action qui nécessite de parler ou de se servir de ses mains.' || E'\n' || 'L''équipement de la cible fusionne avec sa nouvelle forme, mais elle ne peut pas activer, utiliser, ni manier la moindre pièce d''équipement et ne peut pas non plus bénéficier de ses effets.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/polymorph-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Mur de feu',
        NULL,
        'Wall of Fire',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (un éclat de phosphore)',
        'concentration, jusqu''à 1 heure',
        'Vous créez un mur de feu sur une surface solide située à portée. Il peut faire un maximum de 18 mètres de long, 6 mètres de haut et 30 centimètres d''épaisseur, ou prendre une forme circulaire de 6 mètres de diamètre pour 6 mètres de haut et 30 centimètres d''épaisseur. Le mur est opaque et persiste toute la durée du sort.' || E'\n' || 'Quand le mur apparaît, chaque créature présente dans sa zone d''effet doit faire un jet de sauvegarde de Dextérité. Celles qui échouent reçoivent 5d8 dégâts de feu, les autres la moitié seulement.' || E'\n' || 'Une face du mur (celle de votre choix) inflige 5d8 dégâts de feu à chaque créature qui termine son tour à 3 mètres d''elle ou moins ou au sein du mur. Une créature qui pénètre dans le mur pour la première fois de son tour ou y termine son tour subit les mêmes dégâts. L''autre face du mur n''inflige pas de dégâts.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/walloffire-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Peau de pierre',
        NULL,
        'Stoneskin',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S, M (poussière de diamant d''une valeur de 100 po, que le sort consume)',
        'concentration, jusqu''à 1 heure',
        'Ce sort modifie la chair d''une créature consentante pour la rendre aussi dure que de la pierre. Jusqu''à la fin du sort, la cible est résistante aux dégâts non magiques contondants, perforants et tranchants.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/stoneskin-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Porte dimensionnelle',
        NULL,
        'Dimension Door',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '150 mètres',
        'V',
        'instantanée',
        'Vous vous téléportez depuis votre position actuelle vers n''importe quel emplacement désiré situé à portée. Vous arrivez exactement à l''endroit voulu. Ce peut être un endroit que vous voyez, que vous visualisez ou que vous pouvez décrire en donnant sa distance et sa direction, par exemple << 60 mètres plus bas en ligne droite » ou « en montant au nord-ouest à un angle de 45° sur 90 mètres ».' || E'\n' || 'Vous pouvez amener des objets avec vous, tant que leur poids ne dépasse pas la charge que vous êtes capable de porter. Vous pouvez également emmener avec vous une créature consentante de votre taille ou d''une taille inférieure, qui peut transporter du matériel dans la limite de ses capacités. Elle doit se trouver dans un rayon de 1,50 mètre autour de vous quand vous lancez le sort.' || E'\n' || 'Si vous deviez arriver dans un emplacement déjà occupé par un objet ou une créature, vous et la créature qui voyage avec vous subissez chacun 4d6 dégâts de force tandis que le sort s''avère incapable de vous téléporter.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dimensiondoor-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Tempête de grêle',
        NULL,
        'Ice Storm',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '90 mètres',
        'V, S, M (une pincée de poussière et quelques gouttes d''eau)',
        'instantanée',
        'Des grêlons durs comme de la pierre s''abattent dans un cylindre de 6 mètres de rayon pour 12 mètres de haut, centré sur un point à portée. Chaque créature présente dans le cylindre doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 2d8 dégâts contondants et 4d6 dégâts de froid tandis que les autres en subissent la moitié seulement.' || E'\n' || 'Les grêlons transforment la zone en terrain difficile jusqu''à la fin de votre prochain tour.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, les dégâts contondants augmentent de 1d8 par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/ice_storm_spell_evocation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Assassin imaginaire',
        NULL,
        'Phantasmal Killer',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        '36 mètres',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Vous puisez dans les cauchemars d''une créature située à portée dans votre champ de vision pour créer une manifestation illusoire de ses pires terreurs, qu''elle sera la seule à voir. La cible doit faire un jet de sauvegarde de Sagesse. Si elle le rate, elle est terrorisée pendant toute la durée du sort. Tant que le sort n''est pas terminé, la cible doit faire un jet de sauvegarde de Sagesse à la fin de chacun de ses tours. Elle subit 4d10 dégâts psychiques à chaque échec. Le sort se termine dès qu''elle réussit un jet de sauvegarde.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, les dégâts augmentent de 1d10 par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/phantasmalkiller-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Bouclier de feu',
        NULL,
        'Fire Shield',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '1 action bonus',
        '18 mètres',
        'V, S, M (un petit parchemin avec un extrait de texte sacré)',
        'concentration, jusqu''à 10 minutes',
        'Un champ scintillant apparaît autour d''une créature de votre choix située à portée et lui donne un bonus de +2 à la CA pendant toute la durée du sort.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fireshield-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Chien de garde de Mordenkainen',
        NULL,
        'Mordenkainen''s Faithful Hound',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '9 mètres',
        'V,S, M (un petit sifflet en argent, un éclat d''os et une ficelle)',
        '8 heures',
        'Vous invoquez un chien de garde fantomatique dans un emplacement inoccupé situé à portée et dans votre champ de vision. Il reste là pendant toute la durée du sort ou jusqu''à ce que vous le renvoyiez par une action ou que vous vous éloigniez à plus de 30 mètres de lui.' || E'\n' || 'Le chien est invisible pour tout le monde sauf pour vous et il est impossible de le blesser. Il se met à aboyer dès qu''une créature de taille Petite ou supérieure arrive à 9 mètres de lui sans prononcer d''abord le mot de passe que vous avez choisi lors de l''incantation. Le chien perçoit les créatures invisibles et voit ce qui se passe sur le plan éthéré. Il ignore les illusions.' || E'\n' || 'Au début de votre tour, le chien tente de mordre une créature qui vous est hostile et située dans un rayon de 1,50 mètre autour de lui. Son bonus d''attaque est égal à votre modificateur de caractéristique d''incantation+ votre bonus de maîtrise. S''il touche, il inflige 4d8 dégâts perforants.',
        NULL
    ),
    (
        'Coffre secret de Léomund',
        NULL,
        'Leomund''s Secret Chest',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        'contact',
        'V, S, M (un superbe coffre de 90x60x60 centimètres, fait de matériaux rares d''une valeur minimale de 5 000 po et une réplique du coffre de taille Très Petite, faite des mêmes matériaux et valant au moins 50 po)',
        'instantanée',
        'Vous dissimulez un coffre et son contenu sur le plan éthéré. Pour cela, vous devez toucher le coffre et la réplique qui sert de composante matérielle au sort. Le coffre peut contenir un maximum de 324 décimètres cubes (90x60x60 centimètres) de matière non vivante.' || E'\n' || 'Tant que le coffre reste sur le plan éthéré, vous pouvez utiliser une action pour toucher la réplique et le rappeler à vous. Il apparaît en un emplacement libre au sol, situé dans un rayon de 1,50 mètre autour de vous. Vous pouvez renvoyer le coffre dans le plan éthéré en utilisant une action et en touchant le coffre et sa réplique.' || E'\n' || 'Au bout de 60 jours, il y a 5% de chances cumulatifs par jour que les effets du sort se terminent. Ils s''achèvent aussi si vous lancez de nouveau le sort, si la petite réplique du coffre est détruite ou si vous décidez de mettre un terme au sort par une action. Si le sort se termine alors que le grand coffre est encore sur le plan éthéré, ce coffre est irrémédiablement perdu.',
        NULL
    ),
    (
        'Fabrication',
        NULL,
        'Fabricate',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Transmutation'),
        '10 minutes',
        '36 mètres',
        'V, S',
        'instantanée',
        'Vous convertissez des matériaux bruts en produits finis faits de la même matière. Par exemple, vous pouvez fabriquer un pont de bois à partir de souches d''arbres, une corde à base d''un tas de chanvre, et des habits à partir de lin ou de laine.' || E'\n' || 'Choisissez des matériaux bruts situés à portée et dans votre champ de vision. Vous pouvez fabriquer un objet de taille Grande ou inférieure (contenu dans un cube de 3 mètres de côté ou dans huit cubes reliés de 1,50 mètre de côté) à condition d''avoir assez de matière première. Toutefois, si vous travaillez avec du métal, de la pierre ou une autre substance minérale, l''objet fabriqué ne doit pas dépasser la taille Moyenne (donc tenir dans un cube de 1,50 mètre de côté). La qualité de l''objet fabriqué dépend de celle des matières premières.' || E'\n' || 'Il est impossible de créer ou de transmuter des créatures ou des objets magiques à l''aide de ce sort. Vous ne pouvez pas non plus y recourir pour fabriquer des objets demandant un haut degré d''expertise, comme des bijoux, des armes, du verre ou une armure, à moins que vous ne soyez formé à l''utilisation des outils d''artisanat nécessaires à l''élaboration de tels objets.',
        NULL
    ),
    (
        'Oeil magique',
        'Oeil du mage',
        'Arcane Eye',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 action',
        '9 mètres',
        'V, S, M (des poils de chauve-souris)',
        'concentration, jusqu''à 1 heure',
        'Vous créez un œil magique invisible à portée qui flotte dans les airs pendant toute la durée du sort.' || E'\n' || 'Il vous envoie mentalement des informations visuelles grâce à sa vision normale et dans le noir dans un rayon de 9 mètres. Il peut regarder dans toutes les directions.' || E'\n' || 'Par une action, vous pouvez déplacer l''œil d''un maximum de 9 mètres dans la direction de votre choix. Il peut s''éloigner de vous sur une distance illimitée, mais il ne peut pas entrer dans un autre plan d''existence. Une barrière solide l''empêche de passer, mais il peut se glisser à travers une ouverture d''au minimum 2,5 centimètres de diamètre.',
        NULL
    ),
    (
        'Sanctuaire privé de Mordenkainen',
        NULL,
        'Mordenkainen''s Private Sanctum',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '10 minutes',
        '36 mètres',
        'V, S, M (une mince couche de plomb, un morceau de verre opaque, un bout de coton ou de tissu et de la chrysolite en poudre)',
        '24 heures',
        'Vous sécurisez par magie une zone à portée. Il s''agit d''un cube d''au minimum 1,50 mètre d''arête et d''au maximum 30 mètres d''arête. Le sort persiste pendant toute sa durée ou jusqu''à ce que vous utilisiez une action pour le révoquer.' || E'\n' || 'Vous décidez de la sécurité offerte par le sort au moment de l''incantation en choisissant une ou plusieurs propriétés parmi les suivantes.' || E'\n' || '* Les sons ne peuvent pas franchir la barrière qui délimite la zone protégée.' || E'\n' || '* La barrière délimitant la zone protégée est sombre et brumeuse, ce qui empêche de voir au travers (même avec la vision dans le noir).' || E'\n' || '* Les organes sensoriels créés via un sort de divination ne peuvent pas apparaître au sein de la zone protégée ni traverser la barrière qui délimite son périmètre.' || E'\n' || '* Les sorts de divination ne peuvent pas prendre les créatures de la zone pour cible.' || E'\n' || '* Rien ne peut se téléporter à l''intérieur ou à l''extérieur de la zone protégée.' || E'\n' || 'Les voyages planaires sont bloqués au sein de la zone protégée.' || E'\n' || 'Si on lance ce sort tous les jours au même endroit pendant un an, ses effets deviennent permanents.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, vous pouvez augmenter la taille du cube de 30 mètres par niveau au-delà du 4e. Ainsi, avec un emplacement de niveau 5, vous pouvez protéger une zone de 60 mètres de côté.',
        NULL
    ),
    (
        'Sphère résiliente d''Otiluke',
        NULL,
        'Otiluke''s Resilient Sphere',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '9 mètres',
        'V, S, M (un bout de cristal transparent hémisphérique et son équivalent en gomme arabique)',
        'concentration, jusqu''à 1 minute',
        'Une sphère de force scintillante englobe une créature ou un objet de taille Grande ou inférieure situés à portée. Si la cible n''est pas consentante, elle a droit à un jet de sauvegarde de Dextérité. Si elle le rate, elle est enfermée dans la sphère pour toute la durée du sort.' || E'\n' || 'Rien ne peut franchir la barrière que forme la sphère ni les objets physiques, ni l''énergie, ni les effets des autres sorts. En revanche, une créature qui se trouve au sein de la sphère y respire sans mal. La sphère est immunisée contre tous les types de dégâts. De plus, les attaques et les effets originaires de l''extérieur de la sphère ne peuvent pas blesser la créature ou l''objet qu''elle abrite; de même, une créature au sein de la sphère est incapable d''endommager ce qui se trouve à l''extérieur.' || E'\n' || 'La sphère ne pèse rien et elle est tout juste assez grande pour contenir la créature ou l''objet qu''elle renferme. Une créature enfermée dans la sphère peut utiliser son action pour exercer une poussée sur la paroi de la sphère et la faire rouler à la moitié de sa vitesse habituelle. De même, une tierce personne peut ramasser la sphère ou la déplacer.' || E'\n' || 'Un sort de _désintégration_ visant la sphère la détruit sans endommager ce qu''elle contient.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/otilukes-resilient-sphere-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Tentacules noirs d''Evard',
        NULL,
        'Evard''s Black Tentacles',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '27 mètres',
        'V, S,M (un bout de tentacule appartenant à une pieuvre ou un calmar géant)',
        'concentration, jusqu''à 1 minute',
        'Des tentacules noirs grouillants envahissent le sol d''un emplacement de 6 mètres de côté situé à portée et dans votre champ de vision. Pendant toute la durée du sort,ils transforment la zone en terrain difficile.' || E'\n' || 'Quand une créature pénètre dans la zone affectée pour la première fois au cours d''un tour, ou quand elle débute son tour dans cette zone, elle doi� réussir un jet de sauvegarde de Dextérité, sans quoi elle reçoit 3d6 dégâts contondants et se retrouve entravée par les tentacules jusqu''à la fin du sort. Une créature qui commence son tour déjà entravée dans la zone subit 3d6 dégâts contondants.' || E'\n' || 'Une créature entravée par les tentacules peut utiliser son action pour faire un test de Force ou de Dextérité (à elle de choisir) contre le DD de sauvegarde de votre sort. Si elle le réussit, elle parvient à se libérer.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/evardsblacktentacles-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Aura de pureté',
        NULL,
        'Aura of Purity',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle (9 m de rayon)',
        'V',
        'concentration, jusqu''à 10 minutes',
        'Une énergie purificatrice émane de vous et forme une aura dans un rayon de 9 mètres. Cette aura se déplace avec vous jusqu''à la fin du sort et reste centrée sur vous. Chaque créature non hostile qui se trouve dans l''aura (vous y compris) ne peut pas tomber malade, devient résistante aux dégâts de poison et est avantagée sur les jets de sauvegarde contre les effets générant les états suivants : assourdi, aveuglé, charmé, empoisonné, étourdi, paralysé, terrorisé.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/beacon_of_hope_spell_bg3_wiki_guide64px.png'
    ),
    (
        'Aura de vie',
        NULL,
        'Aura of Life',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle (9 m de rayon)',
        'V',
        'concentration, jusqu''à 10 minutes',
        'Une énergie protectrice de vie émane de vous et forme une aura dans un rayon de 9 mètres. Cette aura se déplace avec vous jusqu''à la fin du sort et reste centrée sur vous. Chaque créature non hostile qui se trouve dans l''aura (vous y compris) devient résistante aux dégâts nécrotiques et il est impossible de réduire son maximum de points de vie. De plus,une créature vivante non hostile récupère 1 point de vie quand elle débute son tour au sein de l''aura alors qu''elle a O point de vie.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wardenofvitality-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Bannissement',
        NULL,
        'Banishment',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        '18 mètres',
        'V, S, M (un objet qui répugne à la cible)',
        'concentration, jusqu''à 1 minute',
        'Vous tentez d''envoyer une créature située dans votre champ de vision dans un autre plan d''existence. Elle doit réussir un jet de sauvegarde de Charisme ou se faire bannir.' || E'\n' || 'Si la cible est native du plan d''existence sur lequel vous vous trouvez, vous l''exilez dans un demi-plan inoffensif. Elle est neutralisée tant qu''elle se trouve là-bas et y reste jusqu''à la fin du sort. À ce moment, elle réapparaît à l''endroit qu''elle a quitté ou dans l''emplacement inoccupé le plus proche si son emplacement de départ est occupé.' || E'\n' || 'Si la cible est originaire d''un plan d''existence autre que celui sur lequel vous vous trouvez, une légère détonation accompagne son retour de force sur son plan d''origine. Si le sort se termine avant qu''une minute ne se soit écoulée, la cible réapparaît à l''endroit qu''elle a quitté ou dans l''emplacement inoccupé le plus proche si son emplacement de départ est occupé. Sinon, elle ne revient pas.' || E'\n' || '**À plus haut niveau**, Si vous lancez ce sort en utilisant un emplacement de niveau 5 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 4e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/banishment-spell-bg3-wiki-guide-150px.png'
    ),
    (
        'Frappe assommante',
        'Châtiment débilitant',
        'Staggering Smite',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action bonus',
        'personnelle',
        'V',
        'concentration, jusqu''à 1 minute',
        'Lors de la prochaine attaque armée qui vous permet de toucher une créature pendant la durée du sort, votre arme transperce le corps et l''esprit de la cible et lui inflige 4d6 dégâts psychiques supplémentaires. La cible doit faire un jet de sauvegarde de Sagesse. Si elle échoue, elle est désavantagée lors desjets d''attaque et de caractéristique et ne peut pas utiliser de réaction avant la fin de son prochain tour.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spell_evocation_staggeringsmite_baldurs_gate_3_wiki_guide_65px.png'
    ),
    (
        'Localiser une créature',
        'Localisation de créature',
        'Locate Creature',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'personnelle',
        'V, S, M (des poils de chien de chasse)',
        'concentration, jusqu''à 1 heure',
        'Décrivez ou nommez une créature qui vous est familière. Vous sentez dans quelle direction elle se trouve,à condition qu''elle soit dans un rayon de 300 mètres. Si elle se déplace, vous savez dans quelle direction.' || E'\n' || 'Le sort permet de localiser une créature spécifique de votre connaissance ou la créature la plus proche du même type (comme un humain ou une licorne), mais pour cela, vous devez avoir déjà vu une telle créature de près, c''est-à-dire vous être trouvé à 9 mètres d''elle ou moins au moins une fois dans votre vie. Si la créature que vous décrivez ou nommez se trouve actuellement sous une forme différente, sous l''effet d''un sort de métamorphose par exemple, ce sort est incapable de la localiser.' || E'\n' || 'Le sort ne parvient pas à localiser la créature si le chemin qui vous relie directement est coupé par une étendue d''eau courante d''au moins 3 mètres de large.',
        NULL
    ),
    (
        'Protection contre la mort',
        NULL,
        'Death Ward',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'contact',
        'V, S',
        '8 heures',
        'Vous touchez une créature et lui donnez une protection relative contre la mort.' || E'\n' || 'Quand elle devrait tomber à O point de vie pour la première fois suite à des dégâts, elle tombe à la place à 1 point de vie et le sort se termine.' || E'\n' || 'Si le sort est encore actif quand la cible est soumise à un effet qui devrait la tuer sur-le-champ sans lui infliger de dégâts, l''effet est annulé contre cette cible et le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/deathward-spell-bg3-wiki-guide-64px.png'
    ),
    (
        'Terrain hallucinatoire',
        NULL,
        'Hallucinatory Terrain',
        4,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
        '10 minutes',
        '90 mètres',
        'V, S, M (une pierre,une brindille et un bout de plante verte)',
        '24 heures',
        'Vous maquillez le terrain naturel dans un cube de 45 mètres d''arête situé à portée et lui attribuez l''apparence, les bruits et les odeurs d''un autre type de terrain naturel. Ainsi, vous pouvez faire passer un champ ou une route pour un marais, une colline, une crevasse ou un autre terrain difficile voire impossible à traverser. Vous pouvez aussi déguiser une mare en prairie,un précipice en pente douce ou un goulet semé de rocaille en route large et aplanie. Les structures manufacturées, l''équipement et les créatures de la zone ne changent pas d''apparence.' || E'\n' || 'Les caractéristiques tactiles de la zone ne changent pas, les créatures qui y pénètrent risquent donc fort de percer l''illusion à jour. Si la différence entre le terrain réel et l''illusion n''est pas évidente au toucher, une créature qui examine soigneusement la zone a droit à un test d''Intelligence (Investigation) opposé au DD du jet de sauvegarde de votre sort pour percer l''illusion à jour. Une fois qu''une créature a compris l''illusion, elle la voit comme une image floue superposée au terrain réel.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/evardsblacktentacles-spell-bg3-wiki-guide-64px.png'
    );