INSERT INTO sort (nom_sort,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
(
    'Agrandir/rétrécir',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    '9 mètres',
    'V, S, M (une pincée de limaille de fer)',
    'concentration, jusqu''à 1 minute',
    'Vous agrandissez ou rétrécissez une créature ou un objet situé à portée et dans votre champ de vision pendant toute la durée du sort. Choisissez soit une créature, soit un objet qui n''est ni porté ni transporté. Si la cible n''est pas consentante, elle a droit à un jet de sauvegarde de Constitution. Si elle le réussit, le sort reste sans effet.' || E'\n' || 'Si la cible est une créature, tout ce qu''elle porte et tout ce qu''elle transporte change de taille avec elle. En revanche, si elle lâche un objet, il reprend sa taille normale sur-le-champ.' || E'\n' || '**Agrandir**: La cible double dans toutes les dimensions, et son poids est multiplié par huit. Cette croissance augmente sa catégorie de taille d''un cran, de Moyenne à Grande par exemple. Si la cible n''a pas assez de place pour doubler de volume, elle atteint la taille maximale possible dans l''espace dont elle dispose. Elle est avantagée lors des tests de Force et des jets de sauvegarde de Force jusqu''à la fin du sort. Les armes de la cible grandissent pour s''adapter à sa nouvelle taille. Tant qu''elles sont ainsi agrandies, elles infligent 1d4 dégâts de plus.' || E'\n' || '**Rétrécir**: La cible réduit de moitié dans toutes les dimensions et son poids est divisé par huit. Ce rétrécissement réduit sa catégorie de taille d''un cran, de Moyenne à Petite par exemple. La cible est désavantagée lors des tests de Force et des jets de sauvegarde de Force jusqu''à la fin du sort. Les armes de la cible rétrécissent pour s''adapter à sa nouvelle taille. Tant qu''elles sont ainsi réduites, elles infligent 1d4 dégâts de moins (mais cela ne peut pas faire passer les dégâts en dessous de 1).',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enlarge_reduce_spell_baldurs_gate3_wiki_guide_150px.png'
),
(
    'Amélioration de caractéristique',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    'contact',
    'V, S, M des poils ou des plumes venant d''un animal)',
    'concentration, jusqu''à 1 heure',
    'Vous touchez une créature pour lui accorder une amélioration magique. Choisissez l''un des effets suivants dont la cible bénéficiera jusqu''à la fin du sort.' || E'\n' || '**Endurance de l''ours**: La cible est avantagée lors des tests de Constitution. Elle gagne aussi 2d6 points de vie temporaires qui disparaissent quand le sort se termine.' || E'\n' || '**Force du taureau**: La cible est avantagée lors des tests de Force et sa capacité de charge est doublée.' || E'\n' || '**Grâce du chat**: La cible est avantagée lors des tests de Dextérité. De plus, elle ne subit pas de dégâts quand elle chute sur 6 mètres ou moins, à condition qu''elle ne soit pas neutralisée.' || E'\n' || '**Splendeur de l''aigle**: La cible est avantagée lors des tests de Charisme.' || E'\n' || '**Ruse du renard**: La cible est avantagée lors des tests d''intelligence.' || E'\n' || '**Sagesse du hibou**: La cible est avantagée lors des tests de Sagesse.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez prendre une créature de plus pour cible par niveau au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enhance_ability_spell_baldursgate3_wiki_guide_150px.png'
),
(
    'Bourrasque',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
    '1 action',
    'personnelle (ligne de 18 mètres)',
    'V, S, M (une graine de légume)',
    'concentration, jusqu''à 1 minute',
    'Une zone de vent fort de 18 mètres de long sur 3 de large souffle depuis votre position dans la direction que vous avez choisie pendant toute la durée du sort. Chaque créature commençant son tour dans la zone doit réussir un jet de sauvegarde de Force, sans quoi elle est repoussée de 4,50 mètres à l''opposé de vous, dans la direction où souffle le vent.' || E'\n' || 'Une créature qui se trouve dans la zone doit dépenser 60 centimètres de mouvement pour se rapprocher de vous de 30 centimètres.' || E'\n' || 'La bourrasque disperse les gaz et les vapeurs et éteint les bougies, les torches et autres flammes nues similaires dans la zone. Les flammes protégées, par une lanterne par exemple, s''agitent follement et ont 50% de chance de s''éteindre.' || E'\n' || 'Vous pouvez changer la direction dans laquelle souffle la bourrasque par une action bonus à chacun de vos tours jusqu''à la fin du sort.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/gustofwind-spell-bg3-wiki-guide-64px.png'
),
(
    'Briser',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
    '1 action',
    '18 mètres',
    'V, S, M (un éclat de mica)',
    'instantanée',
    'Un bruit retentit soudain avec une intensité douloureuse, à partir d''un point situé à portée. Chaque créature située dans une sphère de 3 mètres de rayon centrée sur ce point doit faire un jet de sauvegarde de Constitution. Les créatures qui le ratent subissent 3d8 dégâts de tonnerre, les autres la moitié seulement. Une créature faite de matière inorganique, comme de la pierre, du cristal ou du métal est désavantagée sur ce jet de sauvegarde.' || E'\n' || 'Un objet non magique que personne ne porte ni ne transporte subit aussi ces dégâts s''il se trouve dans la zone dun sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 1d8 par niveau au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/shatter_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Cécité/surdité',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
    '1 action',
    '9 mètres',
    'V',
    '1 minute',
    'Vous pouvez rendre un ennemi sourd ou aveugle. Choisissez une créature autre que vous qui se situe à portée et dans votre champ de vision. Elle doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle est soit aveugle, soit sourde (à vous de choisir) pendant toute la durée du sort. Elle a droit à un nouveau jet de sauvegarde de Constitution à la fin de chacun de ses tours, le sort se terminant si elle le réussit' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blindness_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Couronne du dément',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
    '1 action',
    '36 mètres',
    'V, S',
    'concentration, jusqu''à 1 minute',
    'Choisissez un humanoïde situé à portée dans votre champ de vision. Il doit réussir un jet de sauvegarde de Sagesse, sans quoi vous le charmez pendant toute la durée du sort. Tant que la cible est sous votre charme, une couronne tordue en acier dentelé apparaît sur sa tête et une lueur démente brille dans son regard.' || E'\n' || 'À chacun de ses tours, avant de se déplacer, la cible doit utiliser son action pour porter une attaque armée contre une créature (autre qu''elle-même) que vous choisissez mentalement. Si vous ne choisissez pas de créature ou qu''il n''y en a pas à portée, la cible agit normalement.' || E'\n' || 'Lors de vos tours suivants, vous devez utiliser votre action pour garder le contrôle de la cible, sinon le sort se termine. La cible peut faire un jet de sauvegarde de Sagesse à la fin de chacun de ses tours. Si elle réussit, le sort se termine.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/crown_of_madness_enchantment_bg3_spell_wiki_guide64px.png'
),
(
    'Déblocage',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    '18 mètres',
    'V',
    'instantanée',
    'Choisissez un objet situé à portée et dans votre champ de vision. Ce peut être une porte, une boîte, un coffre, des menottes, un cadenas ou un autre objet disposant d''un système de fermeture ordinaire ou magique.' || E'\n' || 'Une cible fermée par une serrure ordinaire, coincée ou bloquée par une barre se déverrouille ou se débloque. Si l''objet a plusieurs serrures, le sort en ouvre une seule.' || E'\n' || 'Si vous visez une cible fermée par un _verrou magique_, ce dernier est supprimé pendant 10 minutes, au cours desquelles on peut ouvrir et fermer la cible normalement.' || E'\n' || 'Quand vous lancez le sort, un cliquetis émane de l''objet et retentit si fort qu''on l''entend dans un rayon de 90 mètres.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/knock_spell_transmutation_school_baldursgate3_wiki_guide_64px.png'
),
(
    'Détection des pensées',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
    '1 action',
    'personnelle',
    'V, S,M (une pièce de cuivre)',
    'concentration, jusqu''à 1 minute',
    'Pendant toute la durée du sort, vous parvenez à lire les pensées de certaines créatures. Quand vous lancez ce sort, puis en tant qu''action à votre tour jusqu''à la fin du sort, vous pouvez focaliser vos pensées sur une créature située dans votre champ de vision et dans un rayon de 9 mètres. Si elle dispose d''une Intelligence de 3 ou moins ou ne parle aucune langue, elle n''est pas affectée.' || E'\n' || 'Au départ, vous découvrez les pensées de surface de la créature, c''est-à-dire ce qu''elle a à i''esprit à ce moment-là. Par une action, vous pouvez tourner votre attention vers les pensées d''une autre créature ou tenter de vous enfoncer plus profondément dans l''esprit de celle que vous sondez actuellement. Dans ce cas, cette créature doit faire un jet de sauvegarde de Sagesse. Si elle échoue,vous avez un aperçu de son mode de raisonnement (le cas échéant), de son état émotionnel ou de ce qui occupe une place importante dans son esprit (par exemple quelque chose qui l''inquiète fortement, qu''elle aime, qu''elle déteste...). Si elle réussit, le sort se termine. Dans les deux cas,la cible sait que vous sondez son esprit et, à moins que vous ne tourniez votre attention vers une autre créature, votre cible peut utiliser son action à son tour pour faire un test d''Intelligence opposé au vôtre. Si elle réussit, le sort se termine.' || E'\n' || 'Les questions directement posées à l''oral à une cible orientent naturellement le cours de ses pensées,ce sort est donc particulièrement utile lors d''un interrogatoire.' || E'\n' || 'Vous pouvez aussi utiliser ce sort pour détecter la présence de créatures intelligentes que vous ne voyez pas. Vous pouvez chercher les pensées qui se trouvent dans un rayon de 9 mètres autour de vous au moment où vous lancez ce sort ou bien par une action tandis que le sort est actif. Le sort peut franchir des obstacles, mais il est arrêté par soixante centimètres de roche, 2,5 centimètres de métal autre que le plomb ou une mince feuille de plomb. Vous ne pouvez pas repérer les créatures dotées d''une Intelligence de 3 ou moins, ni celles qui ne parlent aucune langue.' || E'\n' || 'Une fois que vous avez ainsi détecté la présence d''une créature, vous pouvez lire ses pensées pendant le reste de la durée du sort, comme expliqué plus haut, même si vous ne la voyez pas, mais elle doit tout de même se trouver à portée.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/detect_toughts_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Flou',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
    '1 action',
    'personnelle',
    'V',
    'concentration, jusqu''à 1 minute',
    'Votre corps devient flou, il ondule et vacille comme une flamme aux yeux d''autrui. Pendant toute la durée du sort, les créatures sont désavantagées lorsqu''elles font un jet d''attaque contre vous. Un attaquant est immunisé contre cet effet s''il ne se repose pas sur sa vue, s''il dispose de vision aveugle par exemple, ou s''il peut percer les illusions à jour, avec vision parfaite.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blur_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Force fantasmagorique',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
    '1 action',
    '18 mètres',
    'V, S, M (un peu de laine)',
    'concentration, jusqu''à 1 minute',
    'Vous façonnez une illusion et l''implantez dans l''esprit d''une créature située à portée dans votre champ de vision. Elle doit faire un jet de sauvegarde d''intelligence. Si elle échoue, vous créez un objet, une créature ou un phénomène visible fantasmagorique de votre choix. L''illusion doit tenir dans un cube de 3 mètres d''arête. La cible est seule à la percevoir, et ce pendant toute la durée du sort. Ce dernier ne fonctionne pas contre les morts-vivants ni les créatures artificielles.' || E'\n' || 'L''illusion comprend des bruits, une température et d''autres stimuli, mais, de même, la cible du sort est la seule à les percevoir.' || E'\n' || 'La cible peut utiliser une action pour examiner l''illusion avec un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort. Si elle réussit son test, elle comprend qu''elle a affaire à une simple illusion et le sort se termine.' || E'\n' || 'Tant que la cible est sous l''effet du sort, elle traite l''illusion comme un élément réel et invente une explication rationnelle aux résultats illogiques issus de ses interactions avec elle. Par exemple, si elle tente de traverser un pont fantasmagorique enjambant un ravin et tombe dès qu''elle pose le pied sur ce pont, si elle survit à la chute, elle croit toujours que le pont est réel et trouve une explication logique à sa chute : on l''a poussée, elle a glissé, une forte bourrasque l''a fait basculer...' || E'\n' || 'Une cible affectée croit si fort à la réalité de l''illusion que cette dernière peut même la blesser. Une illusion créée à l''image d''une créature peut attaquer la cible. De même, une illusion représentant du feu, un bassin d''acide ou une nappe de lave peut brûler la cible. À chaque round, à votre tour, votre illusion inflige 1d6 dégâts psychiques à la cible si elle se trouve au sein de l''illusion ou dans un rayon de 1,50 mètre autour d''elle et que cette illusion représente une créature ou un danger qui devrait logiquement la blesser, en l''attaquant par exemple. La cible perçoit les dégâts comme étant d''un type approprié à l''illusion qu''elle voit.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/phantasmal_force_spell_bg3_wiki_guide_75px.png'
),
(
    'Image miroir',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
    '1 action',
    'personnelle',
    'V, S',
    '1 minute',
    'Trois répliques illusoires de votre personne apparaissent dans votre emplacement. Jusqu''à la fin du sort, ces répliques se déplacent en même temps que vous et imitent toutes vos actions, changeant de position de manière à ce qu''il soit impossible de savoir quelles versions de vous sont des images et quelle version est réelle. Vous pouvez utiliser une action pour révoquer les répliques illusoires.' || E'\n' || 'Pendant toute la durée du sort, chaque fois qu''une créature vous prend pour cible d''une attaque, vous devez lancer 1d20 pour savoir si l''attaque touche votre personne ou l''un de vos doubles.' || E'\n' || 'Si vous avez trois répliques, vous devez obtenir 6 ou plus pour que l''attaque touche une réplique. Si vous n''en avez plus que deux, vous devez faire 8 ou plus et si vous n''en avez plus qu''une, vous devez faire 11 ou plus.' || E'\n' || 'Chaque réplique possède une CA de 10 + votre modificateur de Dextérité. Si l''attaque touche une réplique, elle la détruit. Le seul moyen de détruire une réplique est de la toucher avec une attaque, car elle ignore tous les autres effets et dégâts. Le sort se termine quand les trois répliques sont détruites.' || E'\n' || 'Une créature n''est pas affectée par ce sort si elle ne voit pas, si elle se sert d''un mode de perception autre que la vue (comme la vision aveugle) ou encore si elle perçoit les illusions comme telles avec vision parfaite, par exemple.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/mirror_image_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Immobiliser un humanoïde',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
    '1 action',
    '18 mètres',
    'V, S, M (un petit morceau de fer bien droit)',
    'concentration, jusqu''à 1 minute',
    'Choisissez un humanoïde situé à portée et dans votre champ de vision. Il doit réussir un jet de sauvegarde de Sagesse, sans quoi il est paralysé pour toute la durée du sort. À la fin de chacun de ses tours, la cible a droit à un nouveau jet de sauvegarde de Sagesse. Si eUe le réussit, le sort se termine.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser un humanoïde de plus par niveau au-delà du 2e. Les humanoïdes visés doivent se trouver à 9 mètres ou moins les uns des autres au moment où vous lancez le sort.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/hold_person_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Invisibilité',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Illusion'),
    '1 action',
    'contact',
    'V, S, M (un cil enrobé de gomme arabique)',
    'concentration, jusqu''à 1 heure',
    'La créature que vous touchez devient invisible jusqu''à la fin du sort. Tout ce qu''elle porte et transporte reste invisible tant qu''elle le garde sur elle. Le sort se termine pour la cible qui attaque ou lance un sort.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous pouvez viser une créature de plus par niveau au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/invisivility_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Lévitation',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    '18 mètres',
    'V, S, M (soit une petite boucle de cuir, soit un bout de fil de métal doré formant la silhouette d''une cuillère au long manche)',
    'concentration, jusqu''à 10 minutes',
    'Une créature ou un objet situé à portée et dans votre champ de vision s''élève à la verticale à une hauteur de 6 mètres et reste suspendu là pendant toute la durée du sort. Ce dernier peut soulever une cible d''au maximum 250 kilos. Si la créature visée n''est pas consentante, elle doit réussir un jet de sauvegarde de Constitution pour que le sort ne l''affecte pas.' || E'\n' || 'La cible peut se déplacer uniquement en se propulsant ou se tractant en prenant appui sur un objet fixe ou une surface à proximité (comme un mur ou un plafond). Elle se meut alors comme si elle était en pleine escalade. Quand vient votre tour, vous pouvez modifier l''altitude de la cible d''un maximum de 6 mètres dans la direction de votre choix. Si vous êtes la cible, vous pouvez monter ou descendre lors de votre déplacement. En dehors de cela, vous devez dépenser une action pour déplacer la cible qui doit rester dans le rayon de portée du sort. Si la cible est encore en l''air quand le sort se termine, elle flotte délicatement jusqu''au sol.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/telekinesis-spell-bg3-wiki-guide-64px.png'
),
(
    'Modifier son apparence',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    'personnelle',
    'V, S',
    'concentration, jusqu''à 1 heure',
    'Vous revêtez une forme différente. Quand vous lancez ce sort, choisissez l''une des options suivantes, dont les effets dureront aussi longtemps que le sort. Tant qu''il est actif, vous pouvez utiliser une action pour mettre un terme à une option afin de bénéficier d''une autre.' || E'\n' || '**Adaptation aquatique**: Vous adaptez votre corps à un environnement aquatique, générant des branchies et des palmures entre vos doigts. Vous pouvez respirer sous l''eau et gagnez une vitesse de nage égale à votre vitesse de marche.' || E'\n' || '**Changer d''apparence**: Vous modifiez votre apparence et choisissez votre taille, votre poids, vos traits, le son de votre voix, la longueur de vos cheveux, votre pigmentation, et toute caractéristique distinctive désirée. Vous pouvez vous faire passer pour un membre d''une autre race, mais vos caractéristiques ne changent pas. Vous ne pouvez pas vous faire passer pour une créature d''une catégorie de taille différente de la vôtre, et votre silhouette générale doit rester la même (par exemple, si vous êtes un bipède, vous ne pouvez pas utiliser ce sort pour prendre l''apparence d''un quadrupède). À tout moment lors de la durée du sort, vous pouvez dépenser une action pour modifier de nouveau votre apparence de cette manière.' || E'\n' || '**Armes naturelles**: Vous gagnez des griffes, des crocs, des épines, des cornes ou une autre arme naturelle de votre choix. Vos attaques à mains nues infligent 1d6 dégâts contondants, perforants ou tranchants, comme il sied à l''arme naturelle que vous avez choisie et vous maîtrisez automatiquement les attaques à mains nues. Enfin, votre arme naturelle est de nature magique et vous disposez d''un bonus de +1 aux jets d''attaque et de dégâts quand vous l''utilisez.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/polymorph-spell-bg3-wiki-guide-64px.png'
),
(
    'Nuée de dagues',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
    '1 action',
    '18 mètres',
    'V, S, M (un éclat de verre)',
    'concentration, jusqu''à 1 minute',
    'Vous emplissez de dagues tournoyantes un cube de 1,50 mètre d''arête. Ce cube est centré sur un point de votre choix situé à portée. Une créature subit 4d4 dégâts tranchants quand elle entre dans la zone du sort pour la première fois d''un tour ou quand elle y débute son tour.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, les dégâts augmentent de 2d4 par emplacement de sort au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/cloud_of_daggers_spells_bg3_wiki_guide64px.png'
),
(
    'Pattes d''araignée',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    'contact',
    'V, S, M (une goutte de bitume et une araignée)',
    'concentration, jusqu''à 1 heure',
    'Jusqu''à la fin du sort, une créature consentante que vous touchez devient capable de se déplacer sur les surfaces verticales, et même au plafond la tête en bas, tout en gardant les mains libres. La cible bénéficie aussi d''une vitesse d''escalade égale à sa vitesse de marche.',
    NULL
),
(
    'Rayon ardent',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
    '1 action',
    '36 mètres',
    'V, S',
    'instantanée',
    'Vous créez trois rayons de feu et les projetez sur des cibles à portée. Vous pouvez les diriger contre une même cible ou contre des cibles différentes.' || E'\n' || 'Faites une attaque de sort à distance pour chaque rayon. Si vous touchez, la cible reçoit 2d6 dégâts.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 3 ou plus, vous créez un rayon de plus par niveau au-delà du 2e.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/scorching_ray_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Suggestion',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
    '1 action',
    '9 mètres',
    'V, M (une langue de serpent et un rayon de miel ou une goutte d''huile d''olive)',
    'concentration, jusqu''à 8 heures',
    'Vous visez une créature située à portée dans votre champ de vision et à même de vous entendre et de vous comprendre. Vous l''influencez par magie de façon à ce qu''elle suive la conduite que vous lui proposez (en seulement une phrase ou deux). Les créatures insensibles au charme sont immunisées contre ce sort. Vous devez formuler votre suggestion de manière à ce que la conduite à tenir semble tout à fait raisonnable. Si vous demandez à une créature de se poignarder, de se laisser tomber sur une lance, de s''immoler ou d''accomplir n''importe quelle action à l''évidence néfaste, le sort se termine automatiquement.' || E'\n' || 'La cible doit faire un jet de sauvegarde de Sagesse. En cas d''échec, elle fait de son mieux pour suivre la conduite que vous lui avez suggérée et cela peut continuer pendant toute la durée du sort. Si l''activité suggérée peut se finir plus rapidement, le sort se termine quand la cible a accompli ce que vous lui avez demandé.' || E'\n' || 'Vous pouvez spécifier des conditions qui déclenchent une activité spéciale pendant la durée du sort. Par exemple, vous pouvez suggérer à un chevalier de donner son cheval de guerre au premier mendiant qu''il rencontre. Si les conditions ne sont pas remplies avant la fin du sort, la cible n''accomplit pas l''activité.' || E'\n' || 'Si vous (ou l''un de vos compagnons) blessez une créature affectée par ce sort, le sort se termine.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/enthrall-spell-bg3-wiki-guide-64px.png'
),
(
    'Ténèbres',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
    '1 action',
    '18 mètres',
    'V, M (des poils de chauve-souris et une goutte de poix ou un bout de charbon)',
    'concentration, jusqu''à 10 minutes',
    'Des ténèbres magiques se répandent depuis un point de votre choix situé à portée, jusqu''englober une sphère de 4,50 mètres de rayon. Les ténèbres s''étendent en franchissant tout angle éventuel. La vision dans le noir d''une créature ne suffit pas à percer ces ténèbres et les lumières non magiques se révèlent incapables de les éclairer.' || E'\n' || 'Si le point que vous avez choisi est un objet en votre possession ou un objet qui n''est ni porté ni transporté par autrui, les ténèbres émanent de l''objet et se déplacent avec lui. Il suffit de recouvrir complètement l''objet affecté avec un objet opaque, comme un bol ou un heaume, pour bloquer les ténèbres.' || E'\n' || 'Si une partie de la zone affectée par ce sort chevauche une zone de lumière issue d''un sort de niveau 2 ou moins, elle dissipe le sort de lumière.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/darkness_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Toile d''araignée',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
    '1 action',
    '18 mètres',
    'V, S, M (un bout de toile d''araignée)',
    'concentration, jusqu''à 1 heure',
    'Vous invoquez une masse de toiles d''araignées épaisses et collantes en un point de votre choix situé à portée. Pendant toute la durée du sort, les toiles occupent un cube de 6 mètres d''arête centré sur le point choisi. Elles forment un terrain difficile à la visibilité légèrement obstruée.' || E'\n' || 'Si les toiles ne sont pas ancrées entre deux éléments solides, comme des murs ou des arbres, ou disposées en couches sur le sol, le plafond ou un mur, elles s''effondrent sur elles-mêmes et le sort se termine au début de votre prochain tour. Des toiles disposées en couches superposées sur une surface plane s''accumulent sur une épaisseur de 1,50 mètre.' || E'\n' || 'Chaque créature qui commence son tour dans les toiles ou qui y pénètre lors de son tour doit faire un jet de sauvegarde de Dextérité. En cas d''échec, la créature est entravée tant qu''elle reste dans les toiles ou jusqu''à ce qu''elle se libère.' || E'\n' || 'Une créature entravée par les toiles peut utiliser son action pour faire un test de Force contre le DD du jet de sauvegarde de votre sort. Si elle le réussit, elle n''est plus entravée.' || E'\n' || 'Les toiles sont inflammables. Un cube de toiles de 1,50 mètre d''arête exposé au feu brûle en 1 round, infligeant 2d4 dégâts de feu à toute créature qui commence son tour dans les flammes.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/web_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Vision dans le noir',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
    '1 action',
    'contact',
    'V, S, M (une pincée de carotte séchée ou une agate)',
    '8 heures',
    'Vous touchez une créature consentante pour lui permettre de voir dans le noir. Pendant toute la durée du sort, elle bénéficie de la vision dans le noir à une portée de 18 mètres.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/darkvision_spell_baldursgate3_wiki_guide_150px_2.png'
),
(
    'Voir l''invisible',
    2,
    (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
    '1 action',
    'personnelle',
    'V, S, M (une pincée de talc et un saupoudrage de poudre d''argent)',
    '1 heure',
    'Pendant toute la durée du sort, vous voyez les créatures et les objets invisibles comme s''ils étaient bien visibles et vous pouvez aussi observer le plan éthéré. Les créatures et les objets éthérés vous apparaissent comme des silhouettes translucides ët fantomatiques.',
    'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/seeinvisibility_spell_divination_school_baldursgate3_wiki_guide_64px.png'
);