INSERT INTO sort (nom_sort,alias,nom_sort_en,niveau_sort,ecole_sort,duree_incantation,portee,composantes,duree_sort,description,img_sort)
VALUES
    (
        'Danse irrésistible d''Otto',
        NULL,
        'Otto''s Irresistible Dance',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Enchantement'),
        '1 action',
        '9 mètres',
        'V',
        'concentration, jusqu''à 1 minute',
        'Choisissez une créature située à portée dans votre champ de vision. La cible entame une danse comique, se mettant à taper du pied et à caracoler sur place.' || E'\n' || 'Les créatures insensibles au charme sont immunisées contre ce sort.' || E'\n' || 'Une fois que la créature s''est mise à danser, elle doit dépenser la totalité de son déplacement pour danser sans quitter son espace. De plus, elle est désavantagée lors des jets de sauvegarde de Dextérité et des jets d''attaque. Tant que la cible est affectée par ce sort, les autres créatures sont avantagées par rapport à elle lors des jets d''attaque. Une créature en train de danser peut utiliser son action pour faire un jet de sauvegarde de Sagesse et reprendre le contrôle de son corps. Si elle réussit, le sort se termine.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/ottosirresistibledance_spell_enchantment_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Illusion programmée',
        NULL,
        'Programmed Illusion',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Illusion'),
        '1 action',
        '36 mètres',
        'V, S,M (un morceau de toison et de la poussière de jade d''une valeur de 25 po)',
        'jusqu''à dissipation',
        'Vous créez une illusion représentant un objet, une créature ou un autre phénomène visible à portée. Elle s''active une fois les conditions spécifiques remplies; en attendant, elle est imperceptible. L''illusion doit tenir dans un cube de 9 mètres d''arête. Vous décidez de son comportement et des sons qu''elle émet au moment où vous lancez le sort. Ce comportement programmé peut durer un maximum de 5 minutes.' || E'\n' || 'Quand les conditions spécifiées se présentent, l''illusion apparaît et se comporte comme vous l''avez décidé. Sa représentation finie, elle disparaît et reste en hibernation pendant 10 minutes. Ensuite, elle peut se réactiver de nouveau.' || E'\n' || 'Les conditions de déclenchement peuvent être aussi génériques ou détaillées que vous le souhaitez, mais elles doivent toujours se baser sur des éléments visuels ou audibles se produisant dans un rayon de 9 mètres autour de la zone du sort. Par exemple, vous pouvez créer une illusion de vous-même qui apparaît pour avertir d''autres gens quand ils tentent d''ouvrir une porte piégée, ou vous pouvez programmer votre illusion pour qu''elle se déclenche seulement quand une créature prononce le mot de passe correct.' || E'\n' || 'Les interactions physiques révèlent que l''image n''est qu''une illusion, car les objets la traversent. Si une créature utilise son action pour examiner l''image, elle comprend que c''est une illusion, à condition de réussir un test d''Intelligence (Investigation) contre le DD du jet de sauvegarde de votre sort. Si une créature perce l''illusion à jour, elle voit à travers l''image et les sons produits par l''illusion sonnent creux à ses oreilles.',
        NULL
    ),
    (
        'Protections et sceaux',
        NULL,
        'Guards and Wards',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '10 minutes',
        'contact',
        'V,S, M (encens incandescent, petite dose de soufre et d'' huile, cordelette avec des nœuds, petite dose de sang de mastodonte des ombres et petit sceptre en argent d''une valeur minimale de 10 po)',
        '24 heures',
        'Vous créez un sceau protégeant une zone au sol de 225 m2 (soit une zone de 15 mètres de côté, soit une centaine de zones de 1,50 mètre de côté, soit vingt-zones de 3 mètres de côté). La zone protégée fait au maximum 6 mètres de haut et prend la forme de votre choix. Vous pouvez protéger ainsi plusieurs étages d''une place forte en répartissant la zone affectée entre eux tant que vous pouvez relier toutes les zones contiguës en marchant lorsque vous lancez le sort.' || E'\n' || 'Lors de l''incantation, vous pouvez définir quels individus ne seront pas affectés par un ou tous les effets du sort. Vous pouvez aussi choisir un mot de passe qui immunise celui qui le prononce à haute voix contre ces effets.' || E'\n' || '_Protections et sceaux_ produit les effets suivants dans la zone protégée.' || E'\n' || '**Couloirs**: Le brouillard envahit tous les couloirs où la visibilité est alors fortement obstruée. De plus, à chaque intersection ou embranchement laissant un choix de direction, il y a 50% de chances que les créatures autres que vous soient persuadées d''aller dans la direction opposée à celle qu''elles ont choisie.' || E'\n' || '**Portes**: Toutes les portes de la zone protégée sont fermées par magie, comme scellées avec un verrou magique. De plus, vous pouvez recouvrir jusqu''à dix portes d''une illusion (comme la fonction d''objet illusoire du sort _illusion mineure_), afin de les faire passer pour une section de mur ordinaire.' || E'\n' || '**Escaliers**: Des toiles d''araignées, comme le sort du même nom, emplissent tous les escaliers de la zone protégée,du sol au plafond. Tant que _protections et sceaux_ persiste, ces fils repoussent en 10 minutes si quelqu''un les brûle ou les arrache.' || E'\n' || '**Autres effets de sort** Vous pouvez placer l''un des effets suivants, au choix, dans la zone protégée par le sort.' || E'\n' || '* Placer _lumières dansantes_ dans quatre couloirs. Vous pouvez choisir un programme très simple que les lumières suivront pendant toute la durée de _protections et sceaux_.' || E'\n' || '* Placer une _bouche magique_ en deux endroits.' || E'\n' || '* Placer un _nuage puant_ en deux endroits. Les vapeurs apparaissent à l''endroit de votre choix. Tant que _protections et sceaux_ persiste, elles réapparaissent au bout de 10 minutes si le vent les disperse.' || E'\n' || '* Placer une _bourrasque_ constante dans un couloir ou une pièce.' || E'\n' || '* Placer une _suggestion_ en un endroit. Choisissez une zone d''au maximum 1,50 mètre de côté : toute créature qui y pénètre ou la traverse reçoit une suggestion mentale.' || E'\n' || 'Toute la zone protégée émet une aura magique. Si quelqu''un lance avec succès une _dissipation de la magie_ sur un effet spécifique, il élimine seulement cet effet.' || E'\n' || 'Vous pouvez protéger une structure en permanence si vous lancez ce sort tous les jours pendant un an.',
        NULL
    ),
    (
        'Trouver un chemin',
        'Sens de l''orientation',
        'Find the Path',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Divination'),
        '1 minute',
        'personnelle',
        'V, S, M (un ensemble d''instruments de divination [comme des os, des bâtonnets en ivoire, des cartes, des dents ou des runes gravées] d''une valeur de 100 po et un objet venant de l''endroit que vous cherchez)',
        'concentration, jusqu''à 1 jour',
        'Ce sort vous permet de trouver le chemin physique le plus direct et le plus court vers un endroit fixe spécifique avec lequel vous êtes familier et qui se trouve sur le même plan d''existence que vous. Le sort échoue si vous choisissez une destination située sur un autre plan d''existence, une destination mouvante (comme une forteresse mobile) ou une destination n''ayant rien de spécifique (comme l''antre d''un dragon vert).' || E'\n' || 'Tant que le sort persiste et que vous êtes sur le même plan d''existence que votre destination, vous savez dans quelle direction et à quelle distance elle se trouve. Tant que vous faites route vers votre destination, chaque fois que vous avez le choix entre plusieurs itinéraires, vous déterminez automatiquement celui qui sera le plus court et le plus direct (mais pas forcément le plus sûr).',
        NULL
    ),
    (
        'Allié planaire',
        NULL,
        'Planar Ally',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '10 minutes',
        '18 mètres',
        'V, S',
        'instantanée',
        'Vous demandez de l''aide à une entité appartenant à un autre monde. Vous devez connaître cet être, que ce soit un dieu, un primordial, un prince démoniaque ou une autre créature à la puissance cosmique. L''entité vous envoie un céleste, un élémentaire ou un fiélon qui lui est loyal. Cette créature apparaît dans un emplacement libre à portée. Si vous connaissez le nom d''une créature spécifique, vous pouvez le mentionner lors de l''incantation pour demander à ce que ce soit elle que l''entité vous envoie, bien qu''elle puisse tout de même vous envoyer un autre émissaire (au MD de décider).' || E'\n' || 'Quand la créature apparaît, elle n''a aucune obligation de se comporter d''une manière particulière. Vous pouvez lui demander d''accomplir un service rémunéré, mais elle n''est pas obligée d''accepter. Votre requête peut être très simple (nous faire passer en volant au-dessus de ce précipice, nous aider à livrer un combat...) ou plus complexe (espionner nos ennemis, nous protéger lors de l''exploration de ce donjon...). Pour négocier un service, vous devez être en mesure de communiquer avec la créature.' || E'\n' || 'Le paiement peut se faire sous diverses formes. Un céleste peut demander une importante donation en or ou en objets magiques à un temple allié tandis qu''un fiélon peut exiger un sacrifice vivant ou un trésor. Certaines créatures monnayent leurs services contre une quête à accomplir de votre côté.' || E'\n' || 'En règle générale, une tâche qui s''accomplit en quelques minutes se paie 100 po la minute. Une tâche qui demande plusieurs heures coûte 1 000 po de l''heure, et une tâche effectuée sur plusieurs jours (10 au maximum) vaut 10 000 po la journée. Le MD peut modifier le montant en fonction des circonstances dans lesquelles vous lancez le sort. Si la tâche à accomplir s''accorde avec l''éthique de la créature, elle peut réduire son salaire de moitié ou même y renoncer. Les tâches qui ne présentent aucun risque coûtent souvent la moitié du prix indiqué précédemment tandis que les missions particulièrement dangereuses valent parfois bien plus cher. Une créature accepte rarement une tâche visiblement suicidaire.' || E'\n' || 'Une fois que la créature a accompli la tâche demandée ou quand la durée de service décidée est arrivée à son terme, elle retourne sur son plan d''origine après vous avoir fait son rapport, si la tâche l''exige et qu''elle est en mesure de le faire.' || E'\n' || 'Si vous êtes incapable de vous mettre d''accord avec la créature sur le prix de ses services, elle retourne immédiatement sur son plan natal.' || E'\n' || 'Une créature enrôlée dans votre groupe compte comme un membre à part entière et reçoit sa part de points d''expérience.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/planar-ally-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Barrière de lames',
        NULL,
        'Blade Barrier',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '27 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Vous créez un mur vertical constitué de lames toumoyantes faites d''énergie magique et tranchantes comme des rasoirs. Le mur apparaît à portée et persiste pour toute la durée du sort. Vous pouvez créer un mur droit d''un maximum de 30 mètres de long, 6 mètres de haut et 1,50 mètre d''épaisseur, ou un mur circulaire d''un maximum de 18 mètres de diamètre, 6 mètres de haut et 1,50 mètre d''épaisseur. Le mur offre un abri important aux créatures qui se trouvent derrière lui, et son espace est traité comme un terrain difficile.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blade-barrier-spells-bg3-wiki-guide.png'
    ),
    (
        'Contamination',
        NULL,
        'Harm',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 action',
        '18 mètres',
        'V, S',
        'instantanée',
        'Vous transmettez une maladie virulente à une créature située à portée dans votre champ de vision. La cible doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle subit 14d6 dégâts nécrotiques, la moitié seulement si elle réussit. Ces ne peuvent pas faire passer les points de vie de la cible au-dessous de 1. Si la cible rate son jet de sauvegarde, son total de points de vie maximum est réduit, pendant 1 heure, d''un montant égal aux dégâts nécrotiques reçus. Tout effet qui guérit les maladies ramène le maximum de points de vie de la cible à la normale sans avoir besoin d''attendre une heure.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/harm-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Festin des héros',
        NULL,
        'Heroes'' Feast',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '10 minutes',
        '9 mètres',
        'V, S, M (un bol incrusté de gemmes d''une valeur minimale de 1 000 po, que le sort consume)',
        'instantanée',
        'Vous matérialisez un grand festin, comprenant des boissons et des mets de grande qualité. Il faut une heure pour terminer le festin qui disparaît au bout de cette durée. Ses effets bénéfiques se manifestent uniquement une fois cette heure écoulée. Douze créatures au maximum peuvent vous accompagner lors de ce repas.' || E'\n' || 'Une créature qui participe au festin bénéficie de plusieurs avantages. Elle est guérie de toutes les maladies et de tous les poisons qui l''affectaient, elle est immunisée contre le poison et l''état terrorisé, et elle est avantagée lors de tous ses jets de sauvegarde de Sagesse. Son maximum de points de vie augmente de 2d10 et elle gagne le même nombre de points de vie. Ces avantages persistent pendant 24 heures.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spell_conjuration_heroesfeast_(2)_baldurs_gate_3_wiki_guide_65px.png'
    ),
    (
        'Guérison',
        NULL,
        'Heal',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '18 mètres',
        'V, S',
        'instantanée',
        'Choisissez une créature située à portée dans votre champ de vision. Une bouffée d''énergie positive la traverse et lui rend 70 points de vie. Ce sort met aussi un terme à la cécité, la surdité et toutes les maladies qui l''affectent. Ce sort n''a aucun effet sur les créatures artificielles et les morts-vivants.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, la quantité de soins prodigués augmente de 10 points par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/heal-spells-bg3-wiki-guide-min.png'
    ),
    (
        'Interdiction',
        NULL,
        'Forbiddance',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Abjuration'),
        '10 minutes',
        'contact',
        'V, S, M (un peu d''eau bénite, un encens rare et un rubis en poudre d''une valeur minimale de 1 000 po)',
        '1 jour',
        'Vous créez un sceau empêchant les déplacements magiques dans une zone de 3 700 m2 au sol et d''une hauteur de 9 mètres. Pendant toute la durée du sort, les créatures ne peuvent pas se téléporter dans la zone ni y entrer via un portail comme celui issu du sort du même nom. Le sort protège la zone contre tous les modes de déplacement planaire et empêche donc les créatures d''y entrer en passant par le plan astral, le plan éthéré, la Féerie sauvage, !''Obscur ou en utilisant un sort de _changement de plan_.' || E'\n' || 'De plus, le sort blesse les créatures des types choisis lors de son incantation. Choisissez un ou plusieurs de ces types : célestes, élémentaires, fées, fiélons, morts-vivants. Quand une créature d''un type choisi pénètre dans la zone pour la première fois de son tour ou y commence son tour, elle subit 5d10 dégâts radiants ou nécrotiques (à vous de choisir quand vous lancez le sort).' || E'\n' || 'Vous pouvez décider d''un mot de passe lors de l''incantation du sort. Si une créature le prononce en entrant dans la zone, elle ne subit pas de dégâts.' || E'\n' || 'La zone d''effet de ce sort ne peut pas se superposer à celle d''un autre sort d''interdiction. Si vous lancez interdiction tous les jours pendant 30 jours au même endroit, le sort persiste jusqu''à dissipation et les composantes matérielles sont consommées lors de la dernière incantation.',
        NULL
    ),
    (
        'Mot de retour',
        NULL,
        'Word of Recall',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 action',
        '1,50 mètre',
        'V',
        'instantanée',
        'Vous et un maximum de cinq créatures consentantes situées dans un''rayon de 1,50 mètre autour de vous vous téléportez immédiatement dans un sanctuaire précédemment choisi. Vous et les créatures qui se téléportent éventuellement avec vous apparaissez dans l''emplacement inoccupé le plus proche de l''endroit que vous avez désigné lorsque vous avez préparé votre sanctuaire (voir plus bas). Si vous lancez ce sort sans avoir préparé un sanctuaire au préalable, il n''a aucun effet.' || E'\n' || 'Pour désigner un sanctuaire, vous devez lancer ce sort en un lieu dédié à votre divinité, comme un temple, ou entretenant des liens étroits avec elle. Si vous tentez de lancer ainsi le sort dans une zone qui n''est pas dédiée à votre divinité, il n''a aucun effet.',
        NULL
    ),
    (
        'Marche sur le vent',
        'Vent divin',
        'Wind Walk',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 minute',
        '9 mètres',
        'V, S, M (du feu et de l''eau bénite)',
        '8 heures',
        'Vous et un maximum de dix créatures consentantes, situées à portée et dans votre champ de vision, prenez une forme gazeuse pendant toute la durée du sort et ressemblez à des volutes de nuages. Sous cette forme, une créature affectée a une vitesse de vol de 90 mètres et une résistance aux dégâts des armes non magiques. Elle est limitée dans ses actions : elle peut juste se précipiter ou reprendre sa forme normale. Il lui faut une minute pour reprendre sa forme normale et, pendant toute cette période, elle est neutralisée et incapable de bouger. Elle peut de nouveau se muer en nuage tant que le sort n''est pas terminé, cette nouvelle transformation lui demandant aussi une minute.' || E'\n' || 'Si une créature est sous forme de nuage et en plein vol quand le sort se termine, elle descend de 18 mètres par round pendant 1 minute, jusqu''à ce qu''elle atterrisse, en parfaite sécurité. Si elle n''arrive pas à atterrir avant la fin de cette minute, elle tombe sur la distance qui lui reste à parcourir.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spell_transmutation_windwalk_baldurs_gate_3_wiki_guide_65px.png'
    ),
    (
        'Mur d''épines',
        NULL,
        'Wall of Thorns',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '36 mètres',
        'V, S, M (une poignée d''épines)',
        'concentration,jusqu''à 10 minutes',
        'Vous créez un mur fait de buissons souples et robustes, enchevêtrés et hérissés d''épines acérées. Il apparaît à portée sur une surface solide et persiste pendant toute la durée du sort. Vous pouvez faire un mur de 18 mètres de long, 3 mètres de haut et 1,50 mètre d''épaisseur, ou le disposer en un cercle de 6 mètres de diamètre pour une hauteur maximum de 6 mètres et une épaisseur de 1,50 mètre. Le mur bloque le champ de vision.' || E'\n' || 'Quand le mur apparaît, chaque créature située dans sa zone doit faire un jet de sauvegarde de Dextérité. Celles qui échouent subissent 7d8 dégâts perforants, les autres la moitié seulement.' || E'\n' || 'Une créature peut traverser le mur, mais lentement et dans la douleur. Elle doit dépenser 1,20 mètre de déplacement pour avancer de 30 centimètres au sein du mur. De plus, quand elle entre dans le mur pour la première fois de son tour ou quand elle y termine son tour, elle doit faire un jet de sauvegarde de Dextérité. Elle subit 7d8 dégâts perforants si elle rate son jet, la moitié si elle le réussit.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, les deux types de dégâts augmentent chacun de 1d8 par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/spell_wallofthorns_baldurs_gate_3_wiki_guide_65px.png'
    ),
    (
        'Transport végétal',
        'Voie végétale',
        'Transport via Plants',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '3 mètres',
        'V, S',
        '1 round',
        'Ce sort crée un lien magique entre une plante inanimée de taille Grande ou supérieure située à portée et une autre plante, située à n''importe quelle distance mais sur le même plan d''existence. Vous devez impérativement avoir vu ou touché la plante de destination au moins une fois auparavant. Pendant toute la durée du sort, n''importe quelle créature peut entrer par la plante de départ et ressortir par celle d''arrivée en dépensant 1,50 mètre de déplacement.',
        NULL
    ),
    (
        'Cercle de mort',
        NULL,
        'Circle of Death',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        '45 mètres',
        'V, S, M (la poudre d''une perle noire broyée d''une valeur minimale de 500 po)',
        'instantanée',
        'Une sphère d''énergie négative s''étend dans un rayon de 18 mètres à partir d''un point situé à portée. Chaque créature située dans la sphère doit faire un jet de sauvegarde de Constitution. Celles qui échouent subissent 8d6 dégâts nécrotiques, les autres la moitié seulement.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, les dégâts augmentent de 2d6 par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/circleofdeath_spell_necromancy_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Chaine d''éclairs',
        'Chaîne d''éclairs',
        'Chain Lightning',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        '450 mètres',
        'V, S, M ( un éclat d''ambre, de verre ou de cristal, trois épingles en argent et un morceau de fourrure )',
        'instantanée',
        'Vous créez un arc électrique qui file vers une cible de votre choix, située à portée dans votre champ de vision. Trois éclairs bondissent ensuite de cette cible sur un maximum de trois autres cibles qui doivent toutes se trouver dans un rayon de 9 mètres autour de la première. Une cible peut être une créature ou un objet et ne peut recevoir qu''un seul éclair.' || E'\n' || 'Chaque cible doit faire un jet de sauvegarde de Dextérité et subit 10d8 dégâts de foudre en cas d''échec, la moitié en cas de réussite.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, un éclair de plus bondit de la première cible vers une autre pour chaque niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/chainlightning_spell_evocation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Déplacer la terre',
        'Terraformage',
        'Move Earth',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '36 mètres',
        'V, S, M (une lame de fer et un petit sac contenant un mélange de terres : de l''argile, du terreau et du sable)',
        'concentration, jusqu''à 2 heures',
        'Choisissez une zone de terrain à portée d''un maximum de 12 mètres de côté. Vous pouvez remodeler la terre, le sable ou l''argile qu''elle comporte comme bon vous semble pendant toute la durée du sort. Vous pouvez augmenter ou diminuer l''altitude de la zone, creuser ou combler une tranchée, ériger ou abattre un mur, ou former un pilier. L''amplitude de ces modifications ne peut pas excéder la moitié de la dimension la plus importante de la zone affectée. Donc, si vous modifiez une zone de 12 mètres de côté, vous pouvez créer un pilier de 6 mètres de haut au maximum, modifier l''altitude de la zone de 6 mètres au plus, creuser une tranchée d''un maximum de 6 mètres de profondeur, etc. Il faut 10 minutes pour finaliser ces modifications.' || E'\n' || 'Au bout de chaque période de 10 minutes passées à vous concentrer sur le sort, vous pouvez choisir une nouvelle zone de terrain à modifier.' || E'\n' || 'Comme les transformations se produisent lentement, il est bien rare qu''une créature se retrouve piégée ou blessée à cause des mouvements du terrain.' || E'\n' || 'Ce sort est incapable de manipuler la pierre naturelle et les constructions de pierre. La roche et les structures s''adaptent au nouvel agencement du terrain. Si vos modifications déstabilisent une structure, elle peut très bien s''effondrer.' || E'\n' || 'De même, le sort n''affecte pas directement la croissance des plantes. La terre déplacée emporte les végétaux avec elle.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/dethrone-bg3-wiki-guide.png'
    ),
    (
        'Désintégration',
        NULL,
        'Desintegrate',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V, S, M (de la magnétite et une pincée de poussière)',
        'instantanée',
        'Un mince rayon de lumière verte jaillit de votre doigt pointé vers une cible située à portée dans votre champ de vision. La cible peut être une créature, un objet ou une création de force magique, comme un mur issu d''un _mur de force_.' || E'\n' || 'Une créature visée par ce sort doit faire un jet de sauvegarde de Dextérité. Si elle le rate, elle subit 10d6+40 dégâts de force. Si ces dégâts la réduisent à 0 point de vie, elle est désintégrée.' || E'\n' || 'Une créature désintégrée est réduite à l''état de fine poussière grise, tout comme tous les objets qu''elle porte et transporte, à l''exception des objets magiques. Pour ressusciter une créature ainsi désintégrée, il faut impérativement recourir à une _résurrection suprême_ ou à un _souhait_.' || E'\n' || 'Ce sort désintègre automatiquement les objets non magiques de taille Grande ou inférieure et les créations de force magique. Si la cible est un objet de taille Très Grande ou plus, le sort désintègre un cube de 3 mètres d''arête au sein de l''objet. Ce sort reste sans effet sur les objets magiques.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, les dégâts augmentent de 3d6 par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/disintegrate_spell_transmutation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Globe d''invulnérabilité',
        NULL,
        'Globe of Invulnerability',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Abjuration'),
        '1 action',
        'personnelle (3 mètres de diamètre)',
        'V, S, M (une perle de verre ou de cristal qui explose à la fin du sort)',
        'concentration, jusqu''à 1 minute',
        'Une barrière immobile scintille légèrement dans un rayon de 3 mètres autour de vous et persiste pendant toute la durée du sort.' || E'\n' || 'Tout sort de niveau 5 ou inférieur lancé depuis l''extérieur de la barrière se trouve dans l''incapacité d''affecter les créatures et les objets se trouvant à l''intérieur, même si l''incantateur lance son sort en utilisant un emplacement de niveau supérieur. Le sort peut très bien viser les créatures et les objets situés au sein de la barrière, mais il n''a aucun effet sur eux. De même, la zone protégée par la barrière est exclue de la zone affectée par les sorts de ces niveaux.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, la barrière bloque les sorts d''un niveau de plus par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/blobe_of_invulnerability_spell_abjuration_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Mauvais oeil',
        NULL,
        'Eyebite',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 action',
        'personnelle',
        'V, S',
        'concentration, jusqu''à 1 minute',
        'Pendant la durée du sort, vos yeux deviennent deux trous noirs regorgeant d''un pouvoir terrifiant. Une créature de votre choix, située dans votre champ de vision et dans un rayon de 18 mètres doit réussir un jet de sauvegarde de Sagesse ou se voir affectée par l''un des effets suivants, choisi par vos soins, pendant toute la durée du sort. À chacun de vos tours jusqu''à ce que le sort se termine, vous pouvez utiliser votre action pour viser une autre créature, mais vous ne pouvez pas reprendre pour cible une créature ayant déjà réussi un jet de sauvegarde contre l''incantation de mauvais œil en cours.' || E'\n' || '**Endormi**: La cible tombe inconsciente. Elle se réveille si elle subit le moindre dégât ou si une tierce personne utilise une action pour la réveiller en la secouant.' || E'\n' || '**Paniqué**: Vous terrorisez la cible. À chacun de ses tours, la cible terrorisée doit utiliser l''action se précipiter et s''éloigner de vous via l''itinéraire le plus rapide et le plus sûr, à moins qu''elle n''ait nulle part où aller. Cet effet se termine si la cible gagne un emplacement situé à au moins 18 mètres de vous et d''où elle ne vous voit plus.' || E'\n' || '**Écœuré**: La cible est désavantagée lors des jets d''attaque et des tests de caractéristique. Elle a droit à un nouveau jet de sauvegarde de Sagesse à la fin de chacun de ses tours. L''effet se termine si elle le réussit.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/eyebite_spell_necromancy_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Portail magique',
        'Portail arcanique',
        'Arcane Gate',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 action',
        '150 mètres',
        'V, S',
        'concentration, jusqu''à 10 minutes',
        'Vous créez des portails de téléportation reliés qui restent ouverts pendant toute la durée du sort. Choisissez deux points au sol, tous deux situés dans votre champ de vision, l''un devant se trouver dans un rayon de 3 mètres autour de vous, l''autre dans un rayon de 150 mètres autour de vous. Un portail circulaire de 3 mètres de diamètre s''ouvre en chaque point. Si un portail est censé s''ouvrir dans l''emplacement qu''occupe une créature, le sort échoue et l''incantation est gaspillée.' || E'\n' || 'Ces portails se présentent sous forme d''anneaux luisants en deux dimensions emplis de brume, qui flottent à quelques centimètres du sol, perpendiculaires aux points que vous avez choisis. Chaque anneau se voit seulement d''un côté (celui de votre choix), qui correspond à la face fonctionnant comme un portail.' || E'\n' || 'Toute créature ou tout objet entrant dans un portail ressort par l''autre, comme si les deux étaient adjacents. En revanche, il ne se passe rien si quelque chose traverse l''emplacement du portail en passant par la face qui ne fait pas office de portail. La brume qui emplit chaque portail est opaque et bloque toute visibilité. À votre tour, vous pouvez faire pivoter le portail par une action bonus pour que la face active se tourne dans une nouvelle direction.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/arcane_gate_conjuration_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Rayon de soleil',
        NULL,
        'Sunbeam',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Evocation'),
        '1 action',
        'personnelle (ligne de 18 mètres)',
        'V, S, M (une loupe)',
        'concentration, jusqu''à 1 minute',
        'Un rayon de vive lumière jaillit de votre main sur une ligne de 18 mètres de long pour 1,50 mètre de large. Chaque créature située sur cette ligne doit faire un jet de sauvegarde de Constitution. Celles qui échouent subissent 6d8 dégâts radiants et sont aveuglées jusqu''à la fin de votre prochain tour. Les autres subissent seulement la moitié des dégâts et ne sont pas aveuglées. Les vases et les morts-vivants sont désavantagés lors de ce jet de sauvegarde.' || E'\n' || 'Vous pouvez créer une nouvelle ligne de lumière en dépensant votre action à n''importe quel tour jusqu''à la fin du sort.' || E'\n' || 'Pendant toute la durée du sort, une boule de lumière brille dans votre main. Elle émet une vive lumière dans un rayon de 9 mètres et une faible lumière dans un rayon de 9 mètres supplémentaires. Cette lumière est de la même nature que la lumière du soleil.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/sunbeam_spell_evocation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Suggestion de groupe',
        NULL,
        'Mass Suggestion',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Enchantement'),
        '1 action',
        '18 mètres',
        'V, M (une langue de serpent et soit un rayon de miel, soit une goutte d''huile d''olive)',
        '24 heures',
        'Vous visez un maximum de douze créatures de votre choix, situées à portée et dans votre champ de vision et à même de vous entendre et de vous comprendre. Vous les influencez par magie de façon à ce qu''elles suivent la conduite que vous leur proposez (en seulement une phrase ou deux). Les créatures insensibles au charme sont immunisées contre ce sort. Vous devez formuler votre suggestion de manière à ce que la conduite à tenir semble tout à fait raisonnable. Si vous demandez à une créature de se poignarder, de se laisser tomber sur une lance, de s''immoler ou d''accomplir n''importe quelle action à l''évidence néfaste, l''effet du sort s''annule automatiquement.' || E'\n' || 'Chaque cible doit faire un jet de sauvegarde de Sagesse. En cas d''échec, la cible fait de son mieux pour suivre la conduite que vous lui avez suggérée et cela peut occuper toute la durée du sort. Si l''activité suggérée peut se finir plus rapidement, le sort se termine quand la cible a accompli ce que vous lui avez demandé.' || E'\n' || 'Vous pouvez spécifier des conditions qui déclenchent une activité spéciale pendant la durée du sort. Par exemple, vous pouvez suggérer à un groupe de soldats de donner tout leur argent au premier mendiant qu''ils rencontrent. Si les conditions ne sont pas remplies avant la fin du sort, la cible n''accomplit pas l''activité.' || E'\n' || 'Si vous (ou l''un de vos compagnons) blessez une créature affectée par ce sort, le sort se termine pour elle.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, la durée du sort est de 10 jours. Si vous utilisez un emplacement de niveau 8, elle est de 30 jours et si vous utilisez un emplacement de niveau 9, elle est d''un an et un jour.',
        NULL
    ),
    (
        'Vision suprême',
        NULL,
        'True Seeing',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Divination'),
        '1 action',
        'contact',
        'V, S, M (un collyre coûtant 25 po, fait de poudre de champignon, de safran et de graisse, que le sort consume)',
        '1 heure',
        'Grâce à ce sort, la créature consentante que vous touchez est capable de voir les choses telles qu''elles sont réellement. Pendant toute la durée du sort, la cible bénéficie de _vision parfaite_, repère les portes dérobées cachées par magie et voit le plan éthéré, tout cela dans un rayon de 36 mètres.',
        NULL
    ),
    (
        'Contingence',
        'Prévoyance',
        'Contingency',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '10 minutes',
        'personnelle',
        'V, S, M (une statuette de vous taillée dans l''ivoire et ornée de gemmes d''une valeur minimum de 1 500 po)',
        '10 jours',
        'Choisissez un sort de niveau 5 ou moins que vous êtes en mesure de lancer, qui possède une durée d''incantation d''une action, et qui peut vous prendre pour cible. Vous lancez ce sort (que l''on appelle le sort contingent) lors de l''incantation de la contingence. Vous dépensez donc les emplacements des deux sorts, mais le contingent ne fait pas effet immédiatement. Il s''activera lorsque certaines conditions seront remplies. Vous devez décrire ces dernières au moment où vous lancez les deux sorts. Par exemple, lors d''une contingence associée à une respiration aquatique, vous pouvez stipuler que la _respiration aquatique_ doit se déclencher quand vous vous trouvez immergé dans l''eau ou dans un liquide similaire.' || E'\n' || 'Le sort contingent prend effet dès que les circonstances sont remplies pour la première fois, que vous le vouliez ou non, ce qui met un terme à la _contingence_.' || E'\n' || 'Le sort contingent affecte uniquement votre personne, même s''il peut normalement affecter d''autres créatures. Vous ne pouvez utiliser qu''un seul sort de _contingence_ à la fois, si vous en lancez un second, les effets du précédent se dissipent. De plus, la _contingence_ prend fin si sa composante matérielle n''est plus sur votre personne.',
        NULL
    ),
    (
        'Convocations instantanées de Drawmij',
        NULL,
        'Drawmij''s Instant Summons',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Invocation'),
        '1 minute',
        'contact',
        'V, S, M (un saphir d''une valeur de 1 000 po)',
        'jusqu''à dissipation',
        'Vous touchez un objet pesant 5 kilos ou moins et dont la dimension la plus longue est de 1,80 mètre ou moins. Le sort laisse une marque invisible sur la surface de l''objet et inscrit le nom de l''objet sur le saphir que vous utilisez comme composante matérielle. Chaque fois que vous lancez ce sort, vous devez utiliser un saphir différent.' || E'\n' || 'Ensuite, vous pouvez utiliser une action quand vous le désirez pour prononcer le nom de l''objet et broyer le saphir. L''objet apparaît immédiatement dans votre main, en dépit des distances physiques et planaires, et le sort se termine.' || E'\n' || 'Si l''objet est actuellement porté ou transporté par quelqu''un d''autre, il n''arrive pas jusqu''à vous quand vous broyez le saphir, mais vous apprenez qui est la créature qui détient l''objet et vous savez à peu près où elle se trouve à ce moment-là.' || E'\n' || '_Dissipation de la magie_ ou un effet similaire appliqué sur le saphir met un terme à l''effet du sort.',
        NULL
    ),
    (
        'Mur de glace',
        NULL,
        'Wall of Ice',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '36 mètres',
        'V, S, M (un éclat de quartz)',
        'concentration, jusqu''à 10 minutes',
        'Vous créez un mur de glace sur une surface solide à portée. Vous pouvez lui donner une forme de dôme hémisphérique ou de sphère d''un rayon maximal de 3 mètres ou en faire une surface plane composée de dix panneaux de 3 mètres carrés. Chaque panneau doit être contigu à un autre. Quelle que soit sa forme, le mur fait 30 centimètres d''épaisseur et persiste pendant toute la durée du sort. Si le mur passe par l''emplacement d''une créature lorsqu''il apparaît, il la repousse d''un côté ou de l''autre et elle doit faire un jet de sauvegarde de Dextérité. Si elle échoue, elle subit 10d6 dégâts de froid, la moitié seulement si elle réussit.' || E'\n' || 'Le mur est un objet que l''on peut endommager et on peut donc y ouvrir des brèches. Il a une CA de 12 et 30 points de vie par section de 3 mètres de côté et il est vulnérable aux dégâts de feu. Si une section de 3 mètres de côté tombe à 0 point de vie, elle est détruite et laisse juste une zone d''air glacé à l''emplacement où se trouvait le pan de mur. Quand une créature se déplace dans cette zone frigorifique pour la première fois de son tour, elle doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle subit 5d6 dégâts de froid, la moitié seulement si elle réussit.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, les dégâts que le mur inflige en apparaissant augmentent de 2d6 et les dégâts provoqués par un passage dans la zone d''air glacé augmentent de 1d6 par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wallofice_spell_evocation_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Possession',
        'Urne magique',
        'Magic Jar',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Nécromancie'),
        '1 minute',
        'personnelle',
        'V, S, M (une gemme, un cristal, un reliquaire ou un autre réceptacle ornemental d''une valeur minimale de 500 po)',
        'jusqu''à dissipation',
        'Votre corps tombe en catatonie tandis que votre âme le quitte et pénètre dans le réceptacle utilisé comme composante de sort. Tant qu''elle se trouve là, vous percevez votre environnement comme si votre corps occupait le même espace que le réceptacle. En revanche, vous ne pouvez pas bouger ni utiliser de réaction. Vous ne pouvez accomplir qu''une action: projeter votre âme dans un rayon de 30 mètres au maximum autour du réceptacle, soit pour retourner dans votre corps (ce qui met fin au sort), soit pour prendre possession d''un autre corps humanoïde.' || E'\n' || 'Vous pouvez tenter de prendre possession de n''importe quel humanoïde situé dans votre champ de vision et dans un rayon de 30 mètres (sachant que les créatures protégées par une _protection contre le mal et le bien_ ou par un _cercle magique_ sont immunisées contre la possession). La cible doit faire un jet de sauvegarde de Charisme. Si elle échoue, votre âme s''installe dans son corps et la sienne est prisonnière du réceptacle. Si elle réussit son test, elle résiste à votre tentative de possession et vous ne pouvez plus essayer de la posséder pendant 24 heures.' || E'\n' || 'Une fois que vous avez pris possession du corps d''une autre créature, vous le contrôlez totalement. Vos statistiques de jeu sont remplacées par celles de cette créature, bien que vous conserviez votre alignement et vos valeurs d''Intelligence, de Sagesse et de Charisme. Vous conservez les avantages de vos pouvoirs de classe. Si votre cible possède des niveaux de classe, vous n''avez pas accès à ses pouvoirs de classe.' || E'\n' || 'Pendant ce temps, l''âme de la créature possédée perçoit ce qui se passe autour du réceptacle grâce à ses propres sens, mais elle ne peut pas se déplacer ni effectuer la moindre action.' || E'\n' || 'Tant que vous possédez le corps d''autrui, vous pouvez utiliser votre action pour le quitter et regagner le réceptacle s''il se trouve à 30 mètres de vous ou moins. L''âme de votre hôte retourne alors dans son propre corps. Si le corps de l''hôte périt alors que vous l''occupez, l''hôte meurt et vous devez faire un jet de sauvegarde de Charisme contre votre propre DD d''incantation. Si vous réussissez, vous regagnez le réceptacle, à condition qu''il se trouve dans un rayon de 30 mètres. Sinon, vous mourez.' || E'\n' || 'Si le réceptacle est détruit ou que le sort se termine, votre âme regagne immédiatement votre corps, à moins qu''il ne se trouve à plus de 30 mètres d''elle ou qu''il ait succombé, auquel cas vous périssez. Si l''âme d''une autre créature occupe le réceptacle au moment où il est détruit, cette âme retourne immédiatement dans son corps, à condition qu''il se trouve dans un rayon de 30 mètres et soit encore en vie Sinon, elle meurt. Le réceptacle est détruit quand Je sort se termine.',
        NULL
    ),
    (
        'Sphère glacée d''Otiluke',
        'Sphère glaciale d''Otiluke',
        'Otiluke''s Freezing Sphere',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole = 'Evocation'),
        '1 action',
        '90 mètres',
        'V, S, M (une petite sphère de cristal)',
        'instantanée',
        'Un globe d''énergie gelée jaillit de la pointe de votre doigt tendu et file vers un point de votre choix situé à portée. Là, il explose en une sphère de 18 mètres de rayon. Chaque créature de la zone doit faire un jet de sauvegarde de Constitution. Celles qui échouent subissent 10d6 dégâts de froid, les autres la moitié seulement. Si le globe frappe une surface aqueuse ou un liquide principalement constitué d''eau (ce qui n''inclut pas les créatures majoritairement composées d''eau), il gèle le liquide sur une épaisseur de 15 centimètres dans une zone de 9 mètres de côté. La glace subsiste une minute. Les créatures qui nageaient à la surface de l''étendue d''eau se retrouvent prises dans la glace. Une telle créature peut utiliser une action pour faire un test de Force contre le DD du jet de sauvegarde de votre sort afin de se libérer.' || E'\n' || 'Une fois que vous avez terminé l''incantation, vous pouvez attendre avant de lancer le globe. Dans ce cas, il ressemble à une bille de fronde glacée qui reste dans votre main. Vous pouvez alors le lancer à la main (à une portée de 12 mètres) ou avec une fronde (selon la portée habituelle de cette fronde) ou le donner à une créature qui peut faire de même. Le globe se brise à l''impact, explosant comme décrit dans la version normale du sort. Vous pouvez également poser le globe à terre sans le briser. Il explose au bout d''une minute s''il n''a pas été brisé avant.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, les dégâts augmentent de 1d6 par niveau au-delà du 6e.',
        NULL
    ),
    (
        'Création de mort-vivant',
        NULL,
        'Create Undead',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Nécromancie'),
        '1 minute',
        '3 mètres',
        'V, S, M (un pot d''argile rempli de poussière tombale, un pot d''argile rempli d''eau saumâtre et un onyx noir d''une valeur de 150 po par cadavre)',
        'instantanée',
        'Ce sort se lance uniquement de nuit. Choisissez jusqu''à trois cadavres de créatures humanoïdes de taille Moyenne ou Petite situés à portée. Chacun se change en goule placée sous votre contrôle. (Le MD dispose des statistiques de ces créatures).' || E'\n' || 'À chacun de vos tours, vous pouvez utiliser une action bonus pour contrôler mentalement les créatures que vous avez animées avec ce sort si elles se trouvent dans un rayon de 36 mètres (si vous en contrôlez plusieurs, vous pouvez en commander une ou plusieurs à la fois, à condition de donner le même ordre à toutes). Vous pouvez décider de l''action que la créature va entreprendre et de l''endroit où elle va se rendre lors de son prochain tour, ou donner des consignes plus génériques, comme de garder une salle ou un couloir. En l''absence d''ordre de votre part, la créature se contente de se défendre contre les créatures hostiles. Dès qu''une créature a reçu un ordre, elle s''y conforme jusqu''à avoir accompli sa tâche.' || E'\n' || 'La créature reste sous votre contrôle pendant 24 heures, après quoi elle cesse d''obéir aux ordres que vous lui avez donnés. Pour la maintenir sous votre contrôle pendant 24 heures de plus, vous devez lui relancer ce sort avant que les 24 heures de contrôle en cours ne se soient écoulées. Cette nouvelle utilisation du sort vous permet de réaffirmer votre contrôle sur un maximum de trois créatures que vous avez déjà animées via ce sort au lieu d''en animer de nouvelles.' || E'\n' || 'Àplushautniveau. Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, vous pouvez animer ou maintenir votre contrôle sur quatre goules. Quand vous le lancez à partir d''un emplacement de niveau 8, vous pouvez animer ou maintenir votre contrôle sur cinq goules ou deux blêmes ou deux nécrophages. Quand vous le lancez à partir d''un emplacement de niveau 9, vous pouvez animer ou maintenir votre contrôle sur six goules ou trois blêmes ou trois nécrophages ou deux momies.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/create_undead_spell_necromancy_school_baldursgate3_wiki_guide_64px.png'
    ),
    (
        'Invoquer une fée',
        'Invocation de fée',
        'Conjure Fey',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Invocation'),
        '1 minute',
        '27 mètres',
        'V, S',
        'concentration, jusqu''à 1 heure',
        'Vous invoquez une créature féerique dotée d''un indice de dangerosité de 6 ou moins, ou un esprit féerique qui revêt l''apparence d''une bête dotée d''un indice de dangerosité de 6 ou moins. La créature apparaît dans une case inoccupée située à portée dans votre champ de vision. Elle disparaît dès qu''elle tombe à O point de vie ou quand le sort se termine.' || E'\n' || 'La créature féerique se montre amicale envers vous et vos compagnons. Lancez l''initiative pour elle, sachant qu''elle dispose de ses propres tours de jeu. Elle obéit aux ordres verbaux que vous lui donnez (sans que cela vous demande d''utiliser une action), tant qu''ils ne vont pas à l''encontre de son alignement. En l''absence d''ordre, elle se défend contre les créatures hostiles, mais n''entreprend pas d''autre action.' || E'\n' || 'C''est le MD qui dispose des statistiques de la créature féerique.' || E'\n' || '**À plus haut niveau**: Si vous lancez ce sort en utilisant un emplacement de niveau 7 ou plus, l''indice de dangerosité de l''élémentaire augmente de 1 par niveau au-delà du 6e.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/faerie_fire_spell_baldursgate3_wiki_guide_150px_2.png'
    ),
    (
        'Pétrification',
        NULL,
        'Flesh to Stone',
        6,
        (SELECT id_ecole FROM ecole WHERE nom_ecole='Transmutation'),
        '1 action',
        '18 mètres',
        'V, S, M (une pincée de chaux, de l''eau et de la terre)',
        'concentration, jusqu''à 1 minute',
        'Vous tentez de changer en pierre une créature située à portée dans votre champ de vision. Si le corps de la cible est fait de chair, elle doit faire un jet de sauvegarde de Constitution. Si elle échoue, elle se retrouve entravée, car sa chair se met à durcir. Si elle réussit, elle n''est pas affectée.' || E'\n' || 'Une créature entravée par ce sort doit faire un nouveau jet de sauvegarde de Constitution à la fin de chacun de ses tours. Si elle en réussit trois, le sort se termine. Si elle en rate trois, elle se change en pierre et se retrouve pétrifiée pendant toute la durée du sort. Inutile que les succès et les échecs soient consécutifs, notez juste leur nombre jusqu''à ce que la cible arrive à en accumuler trois d''une sorte ou de l''autre.' || E'\n' || 'Si quelqu''un brise le corps physique de la cible alors qu''elle est pétrifiée, les difformités subies sont conservées par sa forme originelle quand elle la reprend.' || E'\n' || 'Si vous maintenez votre concentration sur ce sort jusqu''à la fin de la durée maximale, la cible est définitivement changée en pierre jusqu''à ce que quelqu''un dissipe l''effet.',
        'https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fleshtostone_spells_transmutation_school_baldursgate3_wiki_guide_64px.png'
    );