CREATE TABLE ecole(
    id_ecole serial PRIMARY KEY,
    nom_ecole varchar(50)
);

INSERT INTO ecole (nom_ecole)
VALUES ('Abjuration'),('Divination'),('Enchantement'),('Evocation'),('Illusion'),('Invocation'),('Nécromancie'),('Transmutation');

CREATE TABLE sort(
    id_sort serial PRIMARY KEY,
    nom_sort varchar(100),
    niveau_sort int,
    ecole_sort int,
    duree_incantation varchar(200),
    portee varchar(200),
    composantes text,
    duree_sort varchar(200),
    description text,
    img_sort text
);

CREATE OR REPLACE FUNCTION verif_nom_sort_existence()
    RETURNS TRIGGER AS $$
    BEGIN
        IF EXISTS (SELECT 1 FROM sort WHERE nom_sort = NEW.nom_sort) THEN
            RAISE EXCEPTION 'Le nom du sort % existe déjà dans la base de données.', NEW.nom_sort;
        END IF;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trig_verif_nom_sort_existence
BEFORE INSERT ON sort
FOR EACH ROW
EXECUTE FUNCTION verif_nom_sort_existence();


CREATE TABLE classe(
    id_classe serial PRIMARY KEY,
    nom_classe varchar(50),
    description text,
    de_vie varchar(10),
    caract_principale varchar(50),
    jet_sauv varchar(50),
    arm_skill text,
    img_classe text
);

INSERT INTO classe(nom_classe,description,de_vie,caract_principale,jet_sauv,arm_skill,img_classe)
VALUES
('Barbare','Un féroce combattant primitif capable de devenir enragé.','d12','Force','Force et Constitution','Armures légères et intermédiaires, bouclier, armes courantes et de guerre','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/barbarian_class_icon_alt.png'),
('Barde','Un mage capable d''inspirer ses camarades et dont les pouvoirs font écho à la musique de la création.','d8','Charisme','Dextérité et Charisme','Armure légère, armes courantes, arbalète de poing, épée longue, rapière, épée courte','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/bard_icon_class_bg3_wiki_guide.png'),
('Clerc','Un champion ecclésiastique qui use de magie divine au service d''une puissance supérieure.','d8','Sagesse','Sagesse et Charisme','Armures légères et intermédiaires, boucliers, armes courantes','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/cleric_class_icon_baldursgate3_wiki_guide_75px.png'),
('Druide','Un adepte de l''antique religion qui manie les pouvoirs de la nature (la lumière de la lune et la croissance végétale, le feu et la foudre) et peut revêtir une forme sauvage.', 'd8','Sagesse','Intelligence et Sagesse','Armures légères et intermédiaires (jamais en métal), bouclier (jamais en métal), gourdin, fléchette, javeline, masse d''armes, bâton, cimeterre, serpe, fronde, lance','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/druid_class_icon_1_baldursgate3_wiki_guide_75px.png'),
('Ensorceleur','Un mage qui tire ses pouvoirs magiques innés de sa lignée ou d''un don.','d6','Charisme','Constitution et Charisme','Dague, fléchette, fronde, bâton, arbalète légère','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/sorcerer_class_icon_baldurs_gate_3_wiki_guide_250px.png'),
('Guerrier','Un maître de guerre sachant utiliser tout un éventail d''armes et d''armures.','d10','Force ou Dextérité','Force et Constitution','Toutes les armures, bouclier, armes courantes et de guerre','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/fighter_class_icon_baldursgate3_wiki_guide_75px.png'),
('Magicien','Un utilisateur de magie académique capable de manipuler le tissu de la réalité','d6','Intelligence','Intelligence et Sagesse','Dague, fléchette, fronde, bâton, arbalète légère','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/warlock_class_icon_baldursgate3_wiki_guide_75px.png'),
('Moine','Un maître des arts martiaux qui puise dans sa puissance corporelle afin d''atteindre la perfection physique et spirituelle','d8','Dextérité et Sagesse','Force et Dextérité','Armes courantes, épée courte','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/monk_class_icon_baldursgate3_wiki_guide_75px.png'),
('Paladin','Un guerrier saint lié par un serment sacré','d10','Force et Charsime','Sagesse et Charisme','Toutes les armures, bouclier, armes courantes et de guerre','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/paladin_class_bg3_wiki_guide75px.png'),
('Rodeur','Un combattant qui recourt aux prouesses martiales et à la magie du monde naturel pour lutter contre les dangers rôdant en lisière de la civilisation','d10','Dextérité et Sagesse','Force et Dextérité','Armures légères et intermédiaires, bouclier, armes courantes et de guerre','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/ranger_class_icon_baldursgate3_wiki_guide_75px.png'),
('Roublard','Une crapule qui surmonte les obstacles et triomphe de ses ennemis grâce à sa discrétion et ses ruses','d8','Dextérité','Dextérité et Intelligence','Armures légères, armes courantes, arbalète de poing, épée longue, rapière, épée courte','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/rogue_class_icon_baldursgate3_wiki_guide_75px.png'),
('Sorcier','Un mage qui doit ses pouvoirs au marché passé avec une entité extraplanaire','d8','Charisme','Sagesse et Charisme','Armures légères, armes courantes','https://baldursgate3.wiki.fextralife.com/file/Baldurs-Gate-3/wizard_class_icon_baldursgate3_wiki_guide_75px.png');

CREATE TABLE race(
    id_race serial PRIMARY KEY,
    nom_race varchar(20)
);

INSERT INTO race(nom_race)
VALUES ('Elfe'),('Halfelin'),('Humain'),('Nain'),('Demi-elfe'),('Demi-orc'),('Gnome'),('Sangdragon'),('Tieffelin');

CREATE TABLE sortClasse(
    id_classe int REFERENCES classe(id_classe),
    id_sort int REFERENCES sort(id_sort)
);

INSERT INTO sortclasse
VALUES
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Bénédiction')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Bouclier de la foi')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Détection de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Détection du bien et du mal')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Détection du poison et des maladies')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Duel forcé')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Faveur divine')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe ardente')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe colérique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe tonitruante')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Héroïsme')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Injonction')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre le mal et le bien')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Purification de la nourriture et de l''eau')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Soin des blessures')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aide')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Arme magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe lumineuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Localiser un objet')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre le poison')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Restauration inférieure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Trouver une monture')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Zone de vérité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Arme élémentaire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura de vitalité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura du croisé')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Création de nourriture et d''eau')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Dissipation de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe aveuglante')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Lever une malédiction')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Lumière du jour')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Revigorer')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura de pureté')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura de vie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Bannissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe assommante')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Localiser une créature')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre la mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle de pouvoir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Coercition mystique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Dissipation du mal et du bien')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Frappe du bannissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Relever les morts')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Vague destructrice')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Sens divin')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Imposition des mains')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Châtiment divin')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura de protection')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Aura de courage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Paladin'),(SELECT id_sort FROM sort WHERE nom_sort='Contact purifiant'));

INSERT INTO sortclasse
VALUES
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Amis')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Aspersion acide')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Bouffée de poison')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Contact glacial')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Illusion mineure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Lumière')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Lumières dansantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Main du mage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Message')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Poigne électrique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Prestidigitation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre les armes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Rayon de givre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Réparation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Trait de feu')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Viser juste')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Armure du mage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Bouclier')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Carreau ensorcelé')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Charme-personne')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Compréhension des langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Couleurs dansantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Déguisement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Détection de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Image silencieuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Léger comme une plume')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mains brûlantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nappe de brouillard')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Orbe chromatique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Projectile magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Rayon empoisonné')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Repli expéditif')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Saut')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Simulacre de vie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Sommeil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Vague tonnante')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Agrandir/rétrécir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Amélioration de caractéristique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Bourrasque')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Briser')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Cécité/surdité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Couronne du dément')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Déblocage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Détection des pensées')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Flou')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Force fantasmagorique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Image miroir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un humanoïde')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Invisibilité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Lévitation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Modifier son apparence')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nuée de dagues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Pas brumeux')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Pattes d''araignée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Rayon ardent')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Ténèbres')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Toile d''araignée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Vision dans le noir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Voir l''invisible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Boule de feu')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Clairvoyance')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Clignotement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Contresort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Dissipation de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Eclair')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Forme gazeuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Hâte')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Image majeure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Lenteur')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Lumière du jour')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Marche sur l''eau')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Motif hypnotique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nuage puant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Peur')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre l''énergie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Respiration aquatique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Tempête de neige')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Vol')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Bannissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Confusion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer une bête')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Flétrissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Invisibilité supérieure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Métamorphose')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mur de feu')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Peau de pierre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Porte dimensionnelle')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Tempête de grêle')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Animation des objets')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Apparence trompeuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle de téléportation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Cône de froid')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Création')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer un humanoïde')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Fléau d''insectes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mur de pierre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nuage mortel')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Télékinésie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle de mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Chaine d''éclairs')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Déplacer la terre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Désintégration')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Globe d''invulnérabilité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mauvais oeil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Portail magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Rayon de soleil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion de groupe')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Vision suprême')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Boule de feu à explosion retardée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Changement de plan')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Doigt de mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Embruns prismatiques')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Forme éthérée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Inversion de la gravité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Téléportation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Tempête de feu')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Eclat du soleil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir étourdissant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nuage incendiaire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Tremblement de terre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Arrêt du temps')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir mortel')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Nuée de météores')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Portail')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Ensorceleur'),(SELECT id_sort FROM sort WHERE nom_sort='Souhait'));

INSERT INTO sortclasse
VALUES
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Amis')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Bouffée de poison')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Contact glacial')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Explosion occulte')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Illusion mineure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Main du mage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Prestidigitation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre les armes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Viser juste')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Armure d''Agathys')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Carreau ensorcelé')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Charme-personne')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Compréhension des langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Maléfice')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre le mal et le bien')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Repli expéditif')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Représailles infernales')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Serviteur invisible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Tentacules d''Hadar')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Texte illusoire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Briser')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Couronne du dément')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Envoûtement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Image miroir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un humanoïde')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Invisibilité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Nuée de dagues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Pas brumeux')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Pattes d''araignée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Rayon affaiblissant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Ténèbres')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Envoûtement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Image miroir')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Appétit d''Hadar')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Caresse du vampire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Contresort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Dissipation de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Forme gazeuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Image majeure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Lever une malédiction')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Motif hypnotique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Peur')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Vol')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Bannissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Flétrissement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Porte dimensionnelle')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Terrain hallucinatoire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Contacter un autre plan')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Rêve')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Scrutation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle de mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Création de mort-vivant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Invoquer une fée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Mauvais oeil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Pétrification')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Portail magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion de groupe')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Vision suprême')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Cage de force')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Changement de plan')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Doigt de mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Forme éthérée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Bagou')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Demi-plan')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Esprit faible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir étourdissant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Emprisonnement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Métamorphose suprême')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir mortel')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Prémonition')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Sorcier'),(SELECT id_sort FROM sort WHERE nom_sort='Projection astrale'));


INSERT INTO sortclasse
VALUES
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Amis')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Illusion mineure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Lumière')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Lumières dansantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Main du mage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Message')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Moquerie cruelle')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Prestidigitation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Protection contre les armes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Réparation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Viser juste')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Amitié avec les animaux')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Charme-personne')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Communication avec les animaux')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Compréhension des langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Déguisement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Détection de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Fléau')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Fou rire de Tasha')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Grande foulée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Héroïsme')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Identification')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Image silencieuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Léger comme une plume')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Lueurs féériques')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de guérison')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Murmures dissonants')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Serviteur invisible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Soin des blessures')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Sommeil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Texte illusoire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Vague tonnante')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Amélioration de caractéristique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Apaisement des émotions')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Bouche magique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Briser')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Cécité/surdité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Chauffer le métal')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Couronne du dément')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Déblocage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Détection des pensées')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Envoûtement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Force fantasmagorique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un humanoïde')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Invisibilité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Localiser des animaux ou des plantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Localiser un objet')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Messager animal')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Nuée de dagues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Restauration inférieure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Silence')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Voir l''invisible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Zone de vérité')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Clairvoyance')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Communication avec les morts')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Communication avec les plantes')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Croissance végétale')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Dissipation de la magie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Envoi de message')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Feindre la mort')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Glyphe de protection')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Image majeure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Jeter une malédiction')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Langues')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Motif hypnotique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Non-détection')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Nuage puant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Petite hutte de Léomund')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Peur')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Compulsion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Confusion')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Invisibilité supérieure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Liberté de mouvement')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Localiser une créature')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Métamorphose')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Porte dimensionnelle')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Terrain hallucinatoire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Animation des objets')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Apparence trompeuse')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Cercle de téléportation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Coercition mystique')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer un humanoïde')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Entrave planaire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Eveil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Immobiliser un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Légende')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Modification de mémoire')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Relever les morts')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Restauration supérieure')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Rêve')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Scrutation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Soin des blessures de groupe')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Tromperie')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Danse irrésistible d''Otto')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Illusion programmée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mauvais oeil')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Protections et sceaux')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Suggestion de groupe')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Trouver un chemin')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Vision suprême')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Cage de force')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Epée de Mordenkainen')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Forme éthérée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Image projetée')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Manoir somptueux de Mordenkainen')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mirage')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Régénération')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Résurrection')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Symbole')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Téléportation')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Bagou')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Dominer un monstre')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Esprit faible')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Esprit impénétrable')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir étourdissant')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Métamorphose suprême')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir mortel')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Mot de pouvoir guérisseur')),
    ((SELECT id_classe FROM classe WHERE nom_classe='Barde'),(SELECT id_sort FROM sort WHERE nom_sort='Prémonition'));